// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/infra/monitoring/health/health_client.go
//
// Generated by this command:
//
//	mockgen -destination=pkg/infra/monitoring/health/mocks/health_client_mock.go -package=mockhealth -source=pkg/infra/monitoring/health/health_client.go
//

// Package mockhealth is a generated GoMock package.
package mockhealth

import (
	health "carduka/bidsvc/pkg/infra/monitoring/health"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMonitoringHealthClient is a mock of MonitoringHealthClient interface.
type MockMonitoringHealthClient struct {
	ctrl     *gomock.Controller
	recorder *MockMonitoringHealthClientMockRecorder
}

// MockMonitoringHealthClientMockRecorder is the mock recorder for MockMonitoringHealthClient.
type MockMonitoringHealthClientMockRecorder struct {
	mock *MockMonitoringHealthClient
}

// NewMockMonitoringHealthClient creates a new mock instance.
func NewMockMonitoringHealthClient(ctrl *gomock.Controller) *MockMonitoringHealthClient {
	mock := &MockMonitoringHealthClient{ctrl: ctrl}
	mock.recorder = &MockMonitoringHealthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitoringHealthClient) EXPECT() *MockMonitoringHealthClientMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockMonitoringHealthClient) Check(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockMonitoringHealthClientMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockMonitoringHealthClient)(nil).Check), ctx)
}

// Configure mocks base method.
func (m *MockMonitoringHealthClient) Configure(arg0 ...health.Option) health.MonitoringHealthClient {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Configure", varargs...)
	ret0, _ := ret[0].(health.MonitoringHealthClient)
	return ret0
}

// Configure indicates an expected call of Configure.
func (mr *MockMonitoringHealthClientMockRecorder) Configure(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configure", reflect.TypeOf((*MockMonitoringHealthClient)(nil).Configure), arg0...)
}

// WithDbConnAttempts mocks base method.
func (m *MockMonitoringHealthClient) WithDbConnAttempts(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithDbConnAttempts", arg0)
}

// WithDbConnAttempts indicates an expected call of WithDbConnAttempts.
func (mr *MockMonitoringHealthClientMockRecorder) WithDbConnAttempts(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDbConnAttempts", reflect.TypeOf((*MockMonitoringHealthClient)(nil).WithDbConnAttempts), arg0)
}

// WithDbConnTimeout mocks base method.
func (m *MockMonitoringHealthClient) WithDbConnTimeout(arg0 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithDbConnTimeout", arg0)
}

// WithDbConnTimeout indicates an expected call of WithDbConnTimeout.
func (mr *MockMonitoringHealthClientMockRecorder) WithDbConnTimeout(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDbConnTimeout", reflect.TypeOf((*MockMonitoringHealthClient)(nil).WithDbConnTimeout), arg0)
}
