// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/adapters/postgres/queriers.go
//
// Generated by this command:
//
//	mockgen -destination=app/internal/adapters/postgres/mocks/mock_queries.go -package=mockpostgresrepo -source=app/internal/adapters/postgres/queriers.go
//

// Package mockpostgresrepo is a generated GoMock package.
package mockpostgresrepo

import (
	context "context"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	postgresql "github.com/sanctumlabs/curtz/app/internal/adapters/postgres/sql"
	gomock "go.uber.org/mock/gomock"
)

// MockUrlWriteQuerier is a mock of UrlWriteQuerier interface.
type MockUrlWriteQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockUrlWriteQuerierMockRecorder
	isgomock struct{}
}

// MockUrlWriteQuerierMockRecorder is the mock recorder for MockUrlWriteQuerier.
type MockUrlWriteQuerierMockRecorder struct {
	mock *MockUrlWriteQuerier
}

// NewMockUrlWriteQuerier creates a new mock instance.
func NewMockUrlWriteQuerier(ctrl *gomock.Controller) *MockUrlWriteQuerier {
	mock := &MockUrlWriteQuerier{ctrl: ctrl}
	mock.recorder = &MockUrlWriteQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlWriteQuerier) EXPECT() *MockUrlWriteQuerierMockRecorder {
	return m.recorder
}

// QueryCreateKeyword mocks base method.
func (m *MockUrlWriteQuerier) QueryCreateKeyword(ctx context.Context, params postgresql.QueryCreateKeywordParams) (postgresql.Keyword, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryCreateKeyword", ctx, params)
	ret0, _ := ret[0].(postgresql.Keyword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryCreateKeyword indicates an expected call of QueryCreateKeyword.
func (mr *MockUrlWriteQuerierMockRecorder) QueryCreateKeyword(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCreateKeyword", reflect.TypeOf((*MockUrlWriteQuerier)(nil).QueryCreateKeyword), ctx, params)
}

// QueryCreateUrl mocks base method.
func (m *MockUrlWriteQuerier) QueryCreateUrl(ctx context.Context, params postgresql.QueryCreateUrlParams) (postgresql.Url, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryCreateUrl", ctx, params)
	ret0, _ := ret[0].(postgresql.Url)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryCreateUrl indicates an expected call of QueryCreateUrl.
func (mr *MockUrlWriteQuerierMockRecorder) QueryCreateUrl(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCreateUrl", reflect.TypeOf((*MockUrlWriteQuerier)(nil).QueryCreateUrl), ctx, params)
}

// QueryUrlStatusByName mocks base method.
func (m *MockUrlWriteQuerier) QueryUrlStatusByName(ctx context.Context, name string) (postgresql.UrlStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryUrlStatusByName", ctx, name)
	ret0, _ := ret[0].(postgresql.UrlStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryUrlStatusByName indicates an expected call of QueryUrlStatusByName.
func (mr *MockUrlWriteQuerierMockRecorder) QueryUrlStatusByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryUrlStatusByName", reflect.TypeOf((*MockUrlWriteQuerier)(nil).QueryUrlStatusByName), ctx, name)
}

// MockUserReadQuerier is a mock of UserReadQuerier interface.
type MockUserReadQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockUserReadQuerierMockRecorder
	isgomock struct{}
}

// MockUserReadQuerierMockRecorder is the mock recorder for MockUserReadQuerier.
type MockUserReadQuerierMockRecorder struct {
	mock *MockUserReadQuerier
}

// NewMockUserReadQuerier creates a new mock instance.
func NewMockUserReadQuerier(ctrl *gomock.Controller) *MockUserReadQuerier {
	mock := &MockUserReadQuerier{ctrl: ctrl}
	mock.recorder = &MockUserReadQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserReadQuerier) EXPECT() *MockUserReadQuerierMockRecorder {
	return m.recorder
}

// QueryAllUsers mocks base method.
func (m *MockUserReadQuerier) QueryAllUsers(ctx context.Context, arg postgresql.QueryAllUsersParams) ([]postgresql.QueryAllUsersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryAllUsers", ctx, arg)
	ret0, _ := ret[0].([]postgresql.QueryAllUsersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryAllUsers indicates an expected call of QueryAllUsers.
func (mr *MockUserReadQuerierMockRecorder) QueryAllUsers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryAllUsers", reflect.TypeOf((*MockUserReadQuerier)(nil).QueryAllUsers), ctx, arg)
}

// QueryUserByEmail mocks base method.
func (m *MockUserReadQuerier) QueryUserByEmail(ctx context.Context, email string) (postgresql.QueryUserByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryUserByEmail", ctx, email)
	ret0, _ := ret[0].(postgresql.QueryUserByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryUserByEmail indicates an expected call of QueryUserByEmail.
func (mr *MockUserReadQuerierMockRecorder) QueryUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryUserByEmail", reflect.TypeOf((*MockUserReadQuerier)(nil).QueryUserByEmail), ctx, email)
}

// QueryUserById mocks base method.
func (m *MockUserReadQuerier) QueryUserById(ctx context.Context, id pgtype.UUID) (postgresql.QueryUserByIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryUserById", ctx, id)
	ret0, _ := ret[0].(postgresql.QueryUserByIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryUserById indicates an expected call of QueryUserById.
func (mr *MockUserReadQuerierMockRecorder) QueryUserById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryUserById", reflect.TypeOf((*MockUserReadQuerier)(nil).QueryUserById), ctx, id)
}

// QueryUserByUsername mocks base method.
func (m *MockUserReadQuerier) QueryUserByUsername(ctx context.Context, username string) (postgresql.QueryUserByUsernameRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryUserByUsername", ctx, username)
	ret0, _ := ret[0].(postgresql.QueryUserByUsernameRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryUserByUsername indicates an expected call of QueryUserByUsername.
func (mr *MockUserReadQuerierMockRecorder) QueryUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryUserByUsername", reflect.TypeOf((*MockUserReadQuerier)(nil).QueryUserByUsername), ctx, username)
}
