// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/infra/queue/inmem/interface.go
//
// Generated by this command:
//
//	mockgen -destination=pkg/infra/queue/inmem/mocks/interface_mock.go -package=mockinmemqueue -source=pkg/infra/queue/inmem/interface.go
//

// Package mockinmemqueue is a generated GoMock package.
package mockinmemqueue

import (
	queue "carduka/bidsvc/pkg/infra/queue"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInMemQueueMessagePublisher is a mock of InMemQueueMessagePublisher interface.
type MockInMemQueueMessagePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockInMemQueueMessagePublisherMockRecorder
}

// MockInMemQueueMessagePublisherMockRecorder is the mock recorder for MockInMemQueueMessagePublisher.
type MockInMemQueueMessagePublisherMockRecorder struct {
	mock *MockInMemQueueMessagePublisher
}

// NewMockInMemQueueMessagePublisher creates a new mock instance.
func NewMockInMemQueueMessagePublisher(ctrl *gomock.Controller) *MockInMemQueueMessagePublisher {
	mock := &MockInMemQueueMessagePublisher{ctrl: ctrl}
	mock.recorder = &MockInMemQueueMessagePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInMemQueueMessagePublisher) EXPECT() *MockInMemQueueMessagePublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockInMemQueueMessagePublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockInMemQueueMessagePublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockInMemQueueMessagePublisher)(nil).Close))
}

// Publish mocks base method.
func (m *MockInMemQueueMessagePublisher) Publish(ctx context.Context, message queue.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockInMemQueueMessagePublisherMockRecorder) Publish(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockInMemQueueMessagePublisher)(nil).Publish), ctx, message)
}

// MockInMemQueueEventPublisher is a mock of InMemQueueEventPublisher interface.
type MockInMemQueueEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockInMemQueueEventPublisherMockRecorder
}

// MockInMemQueueEventPublisherMockRecorder is the mock recorder for MockInMemQueueEventPublisher.
type MockInMemQueueEventPublisherMockRecorder struct {
	mock *MockInMemQueueEventPublisher
}

// NewMockInMemQueueEventPublisher creates a new mock instance.
func NewMockInMemQueueEventPublisher(ctrl *gomock.Controller) *MockInMemQueueEventPublisher {
	mock := &MockInMemQueueEventPublisher{ctrl: ctrl}
	mock.recorder = &MockInMemQueueEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInMemQueueEventPublisher) EXPECT() *MockInMemQueueEventPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockInMemQueueEventPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockInMemQueueEventPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockInMemQueueEventPublisher)(nil).Close))
}

// Publish mocks base method.
func (m *MockInMemQueueEventPublisher) Publish(ctx context.Context, event queue.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockInMemQueueEventPublisherMockRecorder) Publish(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockInMemQueueEventPublisher)(nil).Publish), ctx, event)
}

// MockInMemQueueEventConsumer is a mock of InMemQueueEventConsumer interface.
type MockInMemQueueEventConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockInMemQueueEventConsumerMockRecorder
}

// MockInMemQueueEventConsumerMockRecorder is the mock recorder for MockInMemQueueEventConsumer.
type MockInMemQueueEventConsumerMockRecorder struct {
	mock *MockInMemQueueEventConsumer
}

// NewMockInMemQueueEventConsumer creates a new mock instance.
func NewMockInMemQueueEventConsumer(ctrl *gomock.Controller) *MockInMemQueueEventConsumer {
	mock := &MockInMemQueueEventConsumer{ctrl: ctrl}
	mock.recorder = &MockInMemQueueEventConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInMemQueueEventConsumer) EXPECT() *MockInMemQueueEventConsumerMockRecorder {
	return m.recorder
}

// StartConsumer mocks base method.
func (m *MockInMemQueueEventConsumer) StartConsumer(fn queue.EventWorker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartConsumer", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartConsumer indicates an expected call of StartConsumer.
func (mr *MockInMemQueueEventConsumerMockRecorder) StartConsumer(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartConsumer", reflect.TypeOf((*MockInMemQueueEventConsumer)(nil).StartConsumer), fn)
}

// MockInMemQueueMessageConsumer is a mock of InMemQueueMessageConsumer interface.
type MockInMemQueueMessageConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockInMemQueueMessageConsumerMockRecorder
}

// MockInMemQueueMessageConsumerMockRecorder is the mock recorder for MockInMemQueueMessageConsumer.
type MockInMemQueueMessageConsumerMockRecorder struct {
	mock *MockInMemQueueMessageConsumer
}

// NewMockInMemQueueMessageConsumer creates a new mock instance.
func NewMockInMemQueueMessageConsumer(ctrl *gomock.Controller) *MockInMemQueueMessageConsumer {
	mock := &MockInMemQueueMessageConsumer{ctrl: ctrl}
	mock.recorder = &MockInMemQueueMessageConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInMemQueueMessageConsumer) EXPECT() *MockInMemQueueMessageConsumerMockRecorder {
	return m.recorder
}

// StartConsumer mocks base method.
func (m *MockInMemQueueMessageConsumer) StartConsumer(fn queue.MessageWorker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartConsumer", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartConsumer indicates an expected call of StartConsumer.
func (mr *MockInMemQueueMessageConsumerMockRecorder) StartConsumer(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartConsumer", reflect.TypeOf((*MockInMemQueueMessageConsumer)(nil).StartConsumer), fn)
}
