version: "3.8"

services:
  db:
    image: postgres:12
    container_name: curtz-db
    environment:
      POSTGRES_USER: curtz-user
      POSTGRES_PASSWORD: curtz-pass
      POSTGRES_DB: curtz-db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  db1:
    image: cockroachdb/cockroach:v21.1.3
    container_name: curtz-db1
    hostname: db1
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start --insecure --join=db1,db2,db3 && ./cockroach init --insecure
    volumes:
      - db1:/cockroach/cockroach-data

  db2:
    image: cockroachdb/cockroach:v21.1.3
    container_name: curtz-db2
    hostname: db2
    command: start --insecure --join=db1,db2,db3 && ./cockroach init --insecure
    volumes:
      - db2:/cockroach/cockroach-data

  db3:
    image: cockroachdb/cockroach:v21.1.3
    container_name: curtz-db3
    hostname: db3
    command: start --insecure --join=db1,db2,db3 && ./cockroach init --insecure
    volumes:
      - db3:/cockroach/cockroach-data

  documentdb:
    image: mongo:4.4.14
    container_name: curtz-documentdb
    hostname: documentdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: curtzUser
      MONGO_INITDB_ROOT_PASSWORD: curtzPassword
      MONGO_INITDB_DATABASE: curtzdb
      MONGO_INITDB_USER: curtzUser
      MONGO_INITDB_PASSWORD: curtzPassword
    volumes:
      - docdb:/data/db

volumes:
  db:
  db1:
  db2:
  db3:
  docdb:
