version: "3.8"

services:
  documentdb:
    image: mongo:4.4.14
    container_name: curtz-documentdb
    hostname: documentdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: curtzUser
      MONGO_INITDB_ROOT_PASSWORD: curtzPassword
      MONGO_INITDB_DATABASE: curtzdb
      MONGO_INITDB_USER: curtzUser
      MONGO_INITDB_PASSWORD: curtzPassword
    volumes:
      - docdb:/data/db

  cache:
    image: redis:7.0.2
    container_name: curtz-cache
    hostname: cache
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  docdb:
  cache:
