// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/register": {
          "post": {
            "description": "Register a new user account",
            "summary": "Registers a new user account",
            "consumes": [
              "application/json"
            ],
            "produces": [
              "application/json"
            ],
            "tags": [
              "auth"
            ],
            "parameters": [
              {
                "description": "new user",
                "name": "user",
                "in": "body",
                "required": true,
                "schema": {
                  "$ref": "#/definitions/auth.registerRequestDto"
                }
              }
            ],
            "responses": {
              "200": {
                "description": "Successfully created user",
                "schema": {
                  "$ref": "#/definitions/auth.userResponseDto"
                }
              }
            }
          }
        }
    },
    "definitions": {
        "auth.registerRequestDto": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "example": "johndoe@example.com"
            },
            "password": {
              "type": "string",
              "example": "strong password"
            }
          }
        },
        "auth.userResponseDto": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "example": "gciabeoaufbeoaurea"
            },
            "email": {
              "type": "string",
              "example": "johndoe@example.com"
            },
            "created_at": {
              "type": "string",
              "example": "johndoe@example.com"
            },
            "updated_at": {
              "type": "string",
              "example": "johndoe@example.com"
            }
          }
        }
      }    
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "http://localhost:8085",
	BasePath:         "/api/v1/curtz",
	Schemes:          []string{"http", "https"},
	Title:            "Curtz API",
	Description:      "URL Shortener Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
