// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/domain/url/repository.go
//
// Generated by this command:
//
//	mockgen -destination=app/internal/domain/url/mocks/mock_repository.go -package=urlmock -source=app/internal/domain/url/repository.go
//

// Package urlmock is a generated GoMock package.
package urlmock

import (
	context "context"
	reflect "reflect"

	repository "github.com/sanctumlabs/curtz/app/internal/core/ports/repository"
	url "github.com/sanctumlabs/curtz/app/internal/domain/url"
	common "github.com/sanctumlabs/curtz/app/internal/pkg/common"
	gomock "go.uber.org/mock/gomock"
)

// MockUrlRepository is a mock of UrlRepository interface.
type MockUrlRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUrlRepositoryMockRecorder
	isgomock struct{}
}

// MockUrlRepositoryMockRecorder is the mock recorder for MockUrlRepository.
type MockUrlRepositoryMockRecorder struct {
	mock *MockUrlRepository
}

// NewMockUrlRepository creates a new mock instance.
func NewMockUrlRepository(ctrl *gomock.Controller) *MockUrlRepository {
	mock := &MockUrlRepository{ctrl: ctrl}
	mock.recorder = &MockUrlRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlRepository) EXPECT() *MockUrlRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUrlRepository) Create(ctx context.Context, entity url.URL) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUrlRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUrlRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockUrlRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUrlRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUrlRepository)(nil).Delete), ctx, id)
}

// FetchAll mocks base method.
func (m *MockUrlRepository) FetchAll(ctx context.Context, params common.RequestParams) (repository.FetchRecordsResponse[url.URL], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, params)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[url.URL])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUrlRepositoryMockRecorder) FetchAll(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUrlRepository)(nil).FetchAll), ctx, params)
}

// FetchByCustomAlias mocks base method.
func (m *MockUrlRepository) FetchByCustomAlias(ctx context.Context, customAlias string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByCustomAlias", ctx, customAlias)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByCustomAlias indicates an expected call of FetchByCustomAlias.
func (mr *MockUrlRepositoryMockRecorder) FetchByCustomAlias(ctx, customAlias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByCustomAlias", reflect.TypeOf((*MockUrlRepository)(nil).FetchByCustomAlias), ctx, customAlias)
}

// FetchById mocks base method.
func (m *MockUrlRepository) FetchById(ctx context.Context, id string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchById", ctx, id)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchById indicates an expected call of FetchById.
func (mr *MockUrlRepositoryMockRecorder) FetchById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchById", reflect.TypeOf((*MockUrlRepository)(nil).FetchById), ctx, id)
}

// FetchByOriginalUrl mocks base method.
func (m *MockUrlRepository) FetchByOriginalUrl(ctx context.Context, originalUrl string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByOriginalUrl", ctx, originalUrl)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByOriginalUrl indicates an expected call of FetchByOriginalUrl.
func (mr *MockUrlRepositoryMockRecorder) FetchByOriginalUrl(ctx, originalUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByOriginalUrl", reflect.TypeOf((*MockUrlRepository)(nil).FetchByOriginalUrl), ctx, originalUrl)
}

// FetchByShortCode mocks base method.
func (m *MockUrlRepository) FetchByShortCode(ctx context.Context, shortCode string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByShortCode", ctx, shortCode)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByShortCode indicates an expected call of FetchByShortCode.
func (mr *MockUrlRepositoryMockRecorder) FetchByShortCode(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByShortCode", reflect.TypeOf((*MockUrlRepository)(nil).FetchByShortCode), ctx, shortCode)
}

// FetchByStatus mocks base method.
func (m *MockUrlRepository) FetchByStatus(ctx context.Context, status url.URLStatus) (repository.FetchRecordsResponse[url.URL], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByStatus", ctx, status)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[url.URL])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByStatus indicates an expected call of FetchByStatus.
func (mr *MockUrlRepositoryMockRecorder) FetchByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByStatus", reflect.TypeOf((*MockUrlRepository)(nil).FetchByStatus), ctx, status)
}

// FetchByUserId mocks base method.
func (m *MockUrlRepository) FetchByUserId(ctx context.Context, userId string) (repository.FetchRecordsResponse[url.URL], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUserId", ctx, userId)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[url.URL])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUserId indicates an expected call of FetchByUserId.
func (mr *MockUrlRepositoryMockRecorder) FetchByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUserId", reflect.TypeOf((*MockUrlRepository)(nil).FetchByUserId), ctx, userId)
}

// SoftDelete mocks base method.
func (m *MockUrlRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUrlRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUrlRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockUrlRepository) Update(ctx context.Context, entity url.URL) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUrlRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUrlRepository)(nil).Update), ctx, entity)
}

// MockUrlWriteRepository is a mock of UrlWriteRepository interface.
type MockUrlWriteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUrlWriteRepositoryMockRecorder
	isgomock struct{}
}

// MockUrlWriteRepositoryMockRecorder is the mock recorder for MockUrlWriteRepository.
type MockUrlWriteRepositoryMockRecorder struct {
	mock *MockUrlWriteRepository
}

// NewMockUrlWriteRepository creates a new mock instance.
func NewMockUrlWriteRepository(ctrl *gomock.Controller) *MockUrlWriteRepository {
	mock := &MockUrlWriteRepository{ctrl: ctrl}
	mock.recorder = &MockUrlWriteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlWriteRepository) EXPECT() *MockUrlWriteRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUrlWriteRepository) Create(ctx context.Context, entity url.URL) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUrlWriteRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUrlWriteRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockUrlWriteRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUrlWriteRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUrlWriteRepository)(nil).Delete), ctx, id)
}

// SoftDelete mocks base method.
func (m *MockUrlWriteRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUrlWriteRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUrlWriteRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockUrlWriteRepository) Update(ctx context.Context, entity url.URL) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUrlWriteRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUrlWriteRepository)(nil).Update), ctx, entity)
}

// MockUrlReadRepository is a mock of UrlReadRepository interface.
type MockUrlReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUrlReadRepositoryMockRecorder
	isgomock struct{}
}

// MockUrlReadRepositoryMockRecorder is the mock recorder for MockUrlReadRepository.
type MockUrlReadRepositoryMockRecorder struct {
	mock *MockUrlReadRepository
}

// NewMockUrlReadRepository creates a new mock instance.
func NewMockUrlReadRepository(ctrl *gomock.Controller) *MockUrlReadRepository {
	mock := &MockUrlReadRepository{ctrl: ctrl}
	mock.recorder = &MockUrlReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlReadRepository) EXPECT() *MockUrlReadRepositoryMockRecorder {
	return m.recorder
}

// FetchAll mocks base method.
func (m *MockUrlReadRepository) FetchAll(ctx context.Context, params common.RequestParams) (repository.FetchRecordsResponse[url.URL], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, params)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[url.URL])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUrlReadRepositoryMockRecorder) FetchAll(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUrlReadRepository)(nil).FetchAll), ctx, params)
}

// FetchByCustomAlias mocks base method.
func (m *MockUrlReadRepository) FetchByCustomAlias(ctx context.Context, customAlias string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByCustomAlias", ctx, customAlias)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByCustomAlias indicates an expected call of FetchByCustomAlias.
func (mr *MockUrlReadRepositoryMockRecorder) FetchByCustomAlias(ctx, customAlias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByCustomAlias", reflect.TypeOf((*MockUrlReadRepository)(nil).FetchByCustomAlias), ctx, customAlias)
}

// FetchById mocks base method.
func (m *MockUrlReadRepository) FetchById(ctx context.Context, id string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchById", ctx, id)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchById indicates an expected call of FetchById.
func (mr *MockUrlReadRepositoryMockRecorder) FetchById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchById", reflect.TypeOf((*MockUrlReadRepository)(nil).FetchById), ctx, id)
}

// FetchByOriginalUrl mocks base method.
func (m *MockUrlReadRepository) FetchByOriginalUrl(ctx context.Context, originalUrl string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByOriginalUrl", ctx, originalUrl)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByOriginalUrl indicates an expected call of FetchByOriginalUrl.
func (mr *MockUrlReadRepositoryMockRecorder) FetchByOriginalUrl(ctx, originalUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByOriginalUrl", reflect.TypeOf((*MockUrlReadRepository)(nil).FetchByOriginalUrl), ctx, originalUrl)
}

// FetchByShortCode mocks base method.
func (m *MockUrlReadRepository) FetchByShortCode(ctx context.Context, shortCode string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByShortCode", ctx, shortCode)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByShortCode indicates an expected call of FetchByShortCode.
func (mr *MockUrlReadRepositoryMockRecorder) FetchByShortCode(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByShortCode", reflect.TypeOf((*MockUrlReadRepository)(nil).FetchByShortCode), ctx, shortCode)
}

// FetchByStatus mocks base method.
func (m *MockUrlReadRepository) FetchByStatus(ctx context.Context, status url.URLStatus) (repository.FetchRecordsResponse[url.URL], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByStatus", ctx, status)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[url.URL])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByStatus indicates an expected call of FetchByStatus.
func (mr *MockUrlReadRepositoryMockRecorder) FetchByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByStatus", reflect.TypeOf((*MockUrlReadRepository)(nil).FetchByStatus), ctx, status)
}

// FetchByUserId mocks base method.
func (m *MockUrlReadRepository) FetchByUserId(ctx context.Context, userId string) (repository.FetchRecordsResponse[url.URL], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUserId", ctx, userId)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[url.URL])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUserId indicates an expected call of FetchByUserId.
func (mr *MockUrlReadRepositoryMockRecorder) FetchByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUserId", reflect.TypeOf((*MockUrlReadRepository)(nil).FetchByUserId), ctx, userId)
}
