// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/domain/url/datastore.go
//
// Generated by this command:
//
//	mockgen -destination=app/internal/domain/url/mocks/mock_url_datastore.go -package=urlmock -source=app/internal/domain/url/datastore.go
//

// Package urlmock is a generated GoMock package.
package urlmock

import (
	context "context"
	reflect "reflect"
	time "time"

	repository "github.com/sanctumlabs/fupi/app/internal/core/ports/repository"
	url "github.com/sanctumlabs/fupi/app/internal/domain/url"
	common "github.com/sanctumlabs/fupi/app/internal/pkg/common"
	gomock "go.uber.org/mock/gomock"
)

// MockUrlDatastore is a mock of UrlDatastore interface.
type MockUrlDatastore struct {
	ctrl     *gomock.Controller
	recorder *MockUrlDatastoreMockRecorder
	isgomock struct{}
}

// MockUrlDatastoreMockRecorder is the mock recorder for MockUrlDatastore.
type MockUrlDatastoreMockRecorder struct {
	mock *MockUrlDatastore
}

// NewMockUrlDatastore creates a new mock instance.
func NewMockUrlDatastore(ctrl *gomock.Controller) *MockUrlDatastore {
	mock := &MockUrlDatastore{ctrl: ctrl}
	mock.recorder = &MockUrlDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlDatastore) EXPECT() *MockUrlDatastoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUrlDatastore) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUrlDatastoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUrlDatastore)(nil).Delete), ctx, id)
}

// FetchAll mocks base method.
func (m *MockUrlDatastore) FetchAll(ctx context.Context, params common.RequestParams) (repository.FetchRecordsResponse[url.URL], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, params)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[url.URL])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUrlDatastoreMockRecorder) FetchAll(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUrlDatastore)(nil).FetchAll), ctx, params)
}

// FetchByCustomAlias mocks base method.
func (m *MockUrlDatastore) FetchByCustomAlias(ctx context.Context, customAlias string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByCustomAlias", ctx, customAlias)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByCustomAlias indicates an expected call of FetchByCustomAlias.
func (mr *MockUrlDatastoreMockRecorder) FetchByCustomAlias(ctx, customAlias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByCustomAlias", reflect.TypeOf((*MockUrlDatastore)(nil).FetchByCustomAlias), ctx, customAlias)
}

// FetchById mocks base method.
func (m *MockUrlDatastore) FetchById(ctx context.Context, id string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchById", ctx, id)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchById indicates an expected call of FetchById.
func (mr *MockUrlDatastoreMockRecorder) FetchById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchById", reflect.TypeOf((*MockUrlDatastore)(nil).FetchById), ctx, id)
}

// FetchByOriginalUrl mocks base method.
func (m *MockUrlDatastore) FetchByOriginalUrl(ctx context.Context, originalUrl string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByOriginalUrl", ctx, originalUrl)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByOriginalUrl indicates an expected call of FetchByOriginalUrl.
func (mr *MockUrlDatastoreMockRecorder) FetchByOriginalUrl(ctx, originalUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByOriginalUrl", reflect.TypeOf((*MockUrlDatastore)(nil).FetchByOriginalUrl), ctx, originalUrl)
}

// FetchByShortCode mocks base method.
func (m *MockUrlDatastore) FetchByShortCode(ctx context.Context, shortCode string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByShortCode", ctx, shortCode)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByShortCode indicates an expected call of FetchByShortCode.
func (mr *MockUrlDatastoreMockRecorder) FetchByShortCode(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByShortCode", reflect.TypeOf((*MockUrlDatastore)(nil).FetchByShortCode), ctx, shortCode)
}

// FetchByStatus mocks base method.
func (m *MockUrlDatastore) FetchByStatus(ctx context.Context, status url.URLStatus) (repository.FetchRecordsResponse[url.URL], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByStatus", ctx, status)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[url.URL])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByStatus indicates an expected call of FetchByStatus.
func (mr *MockUrlDatastoreMockRecorder) FetchByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByStatus", reflect.TypeOf((*MockUrlDatastore)(nil).FetchByStatus), ctx, status)
}

// FetchByUserId mocks base method.
func (m *MockUrlDatastore) FetchByUserId(ctx context.Context, userId string) (repository.FetchRecordsResponse[url.URL], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUserId", ctx, userId)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[url.URL])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUserId indicates an expected call of FetchByUserId.
func (mr *MockUrlDatastoreMockRecorder) FetchByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUserId", reflect.TypeOf((*MockUrlDatastore)(nil).FetchByUserId), ctx, userId)
}

// FetchExpiredActive mocks base method.
func (m *MockUrlDatastore) FetchExpiredActive(ctx context.Context, before time.Time, limit int) ([]url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchExpiredActive", ctx, before, limit)
	ret0, _ := ret[0].([]url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchExpiredActive indicates an expected call of FetchExpiredActive.
func (mr *MockUrlDatastoreMockRecorder) FetchExpiredActive(ctx, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchExpiredActive", reflect.TypeOf((*MockUrlDatastore)(nil).FetchExpiredActive), ctx, before, limit)
}

// Save mocks base method.
func (m *MockUrlDatastore) Save(ctx context.Context, request url.URL) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, request)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockUrlDatastoreMockRecorder) Save(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUrlDatastore)(nil).Save), ctx, request)
}

// SoftDelete mocks base method.
func (m *MockUrlDatastore) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUrlDatastoreMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUrlDatastore)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockUrlDatastore) Update(ctx context.Context, request url.URL) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUrlDatastoreMockRecorder) Update(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUrlDatastore)(nil).Update), ctx, request)
}

// MockUrlWriteDatastore is a mock of UrlWriteDatastore interface.
type MockUrlWriteDatastore struct {
	ctrl     *gomock.Controller
	recorder *MockUrlWriteDatastoreMockRecorder
	isgomock struct{}
}

// MockUrlWriteDatastoreMockRecorder is the mock recorder for MockUrlWriteDatastore.
type MockUrlWriteDatastoreMockRecorder struct {
	mock *MockUrlWriteDatastore
}

// NewMockUrlWriteDatastore creates a new mock instance.
func NewMockUrlWriteDatastore(ctrl *gomock.Controller) *MockUrlWriteDatastore {
	mock := &MockUrlWriteDatastore{ctrl: ctrl}
	mock.recorder = &MockUrlWriteDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlWriteDatastore) EXPECT() *MockUrlWriteDatastoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUrlWriteDatastore) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUrlWriteDatastoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUrlWriteDatastore)(nil).Delete), ctx, id)
}

// Save mocks base method.
func (m *MockUrlWriteDatastore) Save(ctx context.Context, request url.URL) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, request)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockUrlWriteDatastoreMockRecorder) Save(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUrlWriteDatastore)(nil).Save), ctx, request)
}

// SoftDelete mocks base method.
func (m *MockUrlWriteDatastore) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUrlWriteDatastoreMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUrlWriteDatastore)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockUrlWriteDatastore) Update(ctx context.Context, request url.URL) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUrlWriteDatastoreMockRecorder) Update(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUrlWriteDatastore)(nil).Update), ctx, request)
}

// MockUrlReadDatastore is a mock of UrlReadDatastore interface.
type MockUrlReadDatastore struct {
	ctrl     *gomock.Controller
	recorder *MockUrlReadDatastoreMockRecorder
	isgomock struct{}
}

// MockUrlReadDatastoreMockRecorder is the mock recorder for MockUrlReadDatastore.
type MockUrlReadDatastoreMockRecorder struct {
	mock *MockUrlReadDatastore
}

// NewMockUrlReadDatastore creates a new mock instance.
func NewMockUrlReadDatastore(ctrl *gomock.Controller) *MockUrlReadDatastore {
	mock := &MockUrlReadDatastore{ctrl: ctrl}
	mock.recorder = &MockUrlReadDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlReadDatastore) EXPECT() *MockUrlReadDatastoreMockRecorder {
	return m.recorder
}

// FetchAll mocks base method.
func (m *MockUrlReadDatastore) FetchAll(ctx context.Context, params common.RequestParams) (repository.FetchRecordsResponse[url.URL], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, params)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[url.URL])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUrlReadDatastoreMockRecorder) FetchAll(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUrlReadDatastore)(nil).FetchAll), ctx, params)
}

// FetchByCustomAlias mocks base method.
func (m *MockUrlReadDatastore) FetchByCustomAlias(ctx context.Context, customAlias string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByCustomAlias", ctx, customAlias)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByCustomAlias indicates an expected call of FetchByCustomAlias.
func (mr *MockUrlReadDatastoreMockRecorder) FetchByCustomAlias(ctx, customAlias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByCustomAlias", reflect.TypeOf((*MockUrlReadDatastore)(nil).FetchByCustomAlias), ctx, customAlias)
}

// FetchById mocks base method.
func (m *MockUrlReadDatastore) FetchById(ctx context.Context, id string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchById", ctx, id)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchById indicates an expected call of FetchById.
func (mr *MockUrlReadDatastoreMockRecorder) FetchById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchById", reflect.TypeOf((*MockUrlReadDatastore)(nil).FetchById), ctx, id)
}

// FetchByOriginalUrl mocks base method.
func (m *MockUrlReadDatastore) FetchByOriginalUrl(ctx context.Context, originalUrl string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByOriginalUrl", ctx, originalUrl)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByOriginalUrl indicates an expected call of FetchByOriginalUrl.
func (mr *MockUrlReadDatastoreMockRecorder) FetchByOriginalUrl(ctx, originalUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByOriginalUrl", reflect.TypeOf((*MockUrlReadDatastore)(nil).FetchByOriginalUrl), ctx, originalUrl)
}

// FetchByShortCode mocks base method.
func (m *MockUrlReadDatastore) FetchByShortCode(ctx context.Context, shortCode string) (url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByShortCode", ctx, shortCode)
	ret0, _ := ret[0].(url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByShortCode indicates an expected call of FetchByShortCode.
func (mr *MockUrlReadDatastoreMockRecorder) FetchByShortCode(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByShortCode", reflect.TypeOf((*MockUrlReadDatastore)(nil).FetchByShortCode), ctx, shortCode)
}

// FetchByStatus mocks base method.
func (m *MockUrlReadDatastore) FetchByStatus(ctx context.Context, status url.URLStatus) (repository.FetchRecordsResponse[url.URL], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByStatus", ctx, status)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[url.URL])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByStatus indicates an expected call of FetchByStatus.
func (mr *MockUrlReadDatastoreMockRecorder) FetchByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByStatus", reflect.TypeOf((*MockUrlReadDatastore)(nil).FetchByStatus), ctx, status)
}

// FetchByUserId mocks base method.
func (m *MockUrlReadDatastore) FetchByUserId(ctx context.Context, userId string) (repository.FetchRecordsResponse[url.URL], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUserId", ctx, userId)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[url.URL])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUserId indicates an expected call of FetchByUserId.
func (mr *MockUrlReadDatastoreMockRecorder) FetchByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUserId", reflect.TypeOf((*MockUrlReadDatastore)(nil).FetchByUserId), ctx, userId)
}

// FetchExpiredActive mocks base method.
func (m *MockUrlReadDatastore) FetchExpiredActive(ctx context.Context, before time.Time, limit int) ([]url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchExpiredActive", ctx, before, limit)
	ret0, _ := ret[0].([]url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchExpiredActive indicates an expected call of FetchExpiredActive.
func (mr *MockUrlReadDatastoreMockRecorder) FetchExpiredActive(ctx, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchExpiredActive", reflect.TypeOf((*MockUrlReadDatastore)(nil).FetchExpiredActive), ctx, before, limit)
}
