// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/adapters/postgres/url/url_repo_querier.go
//
// Generated by this command:
//
//	mockgen -destination=app/internal/adapters/postgres/url/mocks/mock_url_repo_querier.go -package=mockurlrepo -source=app/internal/adapters/postgres/url/url_repo_querier.go
//

// Package mockurlrepo is a generated GoMock package.
package mockurlrepo

import (
	context "context"
	reflect "reflect"

	postgresql "github.com/sanctumlabs/curtz/app/internal/adapters/postgres/sql"
	gomock "go.uber.org/mock/gomock"
)

// MockUrlWriteQuerier is a mock of UrlWriteQuerier interface.
type MockUrlWriteQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockUrlWriteQuerierMockRecorder
	isgomock struct{}
}

// MockUrlWriteQuerierMockRecorder is the mock recorder for MockUrlWriteQuerier.
type MockUrlWriteQuerierMockRecorder struct {
	mock *MockUrlWriteQuerier
}

// NewMockUrlWriteQuerier creates a new mock instance.
func NewMockUrlWriteQuerier(ctrl *gomock.Controller) *MockUrlWriteQuerier {
	mock := &MockUrlWriteQuerier{ctrl: ctrl}
	mock.recorder = &MockUrlWriteQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlWriteQuerier) EXPECT() *MockUrlWriteQuerierMockRecorder {
	return m.recorder
}

// QueryCreateKeyword mocks base method.
func (m *MockUrlWriteQuerier) QueryCreateKeyword(ctx context.Context, params postgresql.QueryCreateKeywordParams) (postgresql.Keyword, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryCreateKeyword", ctx, params)
	ret0, _ := ret[0].(postgresql.Keyword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryCreateKeyword indicates an expected call of QueryCreateKeyword.
func (mr *MockUrlWriteQuerierMockRecorder) QueryCreateKeyword(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCreateKeyword", reflect.TypeOf((*MockUrlWriteQuerier)(nil).QueryCreateKeyword), ctx, params)
}

// QueryCreateUrl mocks base method.
func (m *MockUrlWriteQuerier) QueryCreateUrl(ctx context.Context, params postgresql.QueryCreateUrlParams) (postgresql.Url, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryCreateUrl", ctx, params)
	ret0, _ := ret[0].(postgresql.Url)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryCreateUrl indicates an expected call of QueryCreateUrl.
func (mr *MockUrlWriteQuerierMockRecorder) QueryCreateUrl(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCreateUrl", reflect.TypeOf((*MockUrlWriteQuerier)(nil).QueryCreateUrl), ctx, params)
}

// QueryUrlStatusByName mocks base method.
func (m *MockUrlWriteQuerier) QueryUrlStatusByName(ctx context.Context, name string) (postgresql.UrlStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryUrlStatusByName", ctx, name)
	ret0, _ := ret[0].(postgresql.UrlStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryUrlStatusByName indicates an expected call of QueryUrlStatusByName.
func (mr *MockUrlWriteQuerierMockRecorder) QueryUrlStatusByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryUrlStatusByName", reflect.TypeOf((*MockUrlWriteQuerier)(nil).QueryUrlStatusByName), ctx, name)
}
