package postgresrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	postgresql "github.com/sanctumlabs/curtz/app/internal/adapters/postgres/sql"
)

type (
	// UrlWriteQuerier defines the subset of SQL operations needed for URL writes.
	// Using an interface here lets tests inject a mock instead of a real DB connection.
	// The concrete *postgresql.Queries type (generated by sqlc) satisfies this interface.
	UrlWriteQuerier interface {
		QueryCreateUrl(ctx context.Context, params postgresql.QueryCreateUrlParams) (postgresql.Url, error)
		QueryCreateKeyword(ctx context.Context, params postgresql.QueryCreateKeywordParams) (postgresql.Keyword, error)
	}

	// UrlReadQuerier defines the subset of SQL operations needed for URL reads.
	// Using an interface here lets tests inject a mock instead of a real DB connection.
	// The concrete *postgresql.Queries type (generated by sqlc) satisfies this interface.
	UrlReadQuerier interface {
		QueryUrlById(ctx context.Context, id pgtype.UUID) (postgresql.QueryUrlByIdRow, error)
		QueryUrlByUrlShortCode(ctx context.Context, shortCode string) (postgresql.QueryUrlByUrlShortCodeRow, error)
		QueryUrlByCustomAlias(ctx context.Context, customAlias pgtype.Text) (postgresql.QueryUrlByCustomAliasRow, error)
		QueryUrlByOriginalUrl(ctx context.Context, originalUrl string) (postgresql.QueryUrlByOriginalUrlRow, error)
		QueryAllUrls(ctx context.Context, arg postgresql.QueryAllUrlsParams) ([]postgresql.QueryAllUrlsRow, error)
		QueryAllUrlsByUserId(ctx context.Context, arg postgresql.QueryAllUrlsByUserIdParams) ([]postgresql.QueryAllUrlsByUserIdRow, error)
		QueryExpiredActiveUrls(ctx context.Context, arg postgresql.QueryExpiredActiveUrlsParams) ([]postgresql.QueryExpiredActiveUrlsRow, error)
	}

	// UserReadQuerier defines the subset of SQL operations needed for User reads.
	// Using an interface here lets tests inject a mock instead of a real DB connection.
	// The concrete *postgresql.Queries type (generated by sqlc) satisfies this interface.
	UserReadQuerier interface {
		QueryUserById(ctx context.Context, id pgtype.UUID) (postgresql.QueryUserByIdRow, error)
		QueryUserByUsername(ctx context.Context, username string) (postgresql.QueryUserByUsernameRow, error)
		QueryUserByEmail(ctx context.Context, email string) (postgresql.QueryUserByEmailRow, error)
		QueryUserByVerificationToken(ctx context.Context, verificationToken pgtype.Text) (postgresql.QueryUserByVerificationTokenRow, error)
		QueryAllUsers(ctx context.Context, arg postgresql.QueryAllUsersParams) ([]postgresql.QueryAllUsersRow, error)
	}

	// UserWriteQuerier defines the subset of SQL operations needed for User writes.
	// Using an interface here lets tests inject a mock instead of a real DB connection.
	// The concrete *postgresql.Queries type (generated by sqlc) satisfies this interface.
	UserWriteQuerier interface {
		UserReadQuerier
		OutboxWriteQuerier
		QueryCreateUser(ctx context.Context, params postgresql.QueryCreateUserParams) (postgresql.User, error)
		QueryDeleteUserWithId(ctx context.Context, id pgtype.UUID) (postgresql.User, error)
		QuerySoftDeleteUser(ctx context.Context, params postgresql.QuerySoftDeleteUserParams) (postgresql.User, error)
		QueryUpdateUserDetails(ctx context.Context, params postgresql.QueryUpdateUserDetailsParams) (postgresql.User, error)
		QueryUpdateUserMetadata(ctx context.Context, params postgresql.QueryUpdateUserMetadataParams) (postgresql.User, error)
		QueryUpdateUserPassword(ctx context.Context, params postgresql.QueryUpdateUserPasswordParams) (postgresql.User, error)
		QueryUpdateUserStatus(ctx context.Context, params postgresql.QueryUpdateUserStatusParams) (postgresql.User, error)
		QueryUpdateUserVerification(ctx context.Context, params postgresql.QueryUpdateUserVerificationParams) (postgresql.User, error)
	}
)
