package postgresrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	postgresql "github.com/sanctumlabs/curtz/app/internal/adapters/postgres/sql"
)

type (
	// UrlWriteQuerier defines the subset of SQL operations needed for URL writes.
	// Using an interface here lets tests inject a mock instead of a real DB connection.
	// The concrete *postgresql.Queries type (generated by sqlc) satisfies this interface.
	UrlWriteQuerier interface {
		QueryUrlStatusByName(ctx context.Context, name string) (postgresql.UrlStatus, error)
		QueryCreateUrl(ctx context.Context, params postgresql.QueryCreateUrlParams) (postgresql.Url, error)
		QueryCreateKeyword(ctx context.Context, params postgresql.QueryCreateKeywordParams) (postgresql.Keyword, error)
	}

	// UserReadQuerier defines the subset of SQL operations needed for User reads.
	// Using an interface here lets tests inject a mock instead of a real DB connection.
	// The concrete *postgresql.Queries type (generated by sqlc) satisfies this interface.
	UserReadQuerier interface {
		QueryUserById(ctx context.Context, id pgtype.UUID) (postgresql.QueryUserByIdRow, error)
		QueryUserByUsername(ctx context.Context, username string) (postgresql.QueryUserByUsernameRow, error)
		QueryUserByEmail(ctx context.Context, email string) (postgresql.QueryUserByEmailRow, error)
		QueryAllUsers(ctx context.Context, arg postgresql.QueryAllUsersParams) ([]postgresql.QueryAllUsersRow, error)
	}
)
