// Code generated by MockGen. DO NOT EDIT.
// Source: app/pkg/infra/database/dbclient.go
//
// Generated by this command:
//
//	mockgen -destination=app/pkg/infra/database/mocks/dbclient_mock.go -package=mockdatabase -source=app/pkg/infra/database/dbclient.go
//

// Package mockdatabase is a generated GoMock package.
package mockdatabase

import (
	context "context"
	reflect "reflect"
	time "time"

	pgxpool "github.com/jackc/pgx/v5/pgxpool"
	database "github.com/sanctumlabs/curtz/app/pkg/infra/database"
	gomock "go.uber.org/mock/gomock"
)

// MockPostgresDatabaseClient is a mock of PostgresDatabaseClient interface.
type MockPostgresDatabaseClient struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresDatabaseClientMockRecorder
	isgomock struct{}
}

// MockPostgresDatabaseClientMockRecorder is the mock recorder for MockPostgresDatabaseClient.
type MockPostgresDatabaseClientMockRecorder struct {
	mock *MockPostgresDatabaseClient
}

// NewMockPostgresDatabaseClient creates a new mock instance.
func NewMockPostgresDatabaseClient(ctrl *gomock.Controller) *MockPostgresDatabaseClient {
	mock := &MockPostgresDatabaseClient{ctrl: ctrl}
	mock.recorder = &MockPostgresDatabaseClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresDatabaseClient) EXPECT() *MockPostgresDatabaseClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPostgresDatabaseClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockPostgresDatabaseClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPostgresDatabaseClient)(nil).Close))
}

// Configure mocks base method.
func (m *MockPostgresDatabaseClient) Configure(arg0 ...database.PostgresqlDbOption) database.PostgresDatabaseClient {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Configure", varargs...)
	ret0, _ := ret[0].(database.PostgresDatabaseClient)
	return ret0
}

// Configure indicates an expected call of Configure.
func (mr *MockPostgresDatabaseClientMockRecorder) Configure(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configure", reflect.TypeOf((*MockPostgresDatabaseClient)(nil).Configure), arg0...)
}

// GetDB mocks base method.
func (m *MockPostgresDatabaseClient) GetDB() *pgxpool.Pool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*pgxpool.Pool)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockPostgresDatabaseClientMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockPostgresDatabaseClient)(nil).GetDB))
}

// GetDBWithTimeout mocks base method.
func (m *MockPostgresDatabaseClient) GetDBWithTimeout(ctx context.Context, operationType string) (*pgxpool.Pool, context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBWithTimeout", ctx, operationType)
	ret0, _ := ret[0].(*pgxpool.Pool)
	ret1, _ := ret[1].(context.Context)
	ret2, _ := ret[2].(context.CancelFunc)
	return ret0, ret1, ret2
}

// GetDBWithTimeout indicates an expected call of GetDBWithTimeout.
func (mr *MockPostgresDatabaseClientMockRecorder) GetDBWithTimeout(ctx, operationType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBWithTimeout", reflect.TypeOf((*MockPostgresDatabaseClient)(nil).GetDBWithTimeout), ctx, operationType)
}

// HealthCheck mocks base method.
func (m *MockPostgresDatabaseClient) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockPostgresDatabaseClientMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockPostgresDatabaseClient)(nil).HealthCheck), ctx)
}

// WithConnAttempts mocks base method.
func (m *MockPostgresDatabaseClient) WithConnAttempts(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithConnAttempts", arg0)
}

// WithConnAttempts indicates an expected call of WithConnAttempts.
func (mr *MockPostgresDatabaseClientMockRecorder) WithConnAttempts(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithConnAttempts", reflect.TypeOf((*MockPostgresDatabaseClient)(nil).WithConnAttempts), arg0)
}

// WithConnTimeout mocks base method.
func (m *MockPostgresDatabaseClient) WithConnTimeout(arg0 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithConnTimeout", arg0)
}

// WithConnTimeout indicates an expected call of WithConnTimeout.
func (mr *MockPostgresDatabaseClientMockRecorder) WithConnTimeout(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithConnTimeout", reflect.TypeOf((*MockPostgresDatabaseClient)(nil).WithConnTimeout), arg0)
}
