// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/infra/queue/consumer.go
//
// Generated by this command:
//
//	mockgen -destination=pkg/infra/queue/mocks/consumer_mock.go -package=mockqueue -source=pkg/infra/queue/consumer.go
//

// Package mockqueue is a generated GoMock package.
package mockqueue

import (
	queue "carduka/bidsvc/pkg/infra/queue"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConsumer is a mock of Consumer interface.
type MockConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerMockRecorder
}

// MockConsumerMockRecorder is the mock recorder for MockConsumer.
type MockConsumerMockRecorder struct {
	mock *MockConsumer
}

// NewMockConsumer creates a new mock instance.
func NewMockConsumer(ctrl *gomock.Controller) *MockConsumer {
	mock := &MockConsumer{ctrl: ctrl}
	mock.recorder = &MockConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumer) EXPECT() *MockConsumerMockRecorder {
	return m.recorder
}

// AddHandler mocks base method.
func (m *MockConsumer) AddHandler(ctx context.Context, task string, handler func([]byte) error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHandler", ctx, task, handler)
}

// AddHandler indicates an expected call of AddHandler.
func (mr *MockConsumerMockRecorder) AddHandler(ctx, task, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHandler", reflect.TypeOf((*MockConsumer)(nil).AddHandler), ctx, task, handler)
}

// Consume mocks base method.
func (m *MockConsumer) Consume(ctx context.Context, queue string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, queue)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockConsumerMockRecorder) Consume(ctx, queue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockConsumer)(nil).Consume), ctx, queue)
}

// MockEventConsumer is a mock of EventConsumer interface.
type MockEventConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockEventConsumerMockRecorder
}

// MockEventConsumerMockRecorder is the mock recorder for MockEventConsumer.
type MockEventConsumerMockRecorder struct {
	mock *MockEventConsumer
}

// NewMockEventConsumer creates a new mock instance.
func NewMockEventConsumer(ctrl *gomock.Controller) *MockEventConsumer {
	mock := &MockEventConsumer{ctrl: ctrl}
	mock.recorder = &MockEventConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventConsumer) EXPECT() *MockEventConsumerMockRecorder {
	return m.recorder
}

// StartConsumer mocks base method.
func (m *MockEventConsumer) StartConsumer(fn queue.EventWorker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartConsumer", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartConsumer indicates an expected call of StartConsumer.
func (mr *MockEventConsumerMockRecorder) StartConsumer(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartConsumer", reflect.TypeOf((*MockEventConsumer)(nil).StartConsumer), fn)
}

// MockMessageConsumer is a mock of MessageConsumer interface.
type MockMessageConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockMessageConsumerMockRecorder
}

// MockMessageConsumerMockRecorder is the mock recorder for MockMessageConsumer.
type MockMessageConsumerMockRecorder struct {
	mock *MockMessageConsumer
}

// NewMockMessageConsumer creates a new mock instance.
func NewMockMessageConsumer(ctrl *gomock.Controller) *MockMessageConsumer {
	mock := &MockMessageConsumer{ctrl: ctrl}
	mock.recorder = &MockMessageConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageConsumer) EXPECT() *MockMessageConsumerMockRecorder {
	return m.recorder
}

// StartConsumer mocks base method.
func (m *MockMessageConsumer) StartConsumer(fn queue.MessageWorker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartConsumer", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartConsumer indicates an expected call of StartConsumer.
func (mr *MockMessageConsumerMockRecorder) StartConsumer(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartConsumer", reflect.TypeOf((*MockMessageConsumer)(nil).StartConsumer), fn)
}
