// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: apikeys_write_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryCreateApiKey = `-- name: QueryCreateApiKey :one
INSERT INTO api_keys (user_id, key_hash, name, scopes, rate_limit, expires_at) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, key_hash, name, scopes, rate_limit, last_used_at, expires_at, created_at, updated_at, deleted_at
`

type QueryCreateApiKeyParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	KeyHash   string             `db:"key_hash" json:"key_hash"`
	Name      string             `db:"name" json:"name"`
	Scopes    []string           `db:"scopes" json:"scopes"`
	RateLimit int32              `db:"rate_limit" json:"rate_limit"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// QueryCreateApiKey
//
//	INSERT INTO api_keys (user_id, key_hash, name, scopes, rate_limit, expires_at) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, key_hash, name, scopes, rate_limit, last_used_at, expires_at, created_at, updated_at, deleted_at
func (q *Queries) QueryCreateApiKey(ctx context.Context, arg QueryCreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, queryCreateApiKey,
		arg.UserID,
		arg.KeyHash,
		arg.Name,
		arg.Scopes,
		arg.RateLimit,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Name,
		&i.Scopes,
		&i.RateLimit,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryDeleteApiKeyWithId = `-- name: QueryDeleteApiKeyWithId :one
DELETE FROM api_keys WHERE id = $1 RETURNING id, user_id, key_hash, name, scopes, rate_limit, last_used_at, expires_at, created_at, updated_at, deleted_at
`

// QueryDeleteApiKeyWithId
//
//	DELETE FROM api_keys WHERE id = $1 RETURNING id, user_id, key_hash, name, scopes, rate_limit, last_used_at, expires_at, created_at, updated_at, deleted_at
func (q *Queries) QueryDeleteApiKeyWithId(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, queryDeleteApiKeyWithId, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Name,
		&i.Scopes,
		&i.RateLimit,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const querySoftDeleteApiKey = `-- name: QuerySoftDeleteApiKey :one
UPDATE api_keys
SET
  deleted_at = $2
WHERE id = $1 RETURNING id, user_id, key_hash, name, scopes, rate_limit, last_used_at, expires_at, created_at, updated_at, deleted_at
`

type QuerySoftDeleteApiKeyParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// QuerySoftDeleteApiKey
//
//	UPDATE api_keys
//	SET
//	  deleted_at = $2
//	WHERE id = $1 RETURNING id, user_id, key_hash, name, scopes, rate_limit, last_used_at, expires_at, created_at, updated_at, deleted_at
func (q *Queries) QuerySoftDeleteApiKey(ctx context.Context, arg QuerySoftDeleteApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, querySoftDeleteApiKey, arg.ID, arg.DeletedAt)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Name,
		&i.Scopes,
		&i.RateLimit,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateApiKey = `-- name: QueryUpdateApiKey :one
UPDATE api_keys ak
SET
  last_used_at=$2,
  expires_at=$3
WHERE ak.id = $1 RETURNING id, user_id, key_hash, name, scopes, rate_limit, last_used_at, expires_at, created_at, updated_at, deleted_at
`

type QueryUpdateApiKeyParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// QueryUpdateApiKey
//
//	UPDATE api_keys ak
//	SET
//	  last_used_at=$2,
//	  expires_at=$3
//	WHERE ak.id = $1 RETURNING id, user_id, key_hash, name, scopes, rate_limit, last_used_at, expires_at, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateApiKey(ctx context.Context, arg QueryUpdateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, queryUpdateApiKey, arg.ID, arg.LastUsedAt, arg.ExpiresAt)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Name,
		&i.Scopes,
		&i.RateLimit,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateApiKeyLastUsed = `-- name: QueryUpdateApiKeyLastUsed :one
UPDATE api_keys ak
SET
  last_used_at=$2
WHERE ak.id = $1 RETURNING id, user_id, key_hash, name, scopes, rate_limit, last_used_at, expires_at, created_at, updated_at, deleted_at
`

type QueryUpdateApiKeyLastUsedParams struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
}

// QueryUpdateApiKeyLastUsed
//
//	UPDATE api_keys ak
//	SET
//	  last_used_at=$2
//	WHERE ak.id = $1 RETURNING id, user_id, key_hash, name, scopes, rate_limit, last_used_at, expires_at, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateApiKeyLastUsed(ctx context.Context, arg QueryUpdateApiKeyLastUsedParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, queryUpdateApiKeyLastUsed, arg.ID, arg.LastUsedAt)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.Name,
		&i.Scopes,
		&i.RateLimit,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
