// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: apikeys_read_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryAllApiKeys = `-- name: QueryAllApiKeys :many
SELECT
  ak.id, ak.user_id, ak.key_hash, ak.name, ak.scopes, ak.rate_limit, ak.last_used_at, ak.expires_at, ak.created_at, ak.updated_at, ak.deleted_at,
  COUNT(*) OVER() AS total_records
FROM api_keys ak
WHERE CASE 
  WHEN $1::bool=true THEN ak.deleted_at IS NULL OR ak.deleted_at IS NOT NULL
  WHEN $1::bool=false THEN ak.deleted_at IS NULL
  ELSE ak.deleted_at IS NULL
END
ORDER BY ak.created_at DESC
LIMIT $3
OFFSET $2
`

type QueryAllApiKeysParams struct {
	IncludeDeleted bool  `db:"include_deleted" json:"include_deleted"`
	CurrentOffset  int32 `db:"current_offset" json:"current_offset"`
	LimitBy        int32 `db:"limit_by" json:"limit_by"`
}

type QueryAllApiKeysRow struct {
	ApiKey       ApiKey `db:"api_key" json:"api_key"`
	TotalRecords int64  `db:"total_records" json:"total_records"`
}

// QueryAllApiKeys
//
//	SELECT
//	  ak.id, ak.user_id, ak.key_hash, ak.name, ak.scopes, ak.rate_limit, ak.last_used_at, ak.expires_at, ak.created_at, ak.updated_at, ak.deleted_at,
//	  COUNT(*) OVER() AS total_records
//	FROM api_keys ak
//	WHERE CASE
//	  WHEN $1::bool=true THEN ak.deleted_at IS NULL OR ak.deleted_at IS NOT NULL
//	  WHEN $1::bool=false THEN ak.deleted_at IS NULL
//	  ELSE ak.deleted_at IS NULL
//	END
//	ORDER BY ak.created_at DESC
//	LIMIT $3
//	OFFSET $2
func (q *Queries) QueryAllApiKeys(ctx context.Context, arg QueryAllApiKeysParams) ([]QueryAllApiKeysRow, error) {
	rows, err := q.db.Query(ctx, queryAllApiKeys, arg.IncludeDeleted, arg.CurrentOffset, arg.LimitBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllApiKeysRow
	for rows.Next() {
		var i QueryAllApiKeysRow
		if err := rows.Scan(
			&i.ApiKey.ID,
			&i.ApiKey.UserID,
			&i.ApiKey.KeyHash,
			&i.ApiKey.Name,
			&i.ApiKey.Scopes,
			&i.ApiKey.RateLimit,
			&i.ApiKey.LastUsedAt,
			&i.ApiKey.ExpiresAt,
			&i.ApiKey.CreatedAt,
			&i.ApiKey.UpdatedAt,
			&i.ApiKey.DeletedAt,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryApiKeyById = `-- name: QueryApiKeyById :one
SELECT
  ak.id, ak.user_id, ak.key_hash, ak.name, ak.scopes, ak.rate_limit, ak.last_used_at, ak.expires_at, ak.created_at, ak.updated_at, ak.deleted_at
FROM api_keys ak
WHERE ak.id = $1
`

type QueryApiKeyByIdRow struct {
	ApiKey ApiKey `db:"api_key" json:"api_key"`
}

// QueryApiKeyById
//
//	SELECT
//	  ak.id, ak.user_id, ak.key_hash, ak.name, ak.scopes, ak.rate_limit, ak.last_used_at, ak.expires_at, ak.created_at, ak.updated_at, ak.deleted_at
//	FROM api_keys ak
//	WHERE ak.id = $1
func (q *Queries) QueryApiKeyById(ctx context.Context, id pgtype.UUID) (QueryApiKeyByIdRow, error) {
	row := q.db.QueryRow(ctx, queryApiKeyById, id)
	var i QueryApiKeyByIdRow
	err := row.Scan(
		&i.ApiKey.ID,
		&i.ApiKey.UserID,
		&i.ApiKey.KeyHash,
		&i.ApiKey.Name,
		&i.ApiKey.Scopes,
		&i.ApiKey.RateLimit,
		&i.ApiKey.LastUsedAt,
		&i.ApiKey.ExpiresAt,
		&i.ApiKey.CreatedAt,
		&i.ApiKey.UpdatedAt,
		&i.ApiKey.DeletedAt,
	)
	return i, err
}

const queryApiKeysByUser = `-- name: QueryApiKeysByUser :many
SELECT
  ak.id, ak.user_id, ak.key_hash, ak.name, ak.scopes, ak.rate_limit, ak.last_used_at, ak.expires_at, ak.created_at, ak.updated_at, ak.deleted_at,
  COUNT(*) OVER() AS total_records
FROM api_keys ak
WHERE $2::bool OR ak.deleted_at IS NULL
AND ak.user_id = $1
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN ak.created_at
      WHEN $3::text = 'updated_at' THEN ak.updated_at
      WHEN $3::text = 'deleted_at' THEN ak.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  -- Sort by 'created_at'
  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC' 
    THEN ak.created_at END ASC,
  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC' 
    THEN ak.created_at END DESC,
  
  -- Sort by 'updated_at'
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC' 
    THEN ak.updated_at END ASC,
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC' 
    THEN ak.updated_at END DESC,
  
  -- Sort by 'deleted_at'
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC' 
    THEN ak.deleted_at END ASC,
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC' 
    THEN ak.deleted_at END DESC
LIMIT $9
OFFSET $8
`

type QueryApiKeysByUserParams struct {
	UserID         pgtype.UUID      `db:"user_id" json:"user_id"`
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryApiKeysByUserRow struct {
	ApiKey       ApiKey `db:"api_key" json:"api_key"`
	TotalRecords int64  `db:"total_records" json:"total_records"`
}

// Date range filtering
//
//	SELECT
//	  ak.id, ak.user_id, ak.key_hash, ak.name, ak.scopes, ak.rate_limit, ak.last_used_at, ak.expires_at, ak.created_at, ak.updated_at, ak.deleted_at,
//	  COUNT(*) OVER() AS total_records
//	FROM api_keys ak
//	WHERE $2::bool OR ak.deleted_at IS NULL
//	AND ak.user_id = $1
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN ak.created_at
//	      WHEN $3::text = 'updated_at' THEN ak.updated_at
//	      WHEN $3::text = 'deleted_at' THEN ak.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  -- Sort by 'created_at'
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC'
//	    THEN ak.created_at END ASC,
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC'
//	    THEN ak.created_at END DESC,
//
//	  -- Sort by 'updated_at'
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC'
//	    THEN ak.updated_at END ASC,
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC'
//	    THEN ak.updated_at END DESC,
//
//	  -- Sort by 'deleted_at'
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC'
//	    THEN ak.deleted_at END ASC,
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC'
//	    THEN ak.deleted_at END DESC
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryApiKeysByUser(ctx context.Context, arg QueryApiKeysByUserParams) ([]QueryApiKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, queryApiKeysByUser,
		arg.UserID,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryApiKeysByUserRow
	for rows.Next() {
		var i QueryApiKeysByUserRow
		if err := rows.Scan(
			&i.ApiKey.ID,
			&i.ApiKey.UserID,
			&i.ApiKey.KeyHash,
			&i.ApiKey.Name,
			&i.ApiKey.Scopes,
			&i.ApiKey.RateLimit,
			&i.ApiKey.LastUsedAt,
			&i.ApiKey.ExpiresAt,
			&i.ApiKey.CreatedAt,
			&i.ApiKey.UpdatedAt,
			&i.ApiKey.DeletedAt,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryApiKeysByUserCount = `-- name: QueryApiKeysByUserCount :one
SELECT
  COUNT(*)
FROM api_keys ak
WHERE ak.user_id = $1
AND ($2::bool OR ak.deleted_at IS NULL)
`

type QueryApiKeysByUserCountParams struct {
	UserID         pgtype.UUID `db:"user_id" json:"user_id"`
	IncludeDeleted bool        `db:"include_deleted" json:"include_deleted"`
}

// QueryApiKeysByUserCount
//
//	SELECT
//	  COUNT(*)
//	FROM api_keys ak
//	WHERE ak.user_id = $1
//	AND ($2::bool OR ak.deleted_at IS NULL)
func (q *Queries) QueryApiKeysByUserCount(ctx context.Context, arg QueryApiKeysByUserCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, queryApiKeysByUserCount, arg.UserID, arg.IncludeDeleted)
	var count int64
	err := row.Scan(&count)
	return count, err
}
