// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: audit_trail_read_queries.sql

package postgresql

import (
	"context"
)

const queryAllAuditTrails = `-- name: QueryAllAuditTrails :many
SELECT
  t.id, t.schema_name, t.table_name, t.relid, t.session_user_name, t.action_tstamp_tx, t.action_tstamp_stm, t.action_tstamp_clk, t.transaction_id, t.application_name, t.client_addr, t.client_port, t.client_query, t.action, t.row_data, t.changed_fields, t.statement_only,
  COUNT(*) OVER() AS total_records
FROM audit_trail t
LIMIT $2
OFFSET $1
`

type QueryAllAuditTrailsParams struct {
	CurrentOffset int32 `db:"current_offset" json:"current_offset"`
	LimitBy       int32 `db:"limit_by" json:"limit_by"`
}

type QueryAllAuditTrailsRow struct {
	AuditTrail   AuditTrail `db:"audit_trail" json:"audit_trail"`
	TotalRecords int64      `db:"total_records" json:"total_records"`
}

// QueryAllAuditTrails
//
//	SELECT
//	  t.id, t.schema_name, t.table_name, t.relid, t.session_user_name, t.action_tstamp_tx, t.action_tstamp_stm, t.action_tstamp_clk, t.transaction_id, t.application_name, t.client_addr, t.client_port, t.client_query, t.action, t.row_data, t.changed_fields, t.statement_only,
//	  COUNT(*) OVER() AS total_records
//	FROM audit_trail t
//	LIMIT $2
//	OFFSET $1
func (q *Queries) QueryAllAuditTrails(ctx context.Context, arg QueryAllAuditTrailsParams) ([]QueryAllAuditTrailsRow, error) {
	rows, err := q.db.Query(ctx, queryAllAuditTrails, arg.CurrentOffset, arg.LimitBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllAuditTrailsRow
	for rows.Next() {
		var i QueryAllAuditTrailsRow
		if err := rows.Scan(
			&i.AuditTrail.ID,
			&i.AuditTrail.SchemaName,
			&i.AuditTrail.TableName,
			&i.AuditTrail.Relid,
			&i.AuditTrail.SessionUserName,
			&i.AuditTrail.ActionTstampTx,
			&i.AuditTrail.ActionTstampStm,
			&i.AuditTrail.ActionTstampClk,
			&i.AuditTrail.TransactionID,
			&i.AuditTrail.ApplicationName,
			&i.AuditTrail.ClientAddr,
			&i.AuditTrail.ClientPort,
			&i.AuditTrail.ClientQuery,
			&i.AuditTrail.Action,
			&i.AuditTrail.RowData,
			&i.AuditTrail.ChangedFields,
			&i.AuditTrail.StatementOnly,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAllAuditTrailsByAction = `-- name: QueryAllAuditTrailsByAction :many
SELECT 
  t.id, t.schema_name, t.table_name, t.relid, t.session_user_name, t.action_tstamp_tx, t.action_tstamp_stm, t.action_tstamp_clk, t.transaction_id, t.application_name, t.client_addr, t.client_port, t.client_query, t.action, t.row_data, t.changed_fields, t.statement_only,
  COUNT(*) OVER() AS total_records  
FROM audit_trail t
WHERE t.action = $1
LIMIT $3
OFFSET $2
`

type QueryAllAuditTrailsByActionParams struct {
	Action        string `db:"action" json:"action"`
	CurrentOffset int32  `db:"current_offset" json:"current_offset"`
	LimitBy       int32  `db:"limit_by" json:"limit_by"`
}

type QueryAllAuditTrailsByActionRow struct {
	AuditTrail   AuditTrail `db:"audit_trail" json:"audit_trail"`
	TotalRecords int64      `db:"total_records" json:"total_records"`
}

// QueryAllAuditTrailsByAction
//
//	SELECT
//	  t.id, t.schema_name, t.table_name, t.relid, t.session_user_name, t.action_tstamp_tx, t.action_tstamp_stm, t.action_tstamp_clk, t.transaction_id, t.application_name, t.client_addr, t.client_port, t.client_query, t.action, t.row_data, t.changed_fields, t.statement_only,
//	  COUNT(*) OVER() AS total_records
//	FROM audit_trail t
//	WHERE t.action = $1
//	LIMIT $3
//	OFFSET $2
func (q *Queries) QueryAllAuditTrailsByAction(ctx context.Context, arg QueryAllAuditTrailsByActionParams) ([]QueryAllAuditTrailsByActionRow, error) {
	rows, err := q.db.Query(ctx, queryAllAuditTrailsByAction, arg.Action, arg.CurrentOffset, arg.LimitBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllAuditTrailsByActionRow
	for rows.Next() {
		var i QueryAllAuditTrailsByActionRow
		if err := rows.Scan(
			&i.AuditTrail.ID,
			&i.AuditTrail.SchemaName,
			&i.AuditTrail.TableName,
			&i.AuditTrail.Relid,
			&i.AuditTrail.SessionUserName,
			&i.AuditTrail.ActionTstampTx,
			&i.AuditTrail.ActionTstampStm,
			&i.AuditTrail.ActionTstampClk,
			&i.AuditTrail.TransactionID,
			&i.AuditTrail.ApplicationName,
			&i.AuditTrail.ClientAddr,
			&i.AuditTrail.ClientPort,
			&i.AuditTrail.ClientQuery,
			&i.AuditTrail.Action,
			&i.AuditTrail.RowData,
			&i.AuditTrail.ChangedFields,
			&i.AuditTrail.StatementOnly,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAllAuditTrailsById = `-- name: QueryAllAuditTrailsById :many
SELECT 
  t.id, t.schema_name, t.table_name, t.relid, t.session_user_name, t.action_tstamp_tx, t.action_tstamp_stm, t.action_tstamp_clk, t.transaction_id, t.application_name, t.client_addr, t.client_port, t.client_query, t.action, t.row_data, t.changed_fields, t.statement_only,
  COUNT(*) OVER() AS total_records
FROM audit_trail t
WHERE t.id = $1
LIMIT $3
OFFSET $2
`

type QueryAllAuditTrailsByIdParams struct {
	ID            int64 `db:"id" json:"id"`
	CurrentOffset int32 `db:"current_offset" json:"current_offset"`
	LimitBy       int32 `db:"limit_by" json:"limit_by"`
}

type QueryAllAuditTrailsByIdRow struct {
	AuditTrail   AuditTrail `db:"audit_trail" json:"audit_trail"`
	TotalRecords int64      `db:"total_records" json:"total_records"`
}

// QueryAllAuditTrailsById
//
//	SELECT
//	  t.id, t.schema_name, t.table_name, t.relid, t.session_user_name, t.action_tstamp_tx, t.action_tstamp_stm, t.action_tstamp_clk, t.transaction_id, t.application_name, t.client_addr, t.client_port, t.client_query, t.action, t.row_data, t.changed_fields, t.statement_only,
//	  COUNT(*) OVER() AS total_records
//	FROM audit_trail t
//	WHERE t.id = $1
//	LIMIT $3
//	OFFSET $2
func (q *Queries) QueryAllAuditTrailsById(ctx context.Context, arg QueryAllAuditTrailsByIdParams) ([]QueryAllAuditTrailsByIdRow, error) {
	rows, err := q.db.Query(ctx, queryAllAuditTrailsById, arg.ID, arg.CurrentOffset, arg.LimitBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllAuditTrailsByIdRow
	for rows.Next() {
		var i QueryAllAuditTrailsByIdRow
		if err := rows.Scan(
			&i.AuditTrail.ID,
			&i.AuditTrail.SchemaName,
			&i.AuditTrail.TableName,
			&i.AuditTrail.Relid,
			&i.AuditTrail.SessionUserName,
			&i.AuditTrail.ActionTstampTx,
			&i.AuditTrail.ActionTstampStm,
			&i.AuditTrail.ActionTstampClk,
			&i.AuditTrail.TransactionID,
			&i.AuditTrail.ApplicationName,
			&i.AuditTrail.ClientAddr,
			&i.AuditTrail.ClientPort,
			&i.AuditTrail.ClientQuery,
			&i.AuditTrail.Action,
			&i.AuditTrail.RowData,
			&i.AuditTrail.ChangedFields,
			&i.AuditTrail.StatementOnly,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAllAuditTrailsByTable = `-- name: QueryAllAuditTrailsByTable :many
SELECT 
  t.id, t.schema_name, t.table_name, t.relid, t.session_user_name, t.action_tstamp_tx, t.action_tstamp_stm, t.action_tstamp_clk, t.transaction_id, t.application_name, t.client_addr, t.client_port, t.client_query, t.action, t.row_data, t.changed_fields, t.statement_only,
  COUNT(*) OVER() AS total_records  
FROM audit_trail t
WHERE t.table_name = $1
LIMIT $3
OFFSET $2
`

type QueryAllAuditTrailsByTableParams struct {
	TableName     string `db:"table_name" json:"table_name"`
	CurrentOffset int32  `db:"current_offset" json:"current_offset"`
	LimitBy       int32  `db:"limit_by" json:"limit_by"`
}

type QueryAllAuditTrailsByTableRow struct {
	AuditTrail   AuditTrail `db:"audit_trail" json:"audit_trail"`
	TotalRecords int64      `db:"total_records" json:"total_records"`
}

// QueryAllAuditTrailsByTable
//
//	SELECT
//	  t.id, t.schema_name, t.table_name, t.relid, t.session_user_name, t.action_tstamp_tx, t.action_tstamp_stm, t.action_tstamp_clk, t.transaction_id, t.application_name, t.client_addr, t.client_port, t.client_query, t.action, t.row_data, t.changed_fields, t.statement_only,
//	  COUNT(*) OVER() AS total_records
//	FROM audit_trail t
//	WHERE t.table_name = $1
//	LIMIT $3
//	OFFSET $2
func (q *Queries) QueryAllAuditTrailsByTable(ctx context.Context, arg QueryAllAuditTrailsByTableParams) ([]QueryAllAuditTrailsByTableRow, error) {
	rows, err := q.db.Query(ctx, queryAllAuditTrailsByTable, arg.TableName, arg.CurrentOffset, arg.LimitBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllAuditTrailsByTableRow
	for rows.Next() {
		var i QueryAllAuditTrailsByTableRow
		if err := rows.Scan(
			&i.AuditTrail.ID,
			&i.AuditTrail.SchemaName,
			&i.AuditTrail.TableName,
			&i.AuditTrail.Relid,
			&i.AuditTrail.SessionUserName,
			&i.AuditTrail.ActionTstampTx,
			&i.AuditTrail.ActionTstampStm,
			&i.AuditTrail.ActionTstampClk,
			&i.AuditTrail.TransactionID,
			&i.AuditTrail.ApplicationName,
			&i.AuditTrail.ClientAddr,
			&i.AuditTrail.ClientPort,
			&i.AuditTrail.ClientQuery,
			&i.AuditTrail.Action,
			&i.AuditTrail.RowData,
			&i.AuditTrail.ChangedFields,
			&i.AuditTrail.StatementOnly,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
