// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: kafka_write_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryCreateKafkaOutboxEvent = `-- name: QueryCreateKafkaOutboxEvent :one
INSERT INTO 
  kafka_outbox_events (
    partition_key,
    correlation_id,
    destination,
    event_type,
    payload,
    error_message,
    metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, correlation_id, partition_key, destination, event_type, payload, error_message, metadata, sent_time, created_at, updated_at, deleted_at
`

type QueryCreateKafkaOutboxEventParams struct {
	PartitionKey  pgtype.Text `db:"partition_key" json:"partition_key"`
	CorrelationID pgtype.Text `db:"correlation_id" json:"correlation_id"`
	Destination   string      `db:"destination" json:"destination"`
	EventType     string      `db:"event_type" json:"event_type"`
	Payload       []byte      `db:"payload" json:"payload"`
	ErrorMessage  pgtype.Text `db:"error_message" json:"error_message"`
	Metadata      []byte      `db:"metadata" json:"metadata"`
}

// QueryCreateKafkaOutboxEvent
//
//	INSERT INTO
//	  kafka_outbox_events (
//	    partition_key,
//	    correlation_id,
//	    destination,
//	    event_type,
//	    payload,
//	    error_message,
//	    metadata
//	) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, correlation_id, partition_key, destination, event_type, payload, error_message, metadata, sent_time, created_at, updated_at, deleted_at
func (q *Queries) QueryCreateKafkaOutboxEvent(ctx context.Context, arg QueryCreateKafkaOutboxEventParams) (KafkaOutboxEvent, error) {
	row := q.db.QueryRow(ctx, queryCreateKafkaOutboxEvent,
		arg.PartitionKey,
		arg.CorrelationID,
		arg.Destination,
		arg.EventType,
		arg.Payload,
		arg.ErrorMessage,
		arg.Metadata,
	)
	var i KafkaOutboxEvent
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.PartitionKey,
		&i.Destination,
		&i.EventType,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryDeleteKafkaOutboxEvent = `-- name: QueryDeleteKafkaOutboxEvent :one
DELETE FROM kafka_outbox_events WHERE id = $1 RETURNING id, correlation_id, partition_key, destination, event_type, payload, error_message, metadata, sent_time, created_at, updated_at, deleted_at
`

// QueryDeleteKafkaOutboxEvent
//
//	DELETE FROM kafka_outbox_events WHERE id = $1 RETURNING id, correlation_id, partition_key, destination, event_type, payload, error_message, metadata, sent_time, created_at, updated_at, deleted_at
func (q *Queries) QueryDeleteKafkaOutboxEvent(ctx context.Context, id string) (KafkaOutboxEvent, error) {
	row := q.db.QueryRow(ctx, queryDeleteKafkaOutboxEvent, id)
	var i KafkaOutboxEvent
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.PartitionKey,
		&i.Destination,
		&i.EventType,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryMarkKafkaOutboxEventAsSent = `-- name: QueryMarkKafkaOutboxEventAsSent :one
UPDATE kafka_outbox_events
SET
  sent_time=$2,
  updated_at=now()
WHERE id = $1 RETURNING id, correlation_id, partition_key, destination, event_type, payload, error_message, metadata, sent_time, created_at, updated_at, deleted_at
`

type QueryMarkKafkaOutboxEventAsSentParams struct {
	ID       string             `db:"id" json:"id"`
	SentTime pgtype.Timestamptz `db:"sent_time" json:"sent_time"`
}

// QueryMarkKafkaOutboxEventAsSent
//
//	UPDATE kafka_outbox_events
//	SET
//	  sent_time=$2,
//	  updated_at=now()
//	WHERE id = $1 RETURNING id, correlation_id, partition_key, destination, event_type, payload, error_message, metadata, sent_time, created_at, updated_at, deleted_at
func (q *Queries) QueryMarkKafkaOutboxEventAsSent(ctx context.Context, arg QueryMarkKafkaOutboxEventAsSentParams) (KafkaOutboxEvent, error) {
	row := q.db.QueryRow(ctx, queryMarkKafkaOutboxEventAsSent, arg.ID, arg.SentTime)
	var i KafkaOutboxEvent
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.PartitionKey,
		&i.Destination,
		&i.EventType,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const querySoftDeleteKafkaOutboxEvent = `-- name: QuerySoftDeleteKafkaOutboxEvent :one
UPDATE kafka_outbox_events
SET
  deleted_at = $2,
  updated_at = now()
WHERE id = $1 RETURNING id, correlation_id, partition_key, destination, event_type, payload, error_message, metadata, sent_time, created_at, updated_at, deleted_at
`

type QuerySoftDeleteKafkaOutboxEventParams struct {
	ID        string             `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// QuerySoftDeleteKafkaOutboxEvent
//
//	UPDATE kafka_outbox_events
//	SET
//	  deleted_at = $2,
//	  updated_at = now()
//	WHERE id = $1 RETURNING id, correlation_id, partition_key, destination, event_type, payload, error_message, metadata, sent_time, created_at, updated_at, deleted_at
func (q *Queries) QuerySoftDeleteKafkaOutboxEvent(ctx context.Context, arg QuerySoftDeleteKafkaOutboxEventParams) (KafkaOutboxEvent, error) {
	row := q.db.QueryRow(ctx, querySoftDeleteKafkaOutboxEvent, arg.ID, arg.DeletedAt)
	var i KafkaOutboxEvent
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.PartitionKey,
		&i.Destination,
		&i.EventType,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateKafkaOutboxEvent = `-- name: QueryUpdateKafkaOutboxEvent :one
UPDATE kafka_outbox_events AS koe
SET
  error_message=$2,
  sent_time=$3,
  destination=$4,
  updated_at=now()
WHERE koe.id = $1 RETURNING id, correlation_id, partition_key, destination, event_type, payload, error_message, metadata, sent_time, created_at, updated_at, deleted_at
`

type QueryUpdateKafkaOutboxEventParams struct {
	ID           string             `db:"id" json:"id"`
	ErrorMessage pgtype.Text        `db:"error_message" json:"error_message"`
	SentTime     pgtype.Timestamptz `db:"sent_time" json:"sent_time"`
	Destination  string             `db:"destination" json:"destination"`
}

// QueryUpdateKafkaOutboxEvent
//
//	UPDATE kafka_outbox_events AS koe
//	SET
//	  error_message=$2,
//	  sent_time=$3,
//	  destination=$4,
//	  updated_at=now()
//	WHERE koe.id = $1 RETURNING id, correlation_id, partition_key, destination, event_type, payload, error_message, metadata, sent_time, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateKafkaOutboxEvent(ctx context.Context, arg QueryUpdateKafkaOutboxEventParams) (KafkaOutboxEvent, error) {
	row := q.db.QueryRow(ctx, queryUpdateKafkaOutboxEvent,
		arg.ID,
		arg.ErrorMessage,
		arg.SentTime,
		arg.Destination,
	)
	var i KafkaOutboxEvent
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.PartitionKey,
		&i.Destination,
		&i.EventType,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateKafkaOutboxEventError = `-- name: QueryUpdateKafkaOutboxEventError :one
UPDATE kafka_outbox_events AS koe
SET
  error_message=$2,
  updated_at=now()
WHERE koe.id = $1 RETURNING id, correlation_id, partition_key, destination, event_type, payload, error_message, metadata, sent_time, created_at, updated_at, deleted_at
`

type QueryUpdateKafkaOutboxEventErrorParams struct {
	ID           string      `db:"id" json:"id"`
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
}

// QueryUpdateKafkaOutboxEventError
//
//	UPDATE kafka_outbox_events AS koe
//	SET
//	  error_message=$2,
//	  updated_at=now()
//	WHERE koe.id = $1 RETURNING id, correlation_id, partition_key, destination, event_type, payload, error_message, metadata, sent_time, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateKafkaOutboxEventError(ctx context.Context, arg QueryUpdateKafkaOutboxEventErrorParams) (KafkaOutboxEvent, error) {
	row := q.db.QueryRow(ctx, queryUpdateKafkaOutboxEventError, arg.ID, arg.ErrorMessage)
	var i KafkaOutboxEvent
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.PartitionKey,
		&i.Destination,
		&i.EventType,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
