// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: kafka_read_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryAllKafkaOutboxEvents = `-- name: QueryAllKafkaOutboxEvents :many
SELECT
  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
FROM kafka_outbox_events koe
WHERE $1::bool OR koe.deleted_at IS NULL
AND (
  $2::text IS NULL
  OR $3::timestamp IS NULL
  OR $4::timestamp IS NULL
  OR (
    CASE 
      WHEN $2::text = 'created_at' THEN koe.created_at
      WHEN $2::text = 'updated_at' THEN koe.updated_at
      WHEN $2::text = 'deleted_at' THEN koe.deleted_at
    END BETWEEN $3::timestamp AND $4::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $5::text = 'created_at' THEN koe.created_at 
    WHEN $5::text = 'updated_at' THEN koe.updated_at 
    WHEN $5::text = 'deleted_at' THEN koe.deleted_at 
END,
  CASE
    WHEN $6::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $8
OFFSET $7
`

type QueryAllKafkaOutboxEventsParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryAllKafkaOutboxEventsRow struct {
	KafkaOutboxEvent KafkaOutboxEvent `db:"kafka_outbox_event" json:"kafka_outbox_event"`
}

// Date range filtering
//
//	SELECT
//	  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
//	FROM kafka_outbox_events koe
//	WHERE $1::bool OR koe.deleted_at IS NULL
//	AND (
//	  $2::text IS NULL
//	  OR $3::timestamp IS NULL
//	  OR $4::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $2::text = 'created_at' THEN koe.created_at
//	      WHEN $2::text = 'updated_at' THEN koe.updated_at
//	      WHEN $2::text = 'deleted_at' THEN koe.deleted_at
//	    END BETWEEN $3::timestamp AND $4::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $5::text = 'created_at' THEN koe.created_at
//	    WHEN $5::text = 'updated_at' THEN koe.updated_at
//	    WHEN $5::text = 'deleted_at' THEN koe.deleted_at
//	END,
//	  CASE
//	    WHEN $6::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $8
//	OFFSET $7
func (q *Queries) QueryAllKafkaOutboxEvents(ctx context.Context, arg QueryAllKafkaOutboxEventsParams) ([]QueryAllKafkaOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, queryAllKafkaOutboxEvents,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllKafkaOutboxEventsRow
	for rows.Next() {
		var i QueryAllKafkaOutboxEventsRow
		if err := rows.Scan(
			&i.KafkaOutboxEvent.ID,
			&i.KafkaOutboxEvent.CorrelationID,
			&i.KafkaOutboxEvent.PartitionKey,
			&i.KafkaOutboxEvent.Destination,
			&i.KafkaOutboxEvent.EventType,
			&i.KafkaOutboxEvent.Payload,
			&i.KafkaOutboxEvent.ErrorMessage,
			&i.KafkaOutboxEvent.Metadata,
			&i.KafkaOutboxEvent.SentTime,
			&i.KafkaOutboxEvent.CreatedAt,
			&i.KafkaOutboxEvent.UpdatedAt,
			&i.KafkaOutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAllKafkaOutboxEventsCount = `-- name: QueryAllKafkaOutboxEventsCount :one
SELECT
  count(*)
FROM kafka_outbox_events koe
WHERE $1::bool OR koe.deleted_at IS NULL
`

// QueryAllKafkaOutboxEventsCount
//
//	SELECT
//	  count(*)
//	FROM kafka_outbox_events koe
//	WHERE $1::bool OR koe.deleted_at IS NULL
func (q *Queries) QueryAllKafkaOutboxEventsCount(ctx context.Context, includeDeleted bool) (int64, error) {
	row := q.db.QueryRow(ctx, queryAllKafkaOutboxEventsCount, includeDeleted)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const queryKafkaOutboxEventByCorrelationId = `-- name: QueryKafkaOutboxEventByCorrelationId :one
SELECT
  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
FROM kafka_outbox_events koe
WHERE koe.correlation_id = $1
`

type QueryKafkaOutboxEventByCorrelationIdRow struct {
	KafkaOutboxEvent KafkaOutboxEvent `db:"kafka_outbox_event" json:"kafka_outbox_event"`
}

// QueryKafkaOutboxEventByCorrelationId
//
//	SELECT
//	  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
//	FROM kafka_outbox_events koe
//	WHERE koe.correlation_id = $1
func (q *Queries) QueryKafkaOutboxEventByCorrelationId(ctx context.Context, correlationID pgtype.Text) (QueryKafkaOutboxEventByCorrelationIdRow, error) {
	row := q.db.QueryRow(ctx, queryKafkaOutboxEventByCorrelationId, correlationID)
	var i QueryKafkaOutboxEventByCorrelationIdRow
	err := row.Scan(
		&i.KafkaOutboxEvent.ID,
		&i.KafkaOutboxEvent.CorrelationID,
		&i.KafkaOutboxEvent.PartitionKey,
		&i.KafkaOutboxEvent.Destination,
		&i.KafkaOutboxEvent.EventType,
		&i.KafkaOutboxEvent.Payload,
		&i.KafkaOutboxEvent.ErrorMessage,
		&i.KafkaOutboxEvent.Metadata,
		&i.KafkaOutboxEvent.SentTime,
		&i.KafkaOutboxEvent.CreatedAt,
		&i.KafkaOutboxEvent.UpdatedAt,
		&i.KafkaOutboxEvent.DeletedAt,
	)
	return i, err
}

const queryKafkaOutboxEventById = `-- name: QueryKafkaOutboxEventById :one
SELECT
  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
FROM kafka_outbox_events koe
WHERE koe.id = $1
`

type QueryKafkaOutboxEventByIdRow struct {
	KafkaOutboxEvent KafkaOutboxEvent `db:"kafka_outbox_event" json:"kafka_outbox_event"`
}

// QueryKafkaOutboxEventById
//
//	SELECT
//	  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
//	FROM kafka_outbox_events koe
//	WHERE koe.id = $1
func (q *Queries) QueryKafkaOutboxEventById(ctx context.Context, id string) (QueryKafkaOutboxEventByIdRow, error) {
	row := q.db.QueryRow(ctx, queryKafkaOutboxEventById, id)
	var i QueryKafkaOutboxEventByIdRow
	err := row.Scan(
		&i.KafkaOutboxEvent.ID,
		&i.KafkaOutboxEvent.CorrelationID,
		&i.KafkaOutboxEvent.PartitionKey,
		&i.KafkaOutboxEvent.Destination,
		&i.KafkaOutboxEvent.EventType,
		&i.KafkaOutboxEvent.Payload,
		&i.KafkaOutboxEvent.ErrorMessage,
		&i.KafkaOutboxEvent.Metadata,
		&i.KafkaOutboxEvent.SentTime,
		&i.KafkaOutboxEvent.CreatedAt,
		&i.KafkaOutboxEvent.UpdatedAt,
		&i.KafkaOutboxEvent.DeletedAt,
	)
	return i, err
}

const queryKafkaOutboxEventsByDestination = `-- name: QueryKafkaOutboxEventsByDestination :many
SELECT
  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
FROM kafka_outbox_events koe
WHERE $2::bool OR koe.deleted_at IS NULL
AND koe.destination = $1
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN b.created_at
      WHEN $3::text = 'updated_at' THEN b.updated_at
      WHEN $3::text = 'deleted_at' THEN b.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $6::text = 'created_at' THEN koe.created_at 
    WHEN $6::text = 'updated_at' THEN koe.updated_at 
    WHEN $6::text = 'deleted_at' THEN koe.deleted_at 
END,
  CASE
    WHEN $7::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $9
OFFSET $8
`

type QueryKafkaOutboxEventsByDestinationParams struct {
	Destination    string           `db:"destination" json:"destination"`
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryKafkaOutboxEventsByDestinationRow struct {
	KafkaOutboxEvent KafkaOutboxEvent `db:"kafka_outbox_event" json:"kafka_outbox_event"`
}

// Date range filtering
//
//	SELECT
//	  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
//	FROM kafka_outbox_events koe
//	WHERE $2::bool OR koe.deleted_at IS NULL
//	AND koe.destination = $1
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN b.created_at
//	      WHEN $3::text = 'updated_at' THEN b.updated_at
//	      WHEN $3::text = 'deleted_at' THEN b.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $6::text = 'created_at' THEN koe.created_at
//	    WHEN $6::text = 'updated_at' THEN koe.updated_at
//	    WHEN $6::text = 'deleted_at' THEN koe.deleted_at
//	END,
//	  CASE
//	    WHEN $7::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryKafkaOutboxEventsByDestination(ctx context.Context, arg QueryKafkaOutboxEventsByDestinationParams) ([]QueryKafkaOutboxEventsByDestinationRow, error) {
	rows, err := q.db.Query(ctx, queryKafkaOutboxEventsByDestination,
		arg.Destination,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryKafkaOutboxEventsByDestinationRow
	for rows.Next() {
		var i QueryKafkaOutboxEventsByDestinationRow
		if err := rows.Scan(
			&i.KafkaOutboxEvent.ID,
			&i.KafkaOutboxEvent.CorrelationID,
			&i.KafkaOutboxEvent.PartitionKey,
			&i.KafkaOutboxEvent.Destination,
			&i.KafkaOutboxEvent.EventType,
			&i.KafkaOutboxEvent.Payload,
			&i.KafkaOutboxEvent.ErrorMessage,
			&i.KafkaOutboxEvent.Metadata,
			&i.KafkaOutboxEvent.SentTime,
			&i.KafkaOutboxEvent.CreatedAt,
			&i.KafkaOutboxEvent.UpdatedAt,
			&i.KafkaOutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryKafkaOutboxEventsByEventType = `-- name: QueryKafkaOutboxEventsByEventType :many
SELECT
  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
FROM kafka_outbox_events koe
WHERE $2::bool OR koe.deleted_at IS NULL
AND koe.event_type = $1
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN b.created_at
      WHEN $3::text = 'updated_at' THEN b.updated_at
      WHEN $3::text = 'deleted_at' THEN b.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $6::text = 'created_at' THEN koe.created_at 
    WHEN $6::text = 'updated_at' THEN koe.updated_at 
    WHEN $6::text = 'deleted_at' THEN koe.deleted_at 
END,
  CASE
    WHEN $7::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $9
OFFSET $8
`

type QueryKafkaOutboxEventsByEventTypeParams struct {
	EventType      string           `db:"event_type" json:"event_type"`
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryKafkaOutboxEventsByEventTypeRow struct {
	KafkaOutboxEvent KafkaOutboxEvent `db:"kafka_outbox_event" json:"kafka_outbox_event"`
}

// Date range filtering
//
//	SELECT
//	  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
//	FROM kafka_outbox_events koe
//	WHERE $2::bool OR koe.deleted_at IS NULL
//	AND koe.event_type = $1
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN b.created_at
//	      WHEN $3::text = 'updated_at' THEN b.updated_at
//	      WHEN $3::text = 'deleted_at' THEN b.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $6::text = 'created_at' THEN koe.created_at
//	    WHEN $6::text = 'updated_at' THEN koe.updated_at
//	    WHEN $6::text = 'deleted_at' THEN koe.deleted_at
//	END,
//	  CASE
//	    WHEN $7::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryKafkaOutboxEventsByEventType(ctx context.Context, arg QueryKafkaOutboxEventsByEventTypeParams) ([]QueryKafkaOutboxEventsByEventTypeRow, error) {
	rows, err := q.db.Query(ctx, queryKafkaOutboxEventsByEventType,
		arg.EventType,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryKafkaOutboxEventsByEventTypeRow
	for rows.Next() {
		var i QueryKafkaOutboxEventsByEventTypeRow
		if err := rows.Scan(
			&i.KafkaOutboxEvent.ID,
			&i.KafkaOutboxEvent.CorrelationID,
			&i.KafkaOutboxEvent.PartitionKey,
			&i.KafkaOutboxEvent.Destination,
			&i.KafkaOutboxEvent.EventType,
			&i.KafkaOutboxEvent.Payload,
			&i.KafkaOutboxEvent.ErrorMessage,
			&i.KafkaOutboxEvent.Metadata,
			&i.KafkaOutboxEvent.SentTime,
			&i.KafkaOutboxEvent.CreatedAt,
			&i.KafkaOutboxEvent.UpdatedAt,
			&i.KafkaOutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryKafkaOutboxEventsByPartitionKey = `-- name: QueryKafkaOutboxEventsByPartitionKey :many
SELECT
  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
FROM kafka_outbox_events koe
WHERE $1::bool OR koe.deleted_at IS NULL
AND koe.partition_key = $2
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN b.created_at
      WHEN $3::text = 'updated_at' THEN b.updated_at
      WHEN $3::text = 'deleted_at' THEN b.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $6::text = 'created_at' THEN koe.created_at 
    WHEN $6::text = 'updated_at' THEN koe.updated_at 
    WHEN $6::text = 'deleted_at' THEN koe.deleted_at 
END,
  CASE
    WHEN $7::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $9
OFFSET $8
`

type QueryKafkaOutboxEventsByPartitionKeyParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	PartitionKey   pgtype.Text      `db:"partition_key" json:"partition_key"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryKafkaOutboxEventsByPartitionKeyRow struct {
	KafkaOutboxEvent KafkaOutboxEvent `db:"kafka_outbox_event" json:"kafka_outbox_event"`
}

// Date range filtering
//
//	SELECT
//	  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
//	FROM kafka_outbox_events koe
//	WHERE $1::bool OR koe.deleted_at IS NULL
//	AND koe.partition_key = $2
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN b.created_at
//	      WHEN $3::text = 'updated_at' THEN b.updated_at
//	      WHEN $3::text = 'deleted_at' THEN b.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $6::text = 'created_at' THEN koe.created_at
//	    WHEN $6::text = 'updated_at' THEN koe.updated_at
//	    WHEN $6::text = 'deleted_at' THEN koe.deleted_at
//	END,
//	  CASE
//	    WHEN $7::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryKafkaOutboxEventsByPartitionKey(ctx context.Context, arg QueryKafkaOutboxEventsByPartitionKeyParams) ([]QueryKafkaOutboxEventsByPartitionKeyRow, error) {
	rows, err := q.db.Query(ctx, queryKafkaOutboxEventsByPartitionKey,
		arg.IncludeDeleted,
		arg.PartitionKey,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryKafkaOutboxEventsByPartitionKeyRow
	for rows.Next() {
		var i QueryKafkaOutboxEventsByPartitionKeyRow
		if err := rows.Scan(
			&i.KafkaOutboxEvent.ID,
			&i.KafkaOutboxEvent.CorrelationID,
			&i.KafkaOutboxEvent.PartitionKey,
			&i.KafkaOutboxEvent.Destination,
			&i.KafkaOutboxEvent.EventType,
			&i.KafkaOutboxEvent.Payload,
			&i.KafkaOutboxEvent.ErrorMessage,
			&i.KafkaOutboxEvent.Metadata,
			&i.KafkaOutboxEvent.SentTime,
			&i.KafkaOutboxEvent.CreatedAt,
			&i.KafkaOutboxEvent.UpdatedAt,
			&i.KafkaOutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryKafkaOutboxEventsSent = `-- name: QueryKafkaOutboxEventsSent :many
SELECT
  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
FROM kafka_outbox_events koe
WHERE $1::bool OR koe.deleted_at IS NULL
AND koe.sent_time IS NOT NULL
AND (
  $2::text IS NULL
  OR $3::timestamp IS NULL
  OR $4::timestamp IS NULL
  OR (
    CASE 
      WHEN $2::text = 'created_at' THEN b.created_at
      WHEN $2::text = 'updated_at' THEN b.updated_at
      WHEN $2::text = 'deleted_at' THEN b.deleted_at
    END BETWEEN $3::timestamp AND $4::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $5::text = 'created_at' THEN koe.created_at 
    WHEN $5::text = 'updated_at' THEN koe.updated_at 
    WHEN $5::text = 'deleted_at' THEN koe.deleted_at 
END,
  CASE
    WHEN $6::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $8
OFFSET $7
`

type QueryKafkaOutboxEventsSentParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryKafkaOutboxEventsSentRow struct {
	KafkaOutboxEvent KafkaOutboxEvent `db:"kafka_outbox_event" json:"kafka_outbox_event"`
}

// Date range filtering
//
//	SELECT
//	  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
//	FROM kafka_outbox_events koe
//	WHERE $1::bool OR koe.deleted_at IS NULL
//	AND koe.sent_time IS NOT NULL
//	AND (
//	  $2::text IS NULL
//	  OR $3::timestamp IS NULL
//	  OR $4::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $2::text = 'created_at' THEN b.created_at
//	      WHEN $2::text = 'updated_at' THEN b.updated_at
//	      WHEN $2::text = 'deleted_at' THEN b.deleted_at
//	    END BETWEEN $3::timestamp AND $4::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $5::text = 'created_at' THEN koe.created_at
//	    WHEN $5::text = 'updated_at' THEN koe.updated_at
//	    WHEN $5::text = 'deleted_at' THEN koe.deleted_at
//	END,
//	  CASE
//	    WHEN $6::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $8
//	OFFSET $7
func (q *Queries) QueryKafkaOutboxEventsSent(ctx context.Context, arg QueryKafkaOutboxEventsSentParams) ([]QueryKafkaOutboxEventsSentRow, error) {
	rows, err := q.db.Query(ctx, queryKafkaOutboxEventsSent,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryKafkaOutboxEventsSentRow
	for rows.Next() {
		var i QueryKafkaOutboxEventsSentRow
		if err := rows.Scan(
			&i.KafkaOutboxEvent.ID,
			&i.KafkaOutboxEvent.CorrelationID,
			&i.KafkaOutboxEvent.PartitionKey,
			&i.KafkaOutboxEvent.Destination,
			&i.KafkaOutboxEvent.EventType,
			&i.KafkaOutboxEvent.Payload,
			&i.KafkaOutboxEvent.ErrorMessage,
			&i.KafkaOutboxEvent.Metadata,
			&i.KafkaOutboxEvent.SentTime,
			&i.KafkaOutboxEvent.CreatedAt,
			&i.KafkaOutboxEvent.UpdatedAt,
			&i.KafkaOutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryKafkaOutboxEventsUnSent = `-- name: QueryKafkaOutboxEventsUnSent :many
SELECT
  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
FROM kafka_outbox_events koe
WHERE $1::bool OR koe.deleted_at IS NULL
AND koe.sent_time IS NULL
AND (
  $2::text IS NULL
  OR $3::timestamp IS NULL
  OR $4::timestamp IS NULL
  OR (
    CASE 
      WHEN $2::text = 'created_at' THEN b.created_at
      WHEN $2::text = 'updated_at' THEN b.updated_at
      WHEN $2::text = 'deleted_at' THEN b.deleted_at
    END BETWEEN $3::timestamp AND $4::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $5::text = 'created_at' THEN koe.created_at 
    WHEN $5::text = 'updated_at' THEN koe.updated_at 
    WHEN $5::text = 'deleted_at' THEN koe.deleted_at 
END,
  CASE
    WHEN $6::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $8
OFFSET $7
`

type QueryKafkaOutboxEventsUnSentParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryKafkaOutboxEventsUnSentRow struct {
	KafkaOutboxEvent KafkaOutboxEvent `db:"kafka_outbox_event" json:"kafka_outbox_event"`
}

// Date range filtering
//
//	SELECT
//	  koe.id, koe.correlation_id, koe.partition_key, koe.destination, koe.event_type, koe.payload, koe.error_message, koe.metadata, koe.sent_time, koe.created_at, koe.updated_at, koe.deleted_at
//	FROM kafka_outbox_events koe
//	WHERE $1::bool OR koe.deleted_at IS NULL
//	AND koe.sent_time IS NULL
//	AND (
//	  $2::text IS NULL
//	  OR $3::timestamp IS NULL
//	  OR $4::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $2::text = 'created_at' THEN b.created_at
//	      WHEN $2::text = 'updated_at' THEN b.updated_at
//	      WHEN $2::text = 'deleted_at' THEN b.deleted_at
//	    END BETWEEN $3::timestamp AND $4::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $5::text = 'created_at' THEN koe.created_at
//	    WHEN $5::text = 'updated_at' THEN koe.updated_at
//	    WHEN $5::text = 'deleted_at' THEN koe.deleted_at
//	END,
//	  CASE
//	    WHEN $6::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $8
//	OFFSET $7
func (q *Queries) QueryKafkaOutboxEventsUnSent(ctx context.Context, arg QueryKafkaOutboxEventsUnSentParams) ([]QueryKafkaOutboxEventsUnSentRow, error) {
	rows, err := q.db.Query(ctx, queryKafkaOutboxEventsUnSent,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryKafkaOutboxEventsUnSentRow
	for rows.Next() {
		var i QueryKafkaOutboxEventsUnSentRow
		if err := rows.Scan(
			&i.KafkaOutboxEvent.ID,
			&i.KafkaOutboxEvent.CorrelationID,
			&i.KafkaOutboxEvent.PartitionKey,
			&i.KafkaOutboxEvent.Destination,
			&i.KafkaOutboxEvent.EventType,
			&i.KafkaOutboxEvent.Payload,
			&i.KafkaOutboxEvent.ErrorMessage,
			&i.KafkaOutboxEvent.Metadata,
			&i.KafkaOutboxEvent.SentTime,
			&i.KafkaOutboxEvent.CreatedAt,
			&i.KafkaOutboxEvent.UpdatedAt,
			&i.KafkaOutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
