// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: keywords_write_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryCreateKeyword = `-- name: QueryCreateKeyword :one
INSERT INTO keywords (
  url_id,
  value
)
VALUES ($1, $2) RETURNING id, url_id, value, created_at, updated_at, deleted_at
`

type QueryCreateKeywordParams struct {
	UrlID pgtype.UUID `db:"url_id" json:"url_id"`
	Value string      `db:"value" json:"value"`
}

// QueryCreateKeyword
//
//	INSERT INTO keywords (
//	  url_id,
//	  value
//	)
//	VALUES ($1, $2) RETURNING id, url_id, value, created_at, updated_at, deleted_at
func (q *Queries) QueryCreateKeyword(ctx context.Context, arg QueryCreateKeywordParams) (Keyword, error) {
	row := q.db.QueryRow(ctx, queryCreateKeyword, arg.UrlID, arg.Value)
	var i Keyword
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryDeleteKeywordWithId = `-- name: QueryDeleteKeywordWithId :one
DELETE FROM keywords WHERE id = $1 RETURNING id, url_id, value, created_at, updated_at, deleted_at
`

// QueryDeleteKeywordWithId
//
//	DELETE FROM keywords WHERE id = $1 RETURNING id, url_id, value, created_at, updated_at, deleted_at
func (q *Queries) QueryDeleteKeywordWithId(ctx context.Context, id pgtype.UUID) (Keyword, error) {
	row := q.db.QueryRow(ctx, queryDeleteKeywordWithId, id)
	var i Keyword
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const querySoftDeleteKeyword = `-- name: QuerySoftDeleteKeyword :one
UPDATE keywords
SET
  deleted_at = $2,
  updated_at = NOW()
WHERE id = $1 RETURNING id, url_id, value, created_at, updated_at, deleted_at
`

type QuerySoftDeleteKeywordParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// QuerySoftDeleteKeyword
//
//	UPDATE keywords
//	SET
//	  deleted_at = $2,
//	  updated_at = NOW()
//	WHERE id = $1 RETURNING id, url_id, value, created_at, updated_at, deleted_at
func (q *Queries) QuerySoftDeleteKeyword(ctx context.Context, arg QuerySoftDeleteKeywordParams) (Keyword, error) {
	row := q.db.QueryRow(ctx, querySoftDeleteKeyword, arg.ID, arg.DeletedAt)
	var i Keyword
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateKeyword = `-- name: QueryUpdateKeyword :one
UPDATE keywords
SET
  value=$2,
  updated_at=NOW()
WHERE id = $1 RETURNING id, url_id, value, created_at, updated_at, deleted_at
`

type QueryUpdateKeywordParams struct {
	ID    pgtype.UUID `db:"id" json:"id"`
	Value string      `db:"value" json:"value"`
}

// QueryUpdateKeyword
//
//	UPDATE keywords
//	SET
//	  value=$2,
//	  updated_at=NOW()
//	WHERE id = $1 RETURNING id, url_id, value, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateKeyword(ctx context.Context, arg QueryUpdateKeywordParams) (Keyword, error) {
	row := q.db.QueryRow(ctx, queryUpdateKeyword, arg.ID, arg.Value)
	var i Keyword
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
