// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: keywords_read_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryAllKeywords = `-- name: QueryAllKeywords :many
SELECT 
  kw.id, kw.url_id, kw.value, kw.created_at, kw.updated_at, kw.deleted_at,
  COUNT(*) OVER() AS total_records
FROM keywords kw 
WHERE $1::bool OR kw.deleted_at IS NULL
  AND (COALESCE($2, '') = '' OR us.name = $2)
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN kw.created_at
      WHEN $3::text = 'updated_at' THEN kw.updated_at
      WHEN $3::text = 'deleted_at' THEN kw.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  -- Sort by 'created_at'
  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC' 
    THEN kw.created_at END ASC,
  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC' 
    THEN kw.created_at END DESC,
  
  -- Sort by 'updated_at'
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC' 
    THEN kw.updated_at END ASC,
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC' 
    THEN kw.updated_at END DESC,
  
  -- Sort by 'deleted_at'
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC' 
    THEN kw.deleted_at END ASC,
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC' 
    THEN kw.deleted_at END DESC
LIMIT $9
OFFSET $8
`

type QueryAllKeywordsParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	UrlStatus      interface{}      `db:"url_status" json:"url_status"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryAllKeywordsRow struct {
	Keyword      Keyword `db:"keyword" json:"keyword"`
	TotalRecords int64   `db:"total_records" json:"total_records"`
}

// Date range filtering
//
//	SELECT
//	  kw.id, kw.url_id, kw.value, kw.created_at, kw.updated_at, kw.deleted_at,
//	  COUNT(*) OVER() AS total_records
//	FROM keywords kw
//	WHERE $1::bool OR kw.deleted_at IS NULL
//	  AND (COALESCE($2, '') = '' OR us.name = $2)
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN kw.created_at
//	      WHEN $3::text = 'updated_at' THEN kw.updated_at
//	      WHEN $3::text = 'deleted_at' THEN kw.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  -- Sort by 'created_at'
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC'
//	    THEN kw.created_at END ASC,
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC'
//	    THEN kw.created_at END DESC,
//
//	  -- Sort by 'updated_at'
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC'
//	    THEN kw.updated_at END ASC,
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC'
//	    THEN kw.updated_at END DESC,
//
//	  -- Sort by 'deleted_at'
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC'
//	    THEN kw.deleted_at END ASC,
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC'
//	    THEN kw.deleted_at END DESC
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryAllKeywords(ctx context.Context, arg QueryAllKeywordsParams) ([]QueryAllKeywordsRow, error) {
	rows, err := q.db.Query(ctx, queryAllKeywords,
		arg.IncludeDeleted,
		arg.UrlStatus,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllKeywordsRow
	for rows.Next() {
		var i QueryAllKeywordsRow
		if err := rows.Scan(
			&i.Keyword.ID,
			&i.Keyword.UrlID,
			&i.Keyword.Value,
			&i.Keyword.CreatedAt,
			&i.Keyword.UpdatedAt,
			&i.Keyword.DeletedAt,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAllKeywordsByUrlId = `-- name: QueryAllKeywordsByUrlId :many
SELECT 
  kw.id, kw.url_id, kw.value, kw.created_at, kw.updated_at, kw.deleted_at,
  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at,
  COUNT(*) OVER() AS total_records
FROM keywords kw 
JOIN urls u ON kw.url_id = u.id
WHERE kw.url_id = $1
  AND ($2::bool OR kw.deleted_at IS NULL)
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN kw.created_at
      WHEN $3::text = 'updated_at' THEN kw.updated_at
      WHEN $3::text = 'deleted_at' THEN kw.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  -- Sort by 'created_at'
  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC' 
    THEN kw.created_at END ASC,
  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC' 
    THEN kw.created_at END DESC,
  
  -- Sort by 'updated_at'
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC' 
    THEN kw.updated_at END ASC,
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC' 
    THEN kw.updated_at END DESC,
  
  -- Sort by 'deleted_at'
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC' 
    THEN kw.deleted_at END ASC,
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC' 
    THEN kw.deleted_at END DESC
LIMIT $9
OFFSET $8
`

type QueryAllKeywordsByUrlIdParams struct {
	UrlID          pgtype.UUID      `db:"url_id" json:"url_id"`
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryAllKeywordsByUrlIdRow struct {
	Keyword      Keyword `db:"keyword" json:"keyword"`
	Url          Url     `db:"url" json:"url"`
	TotalRecords int64   `db:"total_records" json:"total_records"`
}

// Date range filtering
//
//	SELECT
//	  kw.id, kw.url_id, kw.value, kw.created_at, kw.updated_at, kw.deleted_at,
//	  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at,
//	  COUNT(*) OVER() AS total_records
//	FROM keywords kw
//	JOIN urls u ON kw.url_id = u.id
//	WHERE kw.url_id = $1
//	  AND ($2::bool OR kw.deleted_at IS NULL)
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN kw.created_at
//	      WHEN $3::text = 'updated_at' THEN kw.updated_at
//	      WHEN $3::text = 'deleted_at' THEN kw.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  -- Sort by 'created_at'
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC'
//	    THEN kw.created_at END ASC,
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC'
//	    THEN kw.created_at END DESC,
//
//	  -- Sort by 'updated_at'
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC'
//	    THEN kw.updated_at END ASC,
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC'
//	    THEN kw.updated_at END DESC,
//
//	  -- Sort by 'deleted_at'
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC'
//	    THEN kw.deleted_at END ASC,
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC'
//	    THEN kw.deleted_at END DESC
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryAllKeywordsByUrlId(ctx context.Context, arg QueryAllKeywordsByUrlIdParams) ([]QueryAllKeywordsByUrlIdRow, error) {
	rows, err := q.db.Query(ctx, queryAllKeywordsByUrlId,
		arg.UrlID,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllKeywordsByUrlIdRow
	for rows.Next() {
		var i QueryAllKeywordsByUrlIdRow
		if err := rows.Scan(
			&i.Keyword.ID,
			&i.Keyword.UrlID,
			&i.Keyword.Value,
			&i.Keyword.CreatedAt,
			&i.Keyword.UpdatedAt,
			&i.Keyword.DeletedAt,
			&i.Url.ID,
			&i.Url.UserID,
			&i.Url.ShortCode,
			&i.Url.CustomAlias,
			&i.Url.OriginalUrl,
			&i.Url.StatusID,
			&i.Url.ExpiresOn,
			&i.Url.OgTitle,
			&i.Url.OgDescription,
			&i.Url.OgImageUrl,
			&i.Url.Metadata,
			&i.Url.CreatedAt,
			&i.Url.UpdatedAt,
			&i.Url.DeletedAt,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryKeywordById = `-- name: QueryKeywordById :one
SELECT 
  kw.id, kw.url_id, kw.value, kw.created_at, kw.updated_at, kw.deleted_at
FROM keywords kw
WHERE kw.id = $1
`

type QueryKeywordByIdRow struct {
	Keyword Keyword `db:"keyword" json:"keyword"`
}

// QueryKeywordById
//
//	SELECT
//	  kw.id, kw.url_id, kw.value, kw.created_at, kw.updated_at, kw.deleted_at
//	FROM keywords kw
//	WHERE kw.id = $1
func (q *Queries) QueryKeywordById(ctx context.Context, id pgtype.UUID) (QueryKeywordByIdRow, error) {
	row := q.db.QueryRow(ctx, queryKeywordById, id)
	var i QueryKeywordByIdRow
	err := row.Scan(
		&i.Keyword.ID,
		&i.Keyword.UrlID,
		&i.Keyword.Value,
		&i.Keyword.CreatedAt,
		&i.Keyword.UpdatedAt,
		&i.Keyword.DeletedAt,
	)
	return i, err
}

const queryKeywordByValue = `-- name: QueryKeywordByValue :one
SELECT 
  kw.id, kw.url_id, kw.value, kw.created_at, kw.updated_at, kw.deleted_at
FROM keywords kw
WHERE kw.value = $1 AND kw.url_id = $2
`

type QueryKeywordByValueParams struct {
	Value string      `db:"value" json:"value"`
	UrlID pgtype.UUID `db:"url_id" json:"url_id"`
}

type QueryKeywordByValueRow struct {
	Keyword Keyword `db:"keyword" json:"keyword"`
}

// QueryKeywordByValue
//
//	SELECT
//	  kw.id, kw.url_id, kw.value, kw.created_at, kw.updated_at, kw.deleted_at
//	FROM keywords kw
//	WHERE kw.value = $1 AND kw.url_id = $2
func (q *Queries) QueryKeywordByValue(ctx context.Context, arg QueryKeywordByValueParams) (QueryKeywordByValueRow, error) {
	row := q.db.QueryRow(ctx, queryKeywordByValue, arg.Value, arg.UrlID)
	var i QueryKeywordByValueRow
	err := row.Scan(
		&i.Keyword.ID,
		&i.Keyword.UrlID,
		&i.Keyword.Value,
		&i.Keyword.CreatedAt,
		&i.Keyword.UpdatedAt,
		&i.Keyword.DeletedAt,
	)
	return i, err
}
