// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresql

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type UrlStatus string

const (
	UrlStatusACTIVE    UrlStatus = "ACTIVE"
	UrlStatusSUSPENDED UrlStatus = "SUSPENDED"
	UrlStatusDELETED   UrlStatus = "DELETED"
	UrlStatusEXPIRED   UrlStatus = "EXPIRED"
)

func (e *UrlStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UrlStatus(s)
	case string:
		*e = UrlStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UrlStatus: %T", src)
	}
	return nil
}

type NullUrlStatus struct {
	UrlStatus UrlStatus `json:"url_status"`
	Valid     bool      `json:"valid"` // Valid is true if UrlStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUrlStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UrlStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UrlStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUrlStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UrlStatus), nil
}

type UserStatus string

const (
	UserStatusACTIVE    UserStatus = "ACTIVE"
	UserStatusINACTIVE  UserStatus = "INACTIVE"
	UserStatusSUSPENDED UserStatus = "SUSPENDED"
	UserStatusDELETED   UserStatus = "DELETED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

// API keys for programmatic access, associated with a user.
type ApiKey struct {
	// Primary key, generated by the application.
	ID pgtype.UUID `db:"id" json:"id"`
	// Foreign key referencing the user who owns this API key.
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	// SHA-256 hash of the raw API key for secure storage.
	KeyHash string `db:"key_hash" json:"key_hash"`
	// User-defined name for the API key.
	Name string `db:"name" json:"name"`
	// Array of scopes/permissions associated with the API key.
	Scopes []string `db:"scopes" json:"scopes"`
	// Rate limit for this API key (requests per minute).
	RateLimit int32 `db:"rate_limit" json:"rate_limit"`
	// Timestamp of the last time this API key was used.
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	// Expiration timestamp for the API key.
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type AuditTrail struct {
	ID              int64              `db:"id" json:"id"`
	SchemaName      string             `db:"schema_name" json:"schema_name"`
	TableName       string             `db:"table_name" json:"table_name"`
	Relid           pgtype.Uint32      `db:"relid" json:"relid"`
	SessionUserName pgtype.Text        `db:"session_user_name" json:"session_user_name"`
	ActionTstampTx  pgtype.Timestamptz `db:"action_tstamp_tx" json:"action_tstamp_tx"`
	ActionTstampStm pgtype.Timestamptz `db:"action_tstamp_stm" json:"action_tstamp_stm"`
	ActionTstampClk pgtype.Timestamptz `db:"action_tstamp_clk" json:"action_tstamp_clk"`
	TransactionID   pgtype.Int8        `db:"transaction_id" json:"transaction_id"`
	ApplicationName pgtype.Text        `db:"application_name" json:"application_name"`
	ClientAddr      *netip.Addr        `db:"client_addr" json:"client_addr"`
	ClientPort      pgtype.Int4        `db:"client_port" json:"client_port"`
	ClientQuery     pgtype.Text        `db:"client_query" json:"client_query"`
	Action          string             `db:"action" json:"action"`
	RowData         []byte             `db:"row_data" json:"row_data"`
	ChangedFields   []byte             `db:"changed_fields" json:"changed_fields"`
	StatementOnly   bool               `db:"statement_only" json:"statement_only"`
}

// Represents keywords/tags associated with a URL for categorization and search.
type Keyword struct {
	// Primary key, generated by the application.
	ID pgtype.UUID `db:"id" json:"id"`
	// Foreign key referencing the URL this keyword is associated with.
	UrlID pgtype.UUID `db:"url_id" json:"url_id"`
	// The keyword/tag value.
	Value string `db:"value" json:"value"`
	// Timestamp when the keyword was created.
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	// Timestamp when the keyword was last updated.
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Timestamp when the keyword was deleted (soft delete).
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type OutboxEvent struct {
	// The domain event ID, generated by the application; consumers use it to de-duplicate
	ID pgtype.UUID `db:"id" json:"id"`
	// The group ID associated with the outbox event, this is the identifier for a given consumer group handling sending out this event type
	GroupID pgtype.Text `db:"group_id" json:"group_id"`
	// The correlation ID associated with the outbox event
	CorrelationID pgtype.Text `db:"correlation_id" json:"correlation_id"`
	// Key the broker uses to order and partition messages, typically the aggregate ID. Broker-agnostic: one outbox serves every destination
	PartitionKey pgtype.Text `db:"partition_key" json:"partition_key"`
	// This is the destination of the outbox event or where it is intended to be sent
	Destination string `db:"destination" json:"destination"`
	// This is the event type of the outbox event that is going to be sent out to a given destination
	EventType string `db:"event_type" json:"event_type"`
	// This is the header in JSON format of the outgoing message that is going to be sent out to a given destination
	Headers []byte `db:"headers" json:"headers"`
	// This is the payload in JSON format that is going to be sent out to a given destination
	Payload []byte `db:"payload" json:"payload"`
	// The error message associated with the outbox event if there is a failure sending out this event/message
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
	// Additional metadata about the outbox event in JSON format
	Metadata []byte `db:"metadata" json:"metadata"`
	// When the outbox event was sent out. Null if not sent out yet
	SentTime     pgtype.Timestamptz `db:"sent_time" json:"sent_time"`
	ProcessingAt pgtype.Timestamptz `db:"processing_at" json:"processing_at"`
	// Times the broker permanently rejected this event; transient failures are not counted
	Attempts int32 `db:"attempts" json:"attempts"`
	// When the relay gave up on this event after the maximum number of attempts; null if not parked
	ParkedAt pgtype.Timestamptz `db:"parked_at" json:"parked_at"`
	// Timestamp when the outbox event was created
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	// Timestamp when the outbox event was last updated
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Timestamp when the outbox event was soft deleted, null if active
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Represents shortened URLs created by users.
type Url struct {
	// Primary key, generated by the application.
	ID pgtype.UUID `db:"id" json:"id"`
	// Foreign key referencing the user who created the URL.
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	// Unique short code for the URL, used in the shortened URL.
	ShortCode string `db:"short_code" json:"short_code"`
	// Optional custom alias for the URL, must be unique if provided.
	CustomAlias pgtype.Text `db:"custom_alias" json:"custom_alias"`
	// The original long URL that is being shortened.
	OriginalUrl string `db:"original_url" json:"original_url"`
	// Lifecycle status of the URL; only ACTIVE URLs redirect.
	Status UrlStatus `db:"status" json:"status"`
	// Timestamp when the URL expires and should no longer redirect.
	ExpiresOn pgtype.Timestamptz `db:"expires_on" json:"expires_on"`
	// Open Graph title for the URL, used for rich previews.
	OgTitle pgtype.Text `db:"og_title" json:"og_title"`
	// Open Graph description for the URL, used for rich previews.
	OgDescription pgtype.Text `db:"og_description" json:"og_description"`
	// Open Graph image URL for the URL, used for rich previews.
	OgImageUrl pgtype.Text `db:"og_image_url" json:"og_image_url"`
	// Additional metadata about the URL stored as JSON.
	Metadata []byte `db:"metadata" json:"metadata"`
	// Timestamp when the URL was created.
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	// Timestamp when the URL was last updated.
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Timestamp when the URL was deleted (soft delete).
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Represents security scan results for URLs.
type UrlScan struct {
	// Primary key, generated by the application.
	ID pgtype.UUID `db:"id" json:"id"`
	// Foreign key referencing the URL that was scanned.
	UrlID pgtype.UUID `db:"url_id" json:"url_id"`
	// The security scan provider (e.g. google_safe_browsing, virustotal).
	Provider string `db:"provider" json:"provider"`
	// The result of the scan (e.g. safe, malware, phishing, unknown).
	Result string `db:"result" json:"result"`
	// The raw JSON response from the security scan provider for auditing and debugging purposes.
	RawResponse []byte `db:"raw_response" json:"raw_response"`
	// Timestamp when the URL was scanned.
	ScannedAt pgtype.Timestamptz `db:"scanned_at" json:"scanned_at"`
	// Timestamp when the scan record was created.
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	// Timestamp when the scan record was last updated.
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Timestamp when the scan record was deleted (soft delete).
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Represents registered users of the system.
type User struct {
	// Primary key, UUID generated by the database.
	ID pgtype.UUID `db:"id" json:"id"`
	// Unique username chosen by the user.
	Username string `db:"username" json:"username"`
	// Users first name.
	FirstName pgtype.Text `db:"first_name" json:"first_name"`
	// Users last name.
	LastName pgtype.Text `db:"last_name" json:"last_name"`
	// Email address, used for login and notifications.
	Email string `db:"email" json:"email"`
	// Hashed password using bcrypt.
	PasswordHash string `db:"password_hash" json:"password_hash"`
	// Indicates if the user has verified their email.
	Verified bool `db:"verified" json:"verified"`
	// Token used for email verification.
	VerificationToken pgtype.Text `db:"verification_token" json:"verification_token"`
	// Expiration time for the verification token.
	VerificationExpires pgtype.Timestamptz `db:"verification_expires" json:"verification_expires"`
	// User account status; SUSPENDED and DELETED users may not sign in.
	Status UserStatus `db:"status" json:"status"`
	// Additional user metadata stored as JSON.
	Metadata []byte `db:"metadata" json:"metadata"`
	// Timestamp when the user account was created.
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	// Timestamp when the user account was last updated.
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Represents webhook subscriptions for URL events.
type Webhook struct {
	// Primary key, generated by the application.
	ID pgtype.UUID `db:"id" json:"id"`
	// Foreign key referencing the user who owns this webhook.
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	// Foreign key referencing the URL this webhook is associated with (NULL means it applies to all URLs).
	UrlID pgtype.UUID `db:"url_id" json:"url_id"`
	// The URL endpoint to which the webhook will send POST requests when events occur.
	Endpoint string `db:"endpoint" json:"endpoint"`
	// HMAC signing secret used to verify webhook payloads.
	Secret string `db:"secret" json:"secret"`
	// Array of event types that trigger this webhook (e.g. url.accessed, url.expired).
	Events []string `db:"events" json:"events"`
	// Indicates whether the webhook is active and should receive events.
	Active bool `db:"active" json:"active"`
	// Timestamp when the webhook was created.
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	// Timestamp when the webhook was last updated.
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Timestamp when the webhook was deleted (soft delete).
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
