// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox_relay_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryClaimOutboxEvents = `-- name: QueryClaimOutboxEvents :many
SELECT
  ranked.id,
  ranked.partition_key,
  ranked.destination,
  ranked.event_type,
  ranked.headers,
  ranked.payload,
  ranked.attempts,
  ranked.created_at
FROM (
  SELECT
    oe.id, oe.group_id, oe.correlation_id, oe.partition_key, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.attempts, oe.parked_at, oe.created_at, oe.updated_at, oe.deleted_at,
    row_number() OVER (PARTITION BY oe.destination ORDER BY oe.created_at, oe.id) AS position
  FROM outbox_events oe
  WHERE oe.sent_time IS NULL
    AND oe.parked_at IS NULL
    AND oe.deleted_at IS NULL
) ranked
WHERE ranked.position <= $1::int
ORDER BY ranked.created_at, ranked.id
`

type QueryClaimOutboxEventsRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	PartitionKey pgtype.Text        `db:"partition_key" json:"partition_key"`
	Destination  string             `db:"destination" json:"destination"`
	EventType    string             `db:"event_type" json:"event_type"`
	Headers      []byte             `db:"headers" json:"headers"`
	Payload      []byte             `db:"payload" json:"payload"`
	Attempts     int32              `db:"attempts" json:"attempts"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// The relay's batch: per destination, the oldest unsent, unparked, undeleted events in creation order, so a destination
// whose topic is unavailable cannot starve the others. The creation order is (created_at, id); id is a UUIDv7 and keeps
// the events of one transaction in the order they were recorded.
//
//	SELECT
//	  ranked.id,
//	  ranked.partition_key,
//	  ranked.destination,
//	  ranked.event_type,
//	  ranked.headers,
//	  ranked.payload,
//	  ranked.attempts,
//	  ranked.created_at
//	FROM (
//	  SELECT
//	    oe.id, oe.group_id, oe.correlation_id, oe.partition_key, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.attempts, oe.parked_at, oe.created_at, oe.updated_at, oe.deleted_at,
//	    row_number() OVER (PARTITION BY oe.destination ORDER BY oe.created_at, oe.id) AS position
//	  FROM outbox_events oe
//	  WHERE oe.sent_time IS NULL
//	    AND oe.parked_at IS NULL
//	    AND oe.deleted_at IS NULL
//	) ranked
//	WHERE ranked.position <= $1::int
//	ORDER BY ranked.created_at, ranked.id
func (q *Queries) QueryClaimOutboxEvents(ctx context.Context, perDestination int32) ([]QueryClaimOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, queryClaimOutboxEvents, perDestination)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryClaimOutboxEventsRow
	for rows.Next() {
		var i QueryClaimOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.PartitionKey,
			&i.Destination,
			&i.EventType,
			&i.Headers,
			&i.Payload,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryMarkOutboxEventsSent = `-- name: QueryMarkOutboxEventsSent :execrows
UPDATE outbox_events
SET
  sent_time = now(),
  updated_at = now()
WHERE id = ANY($1::uuid[])
  AND sent_time IS NULL
`

// QueryMarkOutboxEventsSent
//
//	UPDATE outbox_events
//	SET
//	  sent_time = now(),
//	  updated_at = now()
//	WHERE id = ANY($1::uuid[])
//	  AND sent_time IS NULL
func (q *Queries) QueryMarkOutboxEventsSent(ctx context.Context, ids []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, queryMarkOutboxEventsSent, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const queryOutboxBacklog = `-- name: QueryOutboxBacklog :one
SELECT
  count(*) FILTER (WHERE parked_at IS NULL)::bigint AS unsent,
  (min(created_at) FILTER (WHERE parked_at IS NULL))::timestamptz AS oldest_unsent,
  count(*) FILTER (WHERE parked_at IS NOT NULL)::bigint AS parked
FROM outbox_events
WHERE sent_time IS NULL
  AND deleted_at IS NULL
`

type QueryOutboxBacklogRow struct {
	Unsent       int64              `db:"unsent" json:"unsent"`
	OldestUnsent pgtype.Timestamptz `db:"oldest_unsent" json:"oldest_unsent"`
	Parked       int64              `db:"parked" json:"parked"`
}

// QueryOutboxBacklog
//
//	SELECT
//	  count(*) FILTER (WHERE parked_at IS NULL)::bigint AS unsent,
//	  (min(created_at) FILTER (WHERE parked_at IS NULL))::timestamptz AS oldest_unsent,
//	  count(*) FILTER (WHERE parked_at IS NOT NULL)::bigint AS parked
//	FROM outbox_events
//	WHERE sent_time IS NULL
//	  AND deleted_at IS NULL
func (q *Queries) QueryOutboxBacklog(ctx context.Context) (QueryOutboxBacklogRow, error) {
	row := q.db.QueryRow(ctx, queryOutboxBacklog)
	var i QueryOutboxBacklogRow
	err := row.Scan(&i.Unsent, &i.OldestUnsent, &i.Parked)
	return i, err
}

const queryParkOutboxEvent = `-- name: QueryParkOutboxEvent :exec
UPDATE outbox_events
SET
  parked_at = now(),
  error_message = $1,
  updated_at = now()
WHERE id = $2
`

type QueryParkOutboxEventParams struct {
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

// QueryParkOutboxEvent
//
//	UPDATE outbox_events
//	SET
//	  parked_at = now(),
//	  error_message = $1,
//	  updated_at = now()
//	WHERE id = $2
func (q *Queries) QueryParkOutboxEvent(ctx context.Context, arg QueryParkOutboxEventParams) error {
	_, err := q.db.Exec(ctx, queryParkOutboxEvent, arg.ErrorMessage, arg.ID)
	return err
}

const queryPurgeSentOutboxEvents = `-- name: QueryPurgeSentOutboxEvents :execrows
DELETE FROM outbox_events
WHERE id IN (
  SELECT oe.id
  FROM outbox_events oe
  WHERE oe.sent_time IS NOT NULL
    AND oe.sent_time < $1::timestamptz
  ORDER BY oe.sent_time
  LIMIT $2::int
)
`

type QueryPurgeSentOutboxEventsParams struct {
	OlderThan pgtype.Timestamptz `db:"older_than" json:"older_than"`
	LimitBy   int32              `db:"limit_by" json:"limit_by"`
}

// QueryPurgeSentOutboxEvents
//
//	DELETE FROM outbox_events
//	WHERE id IN (
//	  SELECT oe.id
//	  FROM outbox_events oe
//	  WHERE oe.sent_time IS NOT NULL
//	    AND oe.sent_time < $1::timestamptz
//	  ORDER BY oe.sent_time
//	  LIMIT $2::int
//	)
func (q *Queries) QueryPurgeSentOutboxEvents(ctx context.Context, arg QueryPurgeSentOutboxEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, queryPurgeSentOutboxEvents, arg.OlderThan, arg.LimitBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const queryRecordOutboxEventRejection = `-- name: QueryRecordOutboxEventRejection :one
UPDATE outbox_events
SET
  attempts = attempts + 1,
  error_message = $1,
  updated_at = now()
WHERE id = $2
RETURNING attempts
`

type QueryRecordOutboxEventRejectionParams struct {
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

// QueryRecordOutboxEventRejection
//
//	UPDATE outbox_events
//	SET
//	  attempts = attempts + 1,
//	  error_message = $1,
//	  updated_at = now()
//	WHERE id = $2
//	RETURNING attempts
func (q *Queries) QueryRecordOutboxEventRejection(ctx context.Context, arg QueryRecordOutboxEventRejectionParams) (int32, error) {
	row := q.db.QueryRow(ctx, queryRecordOutboxEventRejection, arg.ErrorMessage, arg.ID)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}
