// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: outbox_read_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryAllOutboxEvents = `-- name: QueryAllOutboxEvents :many
SELECT
  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
FROM outbox_events oe
WHERE $1::bool OR oe.deleted_at IS NULL
AND (
  $2::text IS NULL
  OR $3::timestamp IS NULL
  OR $4::timestamp IS NULL
  OR (
    CASE 
      WHEN $2::text = 'created_at' THEN oe.created_at
      WHEN $2::text = 'updated_at' THEN oe.updated_at
      WHEN $2::text = 'deleted_at' THEN oe.deleted_at
    END BETWEEN $3::timestamp AND $4::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $5::text = 'created_at' THEN oe.created_at 
    WHEN $5::text = 'updated_at' THEN oe.updated_at 
    WHEN $5::text = 'deleted_at' THEN oe.deleted_at 
END,
  CASE
    WHEN $6::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $8
OFFSET $7
`

type QueryAllOutboxEventsParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryAllOutboxEventsRow struct {
	OutboxEvent OutboxEvent `db:"outbox_event" json:"outbox_event"`
}

// Date range filtering
//
//	SELECT
//	  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
//	FROM outbox_events oe
//	WHERE $1::bool OR oe.deleted_at IS NULL
//	AND (
//	  $2::text IS NULL
//	  OR $3::timestamp IS NULL
//	  OR $4::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $2::text = 'created_at' THEN oe.created_at
//	      WHEN $2::text = 'updated_at' THEN oe.updated_at
//	      WHEN $2::text = 'deleted_at' THEN oe.deleted_at
//	    END BETWEEN $3::timestamp AND $4::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $5::text = 'created_at' THEN oe.created_at
//	    WHEN $5::text = 'updated_at' THEN oe.updated_at
//	    WHEN $5::text = 'deleted_at' THEN oe.deleted_at
//	END,
//	  CASE
//	    WHEN $6::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $8
//	OFFSET $7
func (q *Queries) QueryAllOutboxEvents(ctx context.Context, arg QueryAllOutboxEventsParams) ([]QueryAllOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, queryAllOutboxEvents,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllOutboxEventsRow
	for rows.Next() {
		var i QueryAllOutboxEventsRow
		if err := rows.Scan(
			&i.OutboxEvent.ID,
			&i.OutboxEvent.GroupID,
			&i.OutboxEvent.CorrelationID,
			&i.OutboxEvent.Destination,
			&i.OutboxEvent.EventType,
			&i.OutboxEvent.Headers,
			&i.OutboxEvent.Payload,
			&i.OutboxEvent.ErrorMessage,
			&i.OutboxEvent.Metadata,
			&i.OutboxEvent.SentTime,
			&i.OutboxEvent.ProcessingAt,
			&i.OutboxEvent.CreatedAt,
			&i.OutboxEvent.UpdatedAt,
			&i.OutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAllOutboxEventsCount = `-- name: QueryAllOutboxEventsCount :one
SELECT
  count(*)
FROM outbox_events oe
WHERE $1::bool OR oe.deleted_at IS NULL
`

// QueryAllOutboxEventsCount
//
//	SELECT
//	  count(*)
//	FROM outbox_events oe
//	WHERE $1::bool OR oe.deleted_at IS NULL
func (q *Queries) QueryAllOutboxEventsCount(ctx context.Context, includeDeleted bool) (int64, error) {
	row := q.db.QueryRow(ctx, queryAllOutboxEventsCount, includeDeleted)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const queryOutboxEventByCorrelationId = `-- name: QueryOutboxEventByCorrelationId :one
SELECT
  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
FROM outbox_events oe
WHERE oe.correlation_id = $1
`

type QueryOutboxEventByCorrelationIdRow struct {
	OutboxEvent OutboxEvent `db:"outbox_event" json:"outbox_event"`
}

// QueryOutboxEventByCorrelationId
//
//	SELECT
//	  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
//	FROM outbox_events oe
//	WHERE oe.correlation_id = $1
func (q *Queries) QueryOutboxEventByCorrelationId(ctx context.Context, correlationID pgtype.Text) (QueryOutboxEventByCorrelationIdRow, error) {
	row := q.db.QueryRow(ctx, queryOutboxEventByCorrelationId, correlationID)
	var i QueryOutboxEventByCorrelationIdRow
	err := row.Scan(
		&i.OutboxEvent.ID,
		&i.OutboxEvent.GroupID,
		&i.OutboxEvent.CorrelationID,
		&i.OutboxEvent.Destination,
		&i.OutboxEvent.EventType,
		&i.OutboxEvent.Headers,
		&i.OutboxEvent.Payload,
		&i.OutboxEvent.ErrorMessage,
		&i.OutboxEvent.Metadata,
		&i.OutboxEvent.SentTime,
		&i.OutboxEvent.ProcessingAt,
		&i.OutboxEvent.CreatedAt,
		&i.OutboxEvent.UpdatedAt,
		&i.OutboxEvent.DeletedAt,
	)
	return i, err
}

const queryOutboxEventById = `-- name: QueryOutboxEventById :one
SELECT
  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
FROM outbox_events oe
WHERE oe.id = $1
`

type QueryOutboxEventByIdRow struct {
	OutboxEvent OutboxEvent `db:"outbox_event" json:"outbox_event"`
}

// QueryOutboxEventById
//
//	SELECT
//	  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
//	FROM outbox_events oe
//	WHERE oe.id = $1
func (q *Queries) QueryOutboxEventById(ctx context.Context, id pgtype.UUID) (QueryOutboxEventByIdRow, error) {
	row := q.db.QueryRow(ctx, queryOutboxEventById, id)
	var i QueryOutboxEventByIdRow
	err := row.Scan(
		&i.OutboxEvent.ID,
		&i.OutboxEvent.GroupID,
		&i.OutboxEvent.CorrelationID,
		&i.OutboxEvent.Destination,
		&i.OutboxEvent.EventType,
		&i.OutboxEvent.Headers,
		&i.OutboxEvent.Payload,
		&i.OutboxEvent.ErrorMessage,
		&i.OutboxEvent.Metadata,
		&i.OutboxEvent.SentTime,
		&i.OutboxEvent.ProcessingAt,
		&i.OutboxEvent.CreatedAt,
		&i.OutboxEvent.UpdatedAt,
		&i.OutboxEvent.DeletedAt,
	)
	return i, err
}

const queryOutboxEventsByDestination = `-- name: QueryOutboxEventsByDestination :many
SELECT
  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
FROM outbox_events oe
WHERE $2::bool OR oe.deleted_at IS NULL
AND oe.destination = $1
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN oe.created_at
      WHEN $3::text = 'updated_at' THEN oe.updated_at
      WHEN $3::text = 'deleted_at' THEN oe.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $6::text = 'created_at' THEN oe.created_at 
    WHEN $6::text = 'updated_at' THEN oe.updated_at 
    WHEN $6::text = 'deleted_at' THEN oe.deleted_at 
END,
  CASE
    WHEN $7::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $9
OFFSET $8
`

type QueryOutboxEventsByDestinationParams struct {
	Destination    string           `db:"destination" json:"destination"`
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryOutboxEventsByDestinationRow struct {
	OutboxEvent OutboxEvent `db:"outbox_event" json:"outbox_event"`
}

// Date range filtering
//
//	SELECT
//	  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
//	FROM outbox_events oe
//	WHERE $2::bool OR oe.deleted_at IS NULL
//	AND oe.destination = $1
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN oe.created_at
//	      WHEN $3::text = 'updated_at' THEN oe.updated_at
//	      WHEN $3::text = 'deleted_at' THEN oe.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $6::text = 'created_at' THEN oe.created_at
//	    WHEN $6::text = 'updated_at' THEN oe.updated_at
//	    WHEN $6::text = 'deleted_at' THEN oe.deleted_at
//	END,
//	  CASE
//	    WHEN $7::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryOutboxEventsByDestination(ctx context.Context, arg QueryOutboxEventsByDestinationParams) ([]QueryOutboxEventsByDestinationRow, error) {
	rows, err := q.db.Query(ctx, queryOutboxEventsByDestination,
		arg.Destination,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryOutboxEventsByDestinationRow
	for rows.Next() {
		var i QueryOutboxEventsByDestinationRow
		if err := rows.Scan(
			&i.OutboxEvent.ID,
			&i.OutboxEvent.GroupID,
			&i.OutboxEvent.CorrelationID,
			&i.OutboxEvent.Destination,
			&i.OutboxEvent.EventType,
			&i.OutboxEvent.Headers,
			&i.OutboxEvent.Payload,
			&i.OutboxEvent.ErrorMessage,
			&i.OutboxEvent.Metadata,
			&i.OutboxEvent.SentTime,
			&i.OutboxEvent.ProcessingAt,
			&i.OutboxEvent.CreatedAt,
			&i.OutboxEvent.UpdatedAt,
			&i.OutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryOutboxEventsByEventType = `-- name: QueryOutboxEventsByEventType :many
SELECT
  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
FROM outbox_events oe
WHERE $2::bool OR oe.deleted_at IS NULL
AND oe.event_type = $1
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN oe.created_at
      WHEN $3::text = 'updated_at' THEN oe.updated_at
      WHEN $3::text = 'deleted_at' THEN oe.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $6::text = 'created_at' THEN oe.created_at 
    WHEN $6::text = 'updated_at' THEN oe.updated_at 
    WHEN $6::text = 'deleted_at' THEN oe.deleted_at 
END,
  CASE
    WHEN $7::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $9
OFFSET $8
`

type QueryOutboxEventsByEventTypeParams struct {
	EventType      string           `db:"event_type" json:"event_type"`
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryOutboxEventsByEventTypeRow struct {
	OutboxEvent OutboxEvent `db:"outbox_event" json:"outbox_event"`
}

// Date range filtering
//
//	SELECT
//	  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
//	FROM outbox_events oe
//	WHERE $2::bool OR oe.deleted_at IS NULL
//	AND oe.event_type = $1
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN oe.created_at
//	      WHEN $3::text = 'updated_at' THEN oe.updated_at
//	      WHEN $3::text = 'deleted_at' THEN oe.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $6::text = 'created_at' THEN oe.created_at
//	    WHEN $6::text = 'updated_at' THEN oe.updated_at
//	    WHEN $6::text = 'deleted_at' THEN oe.deleted_at
//	END,
//	  CASE
//	    WHEN $7::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryOutboxEventsByEventType(ctx context.Context, arg QueryOutboxEventsByEventTypeParams) ([]QueryOutboxEventsByEventTypeRow, error) {
	rows, err := q.db.Query(ctx, queryOutboxEventsByEventType,
		arg.EventType,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryOutboxEventsByEventTypeRow
	for rows.Next() {
		var i QueryOutboxEventsByEventTypeRow
		if err := rows.Scan(
			&i.OutboxEvent.ID,
			&i.OutboxEvent.GroupID,
			&i.OutboxEvent.CorrelationID,
			&i.OutboxEvent.Destination,
			&i.OutboxEvent.EventType,
			&i.OutboxEvent.Headers,
			&i.OutboxEvent.Payload,
			&i.OutboxEvent.ErrorMessage,
			&i.OutboxEvent.Metadata,
			&i.OutboxEvent.SentTime,
			&i.OutboxEvent.ProcessingAt,
			&i.OutboxEvent.CreatedAt,
			&i.OutboxEvent.UpdatedAt,
			&i.OutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryOutboxEventsByGroupId = `-- name: QueryOutboxEventsByGroupId :many
SELECT
  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
FROM outbox_events oe
WHERE $1::bool OR oe.deleted_at IS NULL
AND oe.group_id = $2
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN oe.created_at
      WHEN $3::text = 'updated_at' THEN oe.updated_at
      WHEN $3::text = 'deleted_at' THEN oe.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $6::text = 'created_at' THEN oe.created_at 
    WHEN $6::text = 'updated_at' THEN oe.updated_at 
    WHEN $6::text = 'deleted_at' THEN oe.deleted_at 
END,
  CASE
    WHEN $7::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $9
OFFSET $8
`

type QueryOutboxEventsByGroupIdParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	GroupID        pgtype.Text      `db:"group_id" json:"group_id"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryOutboxEventsByGroupIdRow struct {
	OutboxEvent OutboxEvent `db:"outbox_event" json:"outbox_event"`
}

// Date range filtering
//
//	SELECT
//	  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
//	FROM outbox_events oe
//	WHERE $1::bool OR oe.deleted_at IS NULL
//	AND oe.group_id = $2
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN oe.created_at
//	      WHEN $3::text = 'updated_at' THEN oe.updated_at
//	      WHEN $3::text = 'deleted_at' THEN oe.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $6::text = 'created_at' THEN oe.created_at
//	    WHEN $6::text = 'updated_at' THEN oe.updated_at
//	    WHEN $6::text = 'deleted_at' THEN oe.deleted_at
//	END,
//	  CASE
//	    WHEN $7::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryOutboxEventsByGroupId(ctx context.Context, arg QueryOutboxEventsByGroupIdParams) ([]QueryOutboxEventsByGroupIdRow, error) {
	rows, err := q.db.Query(ctx, queryOutboxEventsByGroupId,
		arg.IncludeDeleted,
		arg.GroupID,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryOutboxEventsByGroupIdRow
	for rows.Next() {
		var i QueryOutboxEventsByGroupIdRow
		if err := rows.Scan(
			&i.OutboxEvent.ID,
			&i.OutboxEvent.GroupID,
			&i.OutboxEvent.CorrelationID,
			&i.OutboxEvent.Destination,
			&i.OutboxEvent.EventType,
			&i.OutboxEvent.Headers,
			&i.OutboxEvent.Payload,
			&i.OutboxEvent.ErrorMessage,
			&i.OutboxEvent.Metadata,
			&i.OutboxEvent.SentTime,
			&i.OutboxEvent.ProcessingAt,
			&i.OutboxEvent.CreatedAt,
			&i.OutboxEvent.UpdatedAt,
			&i.OutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryOutboxEventsSent = `-- name: QueryOutboxEventsSent :many
SELECT
  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
FROM outbox_events oe
WHERE $1::bool OR oe.deleted_at IS NULL
AND oe.sent_time IS NOT NULL
AND (
  $2::text IS NULL
  OR $3::timestamp IS NULL
  OR $4::timestamp IS NULL
  OR (
    CASE 
      WHEN $2::text = 'created_at' THEN oe.created_at
      WHEN $2::text = 'updated_at' THEN oe.updated_at
      WHEN $2::text = 'deleted_at' THEN oe.deleted_at
    END BETWEEN $3::timestamp AND $4::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $5::text = 'created_at' THEN oe.created_at 
    WHEN $5::text = 'updated_at' THEN oe.updated_at 
    WHEN $5::text = 'deleted_at' THEN oe.deleted_at 
END,
  CASE
    WHEN $6::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $8
OFFSET $7
`

type QueryOutboxEventsSentParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryOutboxEventsSentRow struct {
	OutboxEvent OutboxEvent `db:"outbox_event" json:"outbox_event"`
}

// Date range filtering
//
//	SELECT
//	  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
//	FROM outbox_events oe
//	WHERE $1::bool OR oe.deleted_at IS NULL
//	AND oe.sent_time IS NOT NULL
//	AND (
//	  $2::text IS NULL
//	  OR $3::timestamp IS NULL
//	  OR $4::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $2::text = 'created_at' THEN oe.created_at
//	      WHEN $2::text = 'updated_at' THEN oe.updated_at
//	      WHEN $2::text = 'deleted_at' THEN oe.deleted_at
//	    END BETWEEN $3::timestamp AND $4::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $5::text = 'created_at' THEN oe.created_at
//	    WHEN $5::text = 'updated_at' THEN oe.updated_at
//	    WHEN $5::text = 'deleted_at' THEN oe.deleted_at
//	END,
//	  CASE
//	    WHEN $6::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $8
//	OFFSET $7
func (q *Queries) QueryOutboxEventsSent(ctx context.Context, arg QueryOutboxEventsSentParams) ([]QueryOutboxEventsSentRow, error) {
	rows, err := q.db.Query(ctx, queryOutboxEventsSent,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryOutboxEventsSentRow
	for rows.Next() {
		var i QueryOutboxEventsSentRow
		if err := rows.Scan(
			&i.OutboxEvent.ID,
			&i.OutboxEvent.GroupID,
			&i.OutboxEvent.CorrelationID,
			&i.OutboxEvent.Destination,
			&i.OutboxEvent.EventType,
			&i.OutboxEvent.Headers,
			&i.OutboxEvent.Payload,
			&i.OutboxEvent.ErrorMessage,
			&i.OutboxEvent.Metadata,
			&i.OutboxEvent.SentTime,
			&i.OutboxEvent.ProcessingAt,
			&i.OutboxEvent.CreatedAt,
			&i.OutboxEvent.UpdatedAt,
			&i.OutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryOutboxEventsSentForUpdate = `-- name: QueryOutboxEventsSentForUpdate :many
SELECT
  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
FROM outbox_events oe
WHERE $1::bool OR oe.deleted_at IS NULL
AND oe.sent_time IS NOT NULL
AND (
  $2::text IS NULL
  OR $3::timestamp IS NULL
  OR $4::timestamp IS NULL
  OR (
    CASE 
      WHEN $2::text = 'created_at' THEN oe.created_at
      WHEN $2::text = 'updated_at' THEN oe.updated_at
      WHEN $2::text = 'deleted_at' THEN oe.deleted_at
    END BETWEEN $3::timestamp AND $4::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $5::text = 'created_at' THEN oe.created_at 
    WHEN $5::text = 'updated_at' THEN oe.updated_at 
    WHEN $5::text = 'deleted_at' THEN oe.deleted_at 
END,
  CASE
    WHEN $6::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $8
OFFSET $7
`

type QueryOutboxEventsSentForUpdateParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryOutboxEventsSentForUpdateRow struct {
	OutboxEvent OutboxEvent `db:"outbox_event" json:"outbox_event"`
}

// Date range filtering
//
//	SELECT
//	  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
//	FROM outbox_events oe
//	WHERE $1::bool OR oe.deleted_at IS NULL
//	AND oe.sent_time IS NOT NULL
//	AND (
//	  $2::text IS NULL
//	  OR $3::timestamp IS NULL
//	  OR $4::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $2::text = 'created_at' THEN oe.created_at
//	      WHEN $2::text = 'updated_at' THEN oe.updated_at
//	      WHEN $2::text = 'deleted_at' THEN oe.deleted_at
//	    END BETWEEN $3::timestamp AND $4::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $5::text = 'created_at' THEN oe.created_at
//	    WHEN $5::text = 'updated_at' THEN oe.updated_at
//	    WHEN $5::text = 'deleted_at' THEN oe.deleted_at
//	END,
//	  CASE
//	    WHEN $6::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $8
//	OFFSET $7
func (q *Queries) QueryOutboxEventsSentForUpdate(ctx context.Context, arg QueryOutboxEventsSentForUpdateParams) ([]QueryOutboxEventsSentForUpdateRow, error) {
	rows, err := q.db.Query(ctx, queryOutboxEventsSentForUpdate,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryOutboxEventsSentForUpdateRow
	for rows.Next() {
		var i QueryOutboxEventsSentForUpdateRow
		if err := rows.Scan(
			&i.OutboxEvent.ID,
			&i.OutboxEvent.GroupID,
			&i.OutboxEvent.CorrelationID,
			&i.OutboxEvent.Destination,
			&i.OutboxEvent.EventType,
			&i.OutboxEvent.Headers,
			&i.OutboxEvent.Payload,
			&i.OutboxEvent.ErrorMessage,
			&i.OutboxEvent.Metadata,
			&i.OutboxEvent.SentTime,
			&i.OutboxEvent.ProcessingAt,
			&i.OutboxEvent.CreatedAt,
			&i.OutboxEvent.UpdatedAt,
			&i.OutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryOutboxEventsUnSent = `-- name: QueryOutboxEventsUnSent :many
SELECT
  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
FROM outbox_events oe
WHERE $1::bool OR oe.deleted_at IS NULL
AND oe.sent_time IS NULL
AND (oe.metadata IS NULL OR oe.metadata::text = 'null' OR (oe.metadata ->> 'failure_reason') IS NULL)
AND (
  $2::text IS NULL
  OR $3::timestamp IS NULL
  OR $4::timestamp IS NULL
  OR (
    CASE 
      WHEN $2::text = 'created_at' THEN oe.created_at
      WHEN $2::text = 'updated_at' THEN oe.updated_at
      WHEN $2::text = 'deleted_at' THEN oe.deleted_at
    END BETWEEN $3::timestamp AND $4::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $5::text = 'created_at' THEN oe.created_at 
    WHEN $5::text = 'updated_at' THEN oe.updated_at 
    WHEN $5::text = 'deleted_at' THEN oe.deleted_at 
END,
  CASE
    WHEN $6::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $8
OFFSET $7
`

type QueryOutboxEventsUnSentParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryOutboxEventsUnSentRow struct {
	OutboxEvent OutboxEvent `db:"outbox_event" json:"outbox_event"`
}

// Safely check for failure_reason
// AND (
//
//	oe.metadata IS NULL
//	OR oe.metadata::text = 'null'
//	OR (oe.metadata IS NOT NULL AND oe.metadata::text != 'null' AND NOT (oe.metadata ? 'failure_reason'))
//
// )
// Date range filtering
//
//	SELECT
//	  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
//	FROM outbox_events oe
//	WHERE $1::bool OR oe.deleted_at IS NULL
//	AND oe.sent_time IS NULL
//	AND (oe.metadata IS NULL OR oe.metadata::text = 'null' OR (oe.metadata ->> 'failure_reason') IS NULL)
//	AND (
//	  $2::text IS NULL
//	  OR $3::timestamp IS NULL
//	  OR $4::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $2::text = 'created_at' THEN oe.created_at
//	      WHEN $2::text = 'updated_at' THEN oe.updated_at
//	      WHEN $2::text = 'deleted_at' THEN oe.deleted_at
//	    END BETWEEN $3::timestamp AND $4::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $5::text = 'created_at' THEN oe.created_at
//	    WHEN $5::text = 'updated_at' THEN oe.updated_at
//	    WHEN $5::text = 'deleted_at' THEN oe.deleted_at
//	END,
//	  CASE
//	    WHEN $6::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $8
//	OFFSET $7
func (q *Queries) QueryOutboxEventsUnSent(ctx context.Context, arg QueryOutboxEventsUnSentParams) ([]QueryOutboxEventsUnSentRow, error) {
	rows, err := q.db.Query(ctx, queryOutboxEventsUnSent,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryOutboxEventsUnSentRow
	for rows.Next() {
		var i QueryOutboxEventsUnSentRow
		if err := rows.Scan(
			&i.OutboxEvent.ID,
			&i.OutboxEvent.GroupID,
			&i.OutboxEvent.CorrelationID,
			&i.OutboxEvent.Destination,
			&i.OutboxEvent.EventType,
			&i.OutboxEvent.Headers,
			&i.OutboxEvent.Payload,
			&i.OutboxEvent.ErrorMessage,
			&i.OutboxEvent.Metadata,
			&i.OutboxEvent.SentTime,
			&i.OutboxEvent.ProcessingAt,
			&i.OutboxEvent.CreatedAt,
			&i.OutboxEvent.UpdatedAt,
			&i.OutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryOutboxEventsUnSentByDestination = `-- name: QueryOutboxEventsUnSentByDestination :many
SELECT
  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
FROM outbox_events oe
WHERE $1::bool OR oe.deleted_at IS NULL
AND $2 = oe.destination
AND oe.sent_time IS NULL
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN oe.created_at
      WHEN $3::text = 'updated_at' THEN oe.updated_at
      WHEN $3::text = 'deleted_at' THEN oe.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $6::text = 'created_at' THEN oe.created_at 
    WHEN $6::text = 'updated_at' THEN oe.updated_at 
    WHEN $6::text = 'deleted_at' THEN oe.deleted_at 
END,
  CASE
    WHEN $7::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $9
OFFSET $8
`

type QueryOutboxEventsUnSentByDestinationParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	Destination    string           `db:"destination" json:"destination"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryOutboxEventsUnSentByDestinationRow struct {
	OutboxEvent OutboxEvent `db:"outbox_event" json:"outbox_event"`
}

// Date range filtering
//
//	SELECT
//	  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
//	FROM outbox_events oe
//	WHERE $1::bool OR oe.deleted_at IS NULL
//	AND $2 = oe.destination
//	AND oe.sent_time IS NULL
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN oe.created_at
//	      WHEN $3::text = 'updated_at' THEN oe.updated_at
//	      WHEN $3::text = 'deleted_at' THEN oe.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $6::text = 'created_at' THEN oe.created_at
//	    WHEN $6::text = 'updated_at' THEN oe.updated_at
//	    WHEN $6::text = 'deleted_at' THEN oe.deleted_at
//	END,
//	  CASE
//	    WHEN $7::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryOutboxEventsUnSentByDestination(ctx context.Context, arg QueryOutboxEventsUnSentByDestinationParams) ([]QueryOutboxEventsUnSentByDestinationRow, error) {
	rows, err := q.db.Query(ctx, queryOutboxEventsUnSentByDestination,
		arg.IncludeDeleted,
		arg.Destination,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryOutboxEventsUnSentByDestinationRow
	for rows.Next() {
		var i QueryOutboxEventsUnSentByDestinationRow
		if err := rows.Scan(
			&i.OutboxEvent.ID,
			&i.OutboxEvent.GroupID,
			&i.OutboxEvent.CorrelationID,
			&i.OutboxEvent.Destination,
			&i.OutboxEvent.EventType,
			&i.OutboxEvent.Headers,
			&i.OutboxEvent.Payload,
			&i.OutboxEvent.ErrorMessage,
			&i.OutboxEvent.Metadata,
			&i.OutboxEvent.SentTime,
			&i.OutboxEvent.ProcessingAt,
			&i.OutboxEvent.CreatedAt,
			&i.OutboxEvent.UpdatedAt,
			&i.OutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryOutboxEventsUnSentByDestinationWithLock = `-- name: QueryOutboxEventsUnSentByDestinationWithLock :many
SELECT
  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
FROM outbox_events oe
WHERE $1::bool OR oe.deleted_at IS NULL
AND $2 = oe.destination
AND oe.sent_time IS NULL
AND (oe.metadata IS NULL OR oe.metadata::text = 'null' OR (oe.metadata ->> 'failure_reason') IS NULL)
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN oe.created_at
      WHEN $3::text = 'updated_at' THEN oe.updated_at
      WHEN $3::text = 'deleted_at' THEN oe.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  CASE 
    WHEN $6::text = 'created_at' THEN oe.created_at 
    WHEN $6::text = 'updated_at' THEN oe.updated_at 
    WHEN $6::text = 'deleted_at' THEN oe.deleted_at 
END,
  CASE
    WHEN $7::text='ASC' THEN 'ASC'
    ELSE 'DESC'
END
LIMIT $9
OFFSET $8
FOR UPDATE SKIP LOCKED
`

type QueryOutboxEventsUnSentByDestinationWithLockParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	Destination    string           `db:"destination" json:"destination"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryOutboxEventsUnSentByDestinationWithLockRow struct {
	OutboxEvent OutboxEvent `db:"outbox_event" json:"outbox_event"`
}

// Safely check for failure_reason
// AND (
//
//	oe.metadata IS NULL
//	OR oe.metadata::text = 'null'
//	OR (oe.metadata IS NOT NULL AND oe.metadata::text != 'null' AND NOT (oe.metadata ? 'failure_reason'))
//
// )
// Date range filtering
//
//	SELECT
//	  oe.id, oe.group_id, oe.correlation_id, oe.destination, oe.event_type, oe.headers, oe.payload, oe.error_message, oe.metadata, oe.sent_time, oe.processing_at, oe.created_at, oe.updated_at, oe.deleted_at
//	FROM outbox_events oe
//	WHERE $1::bool OR oe.deleted_at IS NULL
//	AND $2 = oe.destination
//	AND oe.sent_time IS NULL
//	AND (oe.metadata IS NULL OR oe.metadata::text = 'null' OR (oe.metadata ->> 'failure_reason') IS NULL)
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN oe.created_at
//	      WHEN $3::text = 'updated_at' THEN oe.updated_at
//	      WHEN $3::text = 'deleted_at' THEN oe.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  CASE
//	    WHEN $6::text = 'created_at' THEN oe.created_at
//	    WHEN $6::text = 'updated_at' THEN oe.updated_at
//	    WHEN $6::text = 'deleted_at' THEN oe.deleted_at
//	END,
//	  CASE
//	    WHEN $7::text='ASC' THEN 'ASC'
//	    ELSE 'DESC'
//	END
//	LIMIT $9
//	OFFSET $8
//	FOR UPDATE SKIP LOCKED
func (q *Queries) QueryOutboxEventsUnSentByDestinationWithLock(ctx context.Context, arg QueryOutboxEventsUnSentByDestinationWithLockParams) ([]QueryOutboxEventsUnSentByDestinationWithLockRow, error) {
	rows, err := q.db.Query(ctx, queryOutboxEventsUnSentByDestinationWithLock,
		arg.IncludeDeleted,
		arg.Destination,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryOutboxEventsUnSentByDestinationWithLockRow
	for rows.Next() {
		var i QueryOutboxEventsUnSentByDestinationWithLockRow
		if err := rows.Scan(
			&i.OutboxEvent.ID,
			&i.OutboxEvent.GroupID,
			&i.OutboxEvent.CorrelationID,
			&i.OutboxEvent.Destination,
			&i.OutboxEvent.EventType,
			&i.OutboxEvent.Headers,
			&i.OutboxEvent.Payload,
			&i.OutboxEvent.ErrorMessage,
			&i.OutboxEvent.Metadata,
			&i.OutboxEvent.SentTime,
			&i.OutboxEvent.ProcessingAt,
			&i.OutboxEvent.CreatedAt,
			&i.OutboxEvent.UpdatedAt,
			&i.OutboxEvent.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
