// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: outbox_write_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryCreateOutboxEvent = `-- name: QueryCreateOutboxEvent :one
INSERT INTO 
  outbox_events (
    group_id,
    correlation_id,
    destination,
    event_type,
    headers,
    payload,
    error_message,
    metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
`

type QueryCreateOutboxEventParams struct {
	GroupID       pgtype.Text `db:"group_id" json:"group_id"`
	CorrelationID pgtype.Text `db:"correlation_id" json:"correlation_id"`
	Destination   string      `db:"destination" json:"destination"`
	EventType     string      `db:"event_type" json:"event_type"`
	Headers       []byte      `db:"headers" json:"headers"`
	Payload       []byte      `db:"payload" json:"payload"`
	ErrorMessage  pgtype.Text `db:"error_message" json:"error_message"`
	Metadata      []byte      `db:"metadata" json:"metadata"`
}

// QueryCreateOutboxEvent
//
//	INSERT INTO
//	  outbox_events (
//	    group_id,
//	    correlation_id,
//	    destination,
//	    event_type,
//	    headers,
//	    payload,
//	    error_message,
//	    metadata
//	) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
func (q *Queries) QueryCreateOutboxEvent(ctx context.Context, arg QueryCreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, queryCreateOutboxEvent,
		arg.GroupID,
		arg.CorrelationID,
		arg.Destination,
		arg.EventType,
		arg.Headers,
		arg.Payload,
		arg.ErrorMessage,
		arg.Metadata,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CorrelationID,
		&i.Destination,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.ProcessingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryDeleteOutboxEvent = `-- name: QueryDeleteOutboxEvent :one
DELETE FROM outbox_events WHERE id = $1 RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
`

// QueryDeleteOutboxEvent
//
//	DELETE FROM outbox_events WHERE id = $1 RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
func (q *Queries) QueryDeleteOutboxEvent(ctx context.Context, id pgtype.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, queryDeleteOutboxEvent, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CorrelationID,
		&i.Destination,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.ProcessingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryMarkOutboxEventAsPermanentlyFailed = `-- name: QueryMarkOutboxEventAsPermanentlyFailed :one
UPDATE outbox_events
SET
  metadata = COALESCE(
    NULLIF(metadata::text, 'null')::jsonb,
    '{}'::jsonb
  ) || jsonb_build_object('failure_reason', 'PERMANENTLY_FAILED'),
  updated_at = now(),
  deleted_at = now()
WHERE id = $1 
RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
`

// QueryMarkOutboxEventAsPermanentlyFailed
//
//	UPDATE outbox_events
//	SET
//	  metadata = COALESCE(
//	    NULLIF(metadata::text, 'null')::jsonb,
//	    '{}'::jsonb
//	  ) || jsonb_build_object('failure_reason', 'PERMANENTLY_FAILED'),
//	  updated_at = now(),
//	  deleted_at = now()
//	WHERE id = $1
//	RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
func (q *Queries) QueryMarkOutboxEventAsPermanentlyFailed(ctx context.Context, id pgtype.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, queryMarkOutboxEventAsPermanentlyFailed, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CorrelationID,
		&i.Destination,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.ProcessingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryMarkOutboxEventAsSent = `-- name: QueryMarkOutboxEventAsSent :one
UPDATE outbox_events
SET
  sent_time=$2,
  updated_at=now()
WHERE id = $1 RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
`

type QueryMarkOutboxEventAsSentParams struct {
	ID       pgtype.UUID        `db:"id" json:"id"`
	SentTime pgtype.Timestamptz `db:"sent_time" json:"sent_time"`
}

// QueryMarkOutboxEventAsSent
//
//	UPDATE outbox_events
//	SET
//	  sent_time=$2,
//	  updated_at=now()
//	WHERE id = $1 RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
func (q *Queries) QueryMarkOutboxEventAsSent(ctx context.Context, arg QueryMarkOutboxEventAsSentParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, queryMarkOutboxEventAsSent, arg.ID, arg.SentTime)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CorrelationID,
		&i.Destination,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.ProcessingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const querySoftDeleteOutboxEvent = `-- name: QuerySoftDeleteOutboxEvent :one
UPDATE outbox_events
SET
  deleted_at = $2,
  updated_at=now()
WHERE id = $1 RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
`

type QuerySoftDeleteOutboxEventParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// QuerySoftDeleteOutboxEvent
//
//	UPDATE outbox_events
//	SET
//	  deleted_at = $2,
//	  updated_at=now()
//	WHERE id = $1 RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
func (q *Queries) QuerySoftDeleteOutboxEvent(ctx context.Context, arg QuerySoftDeleteOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, querySoftDeleteOutboxEvent, arg.ID, arg.DeletedAt)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CorrelationID,
		&i.Destination,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.ProcessingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateOutboxEvent = `-- name: QueryUpdateOutboxEvent :one
UPDATE outbox_events AS oe
SET
  error_message=$2,
  sent_time=$3,
  destination=$4,
  updated_at=now()
WHERE oe.id = $1 RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
`

type QueryUpdateOutboxEventParams struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	ErrorMessage pgtype.Text        `db:"error_message" json:"error_message"`
	SentTime     pgtype.Timestamptz `db:"sent_time" json:"sent_time"`
	Destination  string             `db:"destination" json:"destination"`
}

// QueryUpdateOutboxEvent
//
//	UPDATE outbox_events AS oe
//	SET
//	  error_message=$2,
//	  sent_time=$3,
//	  destination=$4,
//	  updated_at=now()
//	WHERE oe.id = $1 RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateOutboxEvent(ctx context.Context, arg QueryUpdateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, queryUpdateOutboxEvent,
		arg.ID,
		arg.ErrorMessage,
		arg.SentTime,
		arg.Destination,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CorrelationID,
		&i.Destination,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.ProcessingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateOutboxEventAsProcessing = `-- name: QueryUpdateOutboxEventAsProcessing :one
UPDATE outbox_events
SET
  processing_at=$2,
  updated_at=now()
WHERE id = $1 RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
`

type QueryUpdateOutboxEventAsProcessingParams struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	ProcessingAt pgtype.Timestamptz `db:"processing_at" json:"processing_at"`
}

// QueryUpdateOutboxEventAsProcessing
//
//	UPDATE outbox_events
//	SET
//	  processing_at=$2,
//	  updated_at=now()
//	WHERE id = $1 RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateOutboxEventAsProcessing(ctx context.Context, arg QueryUpdateOutboxEventAsProcessingParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, queryUpdateOutboxEventAsProcessing, arg.ID, arg.ProcessingAt)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CorrelationID,
		&i.Destination,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.ProcessingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateOutboxEventError = `-- name: QueryUpdateOutboxEventError :one
UPDATE outbox_events AS oe
SET
  error_message=$2,
  updated_at=now()
WHERE oe.id = $1 RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
`

type QueryUpdateOutboxEventErrorParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
}

// QueryUpdateOutboxEventError
//
//	UPDATE outbox_events AS oe
//	SET
//	  error_message=$2,
//	  updated_at=now()
//	WHERE oe.id = $1 RETURNING id, group_id, correlation_id, destination, event_type, headers, payload, error_message, metadata, sent_time, processing_at, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateOutboxEventError(ctx context.Context, arg QueryUpdateOutboxEventErrorParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, queryUpdateOutboxEventError, arg.ID, arg.ErrorMessage)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CorrelationID,
		&i.Destination,
		&i.EventType,
		&i.Headers,
		&i.Payload,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentTime,
		&i.ProcessingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
