BEGIN;
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Utility functions (Global)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Create a function that generates a UUID-compatible string
CREATE OR REPLACE FUNCTION generate_uuid()
RETURNS uuid AS $$
DECLARE
    v_time timestamp with time zone := clock_timestamp();
    v_epoch bigint;
    v_micro bigint;
    v_random text;
    v_uuid text;
BEGIN
    -- Extract time components with maximum precision
    v_epoch := extract(epoch from v_time)::bigint;
    v_micro := mod(extract(microseconds from v_time)::bigint, 1000000);
    
    -- Generate random components using built-in random()
    v_random := '';
    FOR i IN 1..10 LOOP
        v_random := v_random || lpad(to_hex(floor(random() * 256)::int), 2, '0');
    END LOOP;
    
    -- Construct parts of the UUID using timestamp and randomness
    -- Format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
    -- Where y is 8, 9, a, or b
    v_uuid := lpad(to_hex(v_epoch), 8, '0') || '-' ||
              lpad(to_hex(v_micro), 4, '0') || '-' ||
              '4' || substring(v_random, 1, 3) || '-' ||
              substr('89ab', 1 + (random() * 4)::int % 4, 1) || substring(v_random, 4, 3) || '-' ||
              substring(v_random, 7, 12);
              
    RETURN v_uuid::uuid;
END;
$$ LANGUAGE plpgsql;

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Sequences (Global)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Short code generation range allocator
CREATE SEQUENCE IF NOT EXISTS short_code_counter
    START WITH 1
    INCREMENT BY 1000
    NO CYCLE;

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Users (Identity context)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS user_status (
    id         UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    name        VARCHAR(50) NOT NULL UNIQUE, -- e.g., active, suspended, inactive
    description VARCHAR(255) NULL,
    created_at  timestamp with time zone NOT NULL DEFAULT current_timestamp,
    updated_at  timestamp with time zone NOT NULL DEFAULT current_timestamp,
    deleted_at  timestamp with time zone NULL
);

COMMENT ON TABLE user_status IS 'Defines possible statuses for user accounts.';
COMMENT ON COLUMN user_status.id IS 'Primary key, UUID generated by the database.';
COMMENT ON COLUMN user_status.name IS 'Unique name of the status (e.g. ACTIVE, SUSPENDED).';
COMMENT ON COLUMN user_status.description IS 'Optional description of the status.';
COMMENT ON COLUMN user_status.created_at IS 'Timestamp when the status was created.';
COMMENT ON COLUMN user_status.updated_at IS 'Timestamp when the status was last updated.';
COMMENT ON COLUMN user_status.deleted_at IS 'Timestamp when the status was deleted (soft delete).';

INSERT INTO user_status (name, description) VALUES ('ACTIVE', 'Indicates that the user account is active');
INSERT INTO user_status (name, description) VALUES ('SUSPENDED', 'Indicates that the user account is suspended');
INSERT INTO user_status (name, description) VALUES ('INACTIVE', 'Indicates that the user account is inactive');

CREATE TABLE IF NOT EXISTS users (
    id                   UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    username             VARCHAR(50)  NOT NULL UNIQUE,
    first_name           VARCHAR(50),
    last_name            VARCHAR(50),
    email                VARCHAR(255) NOT NULL,
    password_hash        VARCHAR(255) NOT NULL,
    verified             BOOLEAN      NOT NULL DEFAULT FALSE,
    verification_token   VARCHAR(100),
    verification_expires TIMESTAMPTZ,
    status_id            VARCHAR(50) REFERENCES user_status(id),
    metadata             JSON NULL,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at           TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX idx_users_email ON users (email);

COMMENT ON TABLE users IS 'Represents registered users of the system.';
COMMENT ON COLUMN users.id IS 'Primary key, UUID generated by the database.';
COMMENT ON COLUMN users.username IS 'Unique username chosen by the user.';
COMMENT ON COLUMN users.first_name IS 'Users first name.';
COMMENT ON COLUMN users.last_name IS 'Users last name.';
COMMENT ON COLUMN users.email IS 'Email address, used for login and notifications.';
COMMENT ON COLUMN users.password_hash IS 'Hashed password using bcrypt.';
COMMENT ON COLUMN users.verified IS 'Indicates if the user has verified their email.';
COMMENT ON COLUMN users.verification_token IS 'Token used for email verification.';
COMMENT ON COLUMN users.verification_expires IS 'Expiration time for the verification token.';
COMMENT ON COLUMN users.status_id IS 'User account status (e.g. ACTIVE, SUSPENDED).';
COMMENT ON COLUMN users.metadata IS 'Additional user metadata stored as JSON.';
COMMENT ON COLUMN users.created_at IS 'Timestamp when the user account was created.';
COMMENT ON COLUMN users.updated_at IS 'Timestamp when the user account was last updated.';


-- API keys (Identity context)
CREATE TABLE IF NOT EXISTS api_keys (
    id           UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    user_id      UUID  NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key_hash     VARCHAR(64)  NOT NULL, -- SHA-256 of the raw key
    name         VARCHAR(100) NOT NULL,
    scopes       TEXT[]       NOT NULL DEFAULT '{}',
    rate_limit   INTEGER      NOT NULL DEFAULT 1000, -- requests per minute
    last_used_at TIMESTAMPTZ,
    expires_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX idx_api_keys_hash ON api_keys (key_hash);
CREATE INDEX idx_api_keys_user ON api_keys (user_id);

COMMENT ON TABLE api_keys IS 'API keys for programmatic access, associated with a user.';
COMMENT ON COLUMN api_keys.id IS 'Primary key, generated by the application.';
COMMENT ON COLUMN api_keys.user_id IS 'Foreign key referencing the user who owns this API key.';
COMMENT ON COLUMN api_keys.key_hash IS 'SHA-256 hash of the raw API key for secure storage.';
COMMENT ON COLUMN api_keys.name IS 'User-defined name for the API key.';
COMMENT ON COLUMN api_keys.scopes IS 'Array of scopes/permissions associated with the API key.';
COMMENT ON COLUMN api_keys.rate_limit IS 'Rate limit for this API key (requests per minute).';
COMMENT ON COLUMN api_keys.last_used_at IS 'Timestamp of the last time this API key was used.';
COMMENT ON COLUMN api_keys.expires_at IS 'Expiration timestamp for the API key.';
COMMENT ON INDEX idx_api_keys_hash IS 'Ensures that the key hash is unique for secure storage.';
COMMENT ON INDEX idx_api_keys_user IS 'Index to quickly find API keys by user ID.';

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- urls (URL context) - core domain
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS url_status (
    id         UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    name        VARCHAR(50) NOT NULL UNIQUE, -- e.g., active, suspended, inactive
    description VARCHAR(255) NULL,
    created_at  timestamp with time zone NOT NULL DEFAULT current_timestamp,
    updated_at  timestamp with time zone NOT NULL DEFAULT current_timestamp,
    deleted_at  timestamp with time zone NULL
);

COMMENT ON TABLE url_status IS 'Defines possible statuses for URL entries.';
COMMENT ON COLUMN url_status.id IS 'Primary key, UUID generated by the database.';
COMMENT ON COLUMN url_status.name IS 'Unique name of the status (e.g. ACTIVE, SUSPENDED).';
COMMENT ON COLUMN url_status.description IS 'Optional description of the status.';
COMMENT ON COLUMN url_status.created_at IS 'Timestamp when the status was created.';
COMMENT ON COLUMN url_status.updated_at IS 'Timestamp when the status was last updated.';
COMMENT ON COLUMN url_status.deleted_at IS 'Timestamp when the status was deleted (soft delete).';

INSERT INTO url_status (name, description) VALUES ('ACTIVE', 'Indicates that the URL is active');
INSERT INTO url_status (name, description) VALUES ('SUSPENDED', 'Indicates that the URL is suspended');
INSERT INTO url_status (name, description) VALUES ('DELETED', 'Indicates that the URL is deleted');
INSERT INTO url_status (name, description) VALUES ('EXPIRED', 'Indicates that the URL is expired');

-- URLs (URL context — core domain)
CREATE TABLE IF NOT EXISTS urls (
    id           UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    user_id      UUID NOT NULL REFERENCES users(id),
    short_code   VARCHAR(12)  NOT NULL,
    custom_alias VARCHAR(12),
    original_url TEXT         NOT NULL,
    status_id    UUID REFERENCES url_status(id),
    expires_on   TIMESTAMPTZ  NOT NULL,
    og_title     TEXT,
    og_description TEXT,
    og_image_url TEXT,
    metadata     JSON NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ NULL
);

-- These two indexes are the most performance-critical in the system
CREATE UNIQUE INDEX idx_urls_short_code   ON urls (short_code);
CREATE UNIQUE INDEX idx_urls_custom_alias ON urls (custom_alias) WHERE custom_alias IS NOT NULL;

CREATE INDEX idx_urls_user_id    ON urls (user_id);
-- TODO: set the unique partial indices on status_id and expires_on to handle joins on the status table
-- CREATE INDEX idx_urls_status     ON urls (status) WHERE status = 'ACTIVE';
-- CREATE INDEX idx_urls_expires_on ON urls (expires_on) WHERE status = 'ACTIVE';

COMMENT ON TABLE urls IS 'Represents shortened URLs created by users.';
COMMENT ON COLUMN urls.id IS 'Primary key, generated by the application.';
COMMENT ON COLUMN urls.user_id IS 'Foreign key referencing the user who created the URL.';
COMMENT ON COLUMN urls.short_code IS 'Unique short code for the URL, used in the shortened URL.';
COMMENT ON COLUMN urls.custom_alias IS 'Optional custom alias for the URL, must be unique if provided.';
COMMENT ON COLUMN urls.original_url IS 'The original long URL that is being shortened.';
COMMENT ON COLUMN urls.status_id IS 'Foreign key referencing the status of the URL (e.g. ACTIVE, SUSPENDED).';
COMMENT ON COLUMN urls.expires_on IS 'Timestamp when the URL expires and should no longer redirect.';
COMMENT ON COLUMN urls.og_title IS 'Open Graph title for the URL, used for rich previews.';
COMMENT ON COLUMN urls.og_description IS 'Open Graph description for the URL, used for rich previews.';
COMMENT ON COLUMN urls.og_image_url IS 'Open Graph image URL for the URL, used for rich previews.';
COMMENT ON COLUMN urls.metadata IS 'Additional metadata about the URL stored as JSON.';
COMMENT ON COLUMN urls.created_at IS 'Timestamp when the URL was created.';
COMMENT ON COLUMN urls.updated_at IS 'Timestamp when the URL was last updated.';
COMMENT ON COLUMN urls.deleted_at IS 'Timestamp when the URL was deleted (soft delete).';

-- Keywords (URL context)
CREATE TABLE IF NOT EXISTS keywords (
    id         UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    url_id     UUID  NOT NULL REFERENCES urls(id) ON DELETE CASCADE,
    value      VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL
);

CREATE INDEX idx_keywords_url_id ON keywords (url_id);
CREATE INDEX idx_keywords_value  ON keywords (value);
CREATE UNIQUE INDEX idx_keywords_url_id_value ON keywords (url_id, value) WHERE deleted_at IS NULL;

COMMENT ON TABLE keywords IS 'Represents keywords/tags associated with a URL for categorization and search.';
COMMENT ON COLUMN keywords.id IS 'Primary key, generated by the application.';
COMMENT ON COLUMN keywords.url_id IS 'Foreign key referencing the URL this keyword is associated with.';
COMMENT ON COLUMN keywords.value IS 'The keyword/tag value.';
COMMENT ON COLUMN keywords.created_at IS 'Timestamp when the keyword was created.';
COMMENT ON COLUMN keywords.updated_at IS 'Timestamp when the keyword was last updated.';
COMMENT ON COLUMN keywords.deleted_at IS 'Timestamp when the keyword was deleted (soft delete).';
COMMENT ON INDEX idx_keywords_url_id_value IS 'Ensures that a given keyword value can only be associated with a URL once (ignoring deleted keywords).';

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- webhooks (Notification context)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Webhooks (Notification context)
CREATE TABLE IF NOT EXISTS webhooks (
    id         UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    user_id    UUID  NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    url_id     UUID  REFERENCES urls(id) ON DELETE CASCADE, -- NULL = all URLs
    endpoint   TEXT         NOT NULL,
    secret     VARCHAR(64)  NOT NULL, -- HMAC signing secret
    events     TEXT[]       NOT NULL, -- e.g. {'url.accessed', 'url.expired'}
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL
);

CREATE INDEX idx_webhooks_user_id ON webhooks (user_id);
CREATE INDEX idx_webhooks_url_id  ON webhooks (url_id);

COMMENT ON TABLE webhooks IS 'Represents webhook subscriptions for URL events.';
COMMENT ON COLUMN webhooks.id IS 'Primary key, generated by the application.';
COMMENT ON COLUMN webhooks.user_id IS 'Foreign key referencing the user who owns this webhook.';
COMMENT ON COLUMN webhooks.url_id IS 'Foreign key referencing the URL this webhook is associated with (NULL means it applies to all URLs).';
COMMENT ON COLUMN webhooks.endpoint IS 'The URL endpoint to which the webhook will send POST requests when events occur.';
COMMENT ON COLUMN webhooks.secret IS 'HMAC signing secret used to verify webhook payloads.';
COMMENT ON COLUMN webhooks.events IS 'Array of event types that trigger this webhook (e.g. url.accessed, url.expired).';
COMMENT ON COLUMN webhooks.active IS 'Indicates whether the webhook is active and should receive events.';
COMMENT ON COLUMN webhooks.created_at IS 'Timestamp when the webhook was created.';
COMMENT ON COLUMN webhooks.updated_at IS 'Timestamp when the webhook was last updated.';
COMMENT ON COLUMN webhooks.deleted_at IS 'Timestamp when the webhook was deleted (soft delete).';

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- url scans (Security context)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Security scan results (Security context)
CREATE TABLE IF NOT EXISTS url_scans (
    id           UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    url_id       UUID  NOT NULL REFERENCES urls(id),
    provider     VARCHAR(50)  NOT NULL, -- 'google_safe_browsing' | 'virustotal'
    result       VARCHAR(20)  NOT NULL, -- 'safe' | 'malware' | 'phishing' | 'unknown'
    raw_response JSONB,
    scanned_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_url_scans_url_id ON url_scans (url_id);

COMMENT ON TABLE url_scans IS 'Represents security scan results for URLs.';
COMMENT ON COLUMN url_scans.id IS 'Primary key, generated by the application.';
COMMENT ON COLUMN url_scans.url_id IS 'Foreign key referencing the URL that was scanned.';
COMMENT ON COLUMN url_scans.provider IS 'The security scan provider (e.g. google_safe_browsing, virustotal).';
COMMENT ON COLUMN url_scans.result IS 'The result of the scan (e.g. safe, malware, phishing, unknown).';
COMMENT ON COLUMN url_scans.raw_response IS 'The raw JSON response from the security scan provider for auditing and debugging purposes.';
COMMENT ON COLUMN url_scans.scanned_at IS 'Timestamp when the URL was scanned.';

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- transaction outbox (Eventing context)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- outbox events
CREATE TABLE outbox_events (
    id              UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    group_id        VARCHAR,
    correlation_id  VARCHAR,
    destination     VARCHAR NOT NULL,
    event_type      VARCHAR NOT NULL,
    headers         JSON NOT NULL,
    payload         JSON NOT NULL,
    error_message   VARCHAR NULL,
    metadata        JSON NULL, -- Additional metadata
    sent_time       TIMESTAMP WITH TIME ZONE NULL,
    processing_at   TIMESTAMP WITH TIME ZONE NULL,
    created_at      TIMESTAMP with time zone NOT NULL DEFAULT current_timestamp,
    updated_at      TIMESTAMP with time zone NOT NULL DEFAULT current_timestamp,
    deleted_at      TIMESTAMP with time zone NULL
);

CREATE INDEX ix_outbox_events_sent_time_idx ON outbox_events("sent_time");
CREATE INDEX ix_outbox_events_group_id_idx ON outbox_events("group_id");
CREATE INDEX ix_outbox_events_correlation_id_idx ON outbox_events("correlation_id");
CREATE INDEX ix_outbox_events_created_at_event_type_idx ON outbox_events("created_at", "event_type");
COMMENT ON INDEX ix_outbox_events_created_at_event_type_idx IS 'This index is used to prevent duplicate outbox events for a given event type';

COMMENT ON COLUMN outbox_events.id IS 'This is the UUID generated by the database server';
COMMENT ON COLUMN outbox_events.destination IS 'This is the destination of the outbox event or where it is intended to be sent';
COMMENT ON COLUMN outbox_events.event_type IS 'This is the event type of the outbox event that is going to be sent out to a given destination';
COMMENT ON COLUMN outbox_events.headers IS 'This is the header in JSON format of the outgoing message that is going to be sent out to a given destination';
COMMENT ON COLUMN outbox_events.payload IS 'This is the payload in JSON format that is going to be sent out to a given destination';
COMMENT ON COLUMN outbox_events.error_message IS 'The error message associated with the outbox event if there is a failure sending out this event/message';
COMMENT ON COLUMN outbox_events.group_id IS 'The group ID associated with the outbox event, this is the identifier for a given consumer group handling sending out this event type';
COMMENT ON COLUMN outbox_events.correlation_id IS 'The correlation ID associated with the outbox event';
COMMENT ON COLUMN outbox_events.metadata IS 'Additional metadata about the outbox event in JSON format';
COMMENT ON COLUMN outbox_events.sent_time IS 'When the outbox event was sent out. Null if not sent out yet';
COMMENT ON COLUMN outbox_events.created_at IS 'Timestamp when the outbox event was created';
COMMENT ON COLUMN outbox_events.updated_at IS 'Timestamp when the outbox event was last updated';
COMMENT ON COLUMN outbox_events.deleted_at IS 'Timestamp when the outbox event was soft deleted, null if active';

CREATE TABLE kafka_outbox_events (
    id              UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    correlation_id  VARCHAR,
    partition_key   VARCHAR,
    destination     VARCHAR NOT NULL,
    event_type      VARCHAR NOT NULL,
    payload         JSON NOT NULL,
    error_message   VARCHAR NULL,
    metadata        JSON NULL, -- Additional metadata
    sent_time       TIMESTAMP WITH TIME ZONE NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at      TIMESTAMP with time zone NULL
);

CREATE INDEX ix_kafka_outbox_events_sent_time_idx ON kafka_outbox_events("sent_time");
CREATE INDEX ix_kafka_outbox_events_partition_key_idx ON kafka_outbox_events("partition_key");
CREATE INDEX ix_kafka_outbox_events_correlation_id_idx ON kafka_outbox_events("correlation_id");

COMMENT ON COLUMN kafka_outbox_events.id IS 'This is the UUID generated by the database server';
COMMENT ON COLUMN kafka_outbox_events.partition_key IS 'The Partition Key associated with the outbox event, this is the key that is used in Kafka to assign a message to a given partition in a topic';
COMMENT ON COLUMN kafka_outbox_events.correlation_id IS 'The correlation ID associated with the outbox event';
COMMENT ON COLUMN kafka_outbox_events.destination IS 'This is the destination of the outbox event or where it is intended to be sent';
COMMENT ON COLUMN kafka_outbox_events.event_type IS 'This is the event type of the outbox event that is going to be sent out to a given destination';
COMMENT ON COLUMN kafka_outbox_events.payload IS 'This is the payload in JSON format that is going to be sent out to a given destination';
COMMENT ON COLUMN kafka_outbox_events.error_message IS 'The error message associated with the outbox event if there is a failure sending out this event/message';
COMMENT ON COLUMN kafka_outbox_events.metadata IS 'Additional metadata about the kafka outbox event in JSON format';
COMMENT ON COLUMN kafka_outbox_events.sent_time IS 'When the outbox event was sent out. Null if not sent out yet';
COMMENT ON COLUMN kafka_outbox_events.created_at IS 'Timestamp when the outbox event was created';
COMMENT ON COLUMN kafka_outbox_events.updated_at IS 'Timestamp when the outbox event was last updated';
COMMENT ON COLUMN kafka_outbox_events.deleted_at IS 'Timestamp when the outbox event was soft deleted, null if active';

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- audit (Audit context)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS audit_trail
(
    id BIGSERIAL primary key,
    schema_name text COLLATE pg_catalog."default" NOT NULL,
    table_name text COLLATE pg_catalog."default" NOT NULL,
    relid oid NOT NULL,
    session_user_name text COLLATE pg_catalog."default",
    action_tstamp_tx timestamp with time zone NOT NULL,
    action_tstamp_stm timestamp with time zone NOT NULL,
    action_tstamp_clk timestamp with time zone NOT NULL,
    transaction_id bigint,
    application_name text COLLATE pg_catalog."default",
    client_addr inet,
    client_port integer,
    client_query text COLLATE pg_catalog."default",
    action text COLLATE pg_catalog."default" NOT NULL,
    row_data jsonb,
    changed_fields jsonb,
    statement_only boolean NOT NULL,

    CONSTRAINT audit_trail_action_check CHECK (action = ANY (ARRAY['I'::text, 'D'::text, 'U'::text, 'T'::text]))
);

-- CreateIndex
CREATE INDEX IF NOT EXISTS audit_trail_action_idx
    ON audit_trail USING btree
    (action COLLATE pg_catalog."default" ASC NULLS LAST);

CREATE INDEX IF NOT EXISTS audit_trail_action_tstamp_tx_stm_idx
    ON audit_trail USING btree
    (action_tstamp_stm ASC NULLS LAST);

CREATE INDEX IF NOT EXISTS audit_trail_relid_idx
    ON audit_trail USING btree
    (relid ASC NULLS LAST);

-- Add GIN index for JSONB fields for better performance
CREATE INDEX IF NOT EXISTS audit_trail_row_data_idx
    ON audit_trail USING gin (row_data);

CREATE INDEX IF NOT EXISTS audit_trail_changed_fields_idx
    ON audit_trail USING gin (changed_fields);

-- CreateFunction
CREATE OR REPLACE FUNCTION create_log_on_modify()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE NOT LEAKPROOF SECURITY DEFINER
    SET search_path=pg_catalog, public
AS $BODY$
DECLARE
    audit_row audit_trail;
    include_values boolean;
    log_diffs boolean;
    excluded_cols text[] = ARRAY[]::text[];
    row_data jsonb;
    changed_fields jsonb;
    t_record record;
    i_record record;
    old_row jsonb;
    new_row jsonb;
BEGIN
    IF TG_WHEN <> 'AFTER' THEN
        RAISE EXCEPTION 'create_log_on_modify() may only run as an AFTER trigger';
    END IF;

    audit_row = ROW(
        nextval('audit_trail_id_seq'), -- id
        TG_TABLE_SCHEMA::text,                        -- schema_name
        TG_TABLE_NAME::text,                          -- table_name
        TG_RELID,                                     -- relation OID for much quicker searches
        session_user::text,                           -- session_user_name
        current_timestamp,                            -- action_tstamp_tx
        statement_timestamp(),                        -- action_tstamp_stm
        clock_timestamp(),                            -- action_tstamp_clk
        txid_current(),                               -- transaction ID
        current_setting('application_name'),          -- client application
        inet_client_addr(),                           -- client_addr
        inet_client_port(),                           -- client_port
        current_query(),                              -- top-level query or queries (if multistatement) from client
        substring(TG_OP,1,1),                         -- action
        NULL, NULL,                                   -- row_data, changed_fields
        'f'                                           -- statement_only
        );

    IF NOT TG_ARGV[0]::boolean IS DISTINCT FROM 'f'::boolean THEN
        audit_row.client_query = NULL;
    END IF;

    IF TG_ARGV[1] IS NOT NULL THEN
        excluded_cols = TG_ARGV[1]::text[];
    END IF;

    IF (TG_OP = 'UPDATE' AND TG_LEVEL = 'ROW') THEN
        -- Convert OLD and NEW to jsonb
        old_row = to_jsonb(OLD);
        new_row = to_jsonb(NEW);
        
        -- Start with all fields from OLD record
        audit_row.row_data = old_row;
        
        -- Calculate changed fields
        changed_fields = jsonb_object_agg(key, value) 
                     FROM jsonb_each(new_row)
                     WHERE NOT (old_row ? key AND old_row->key = value);
                     
        -- If specified, remove excluded columns
        IF array_length(excluded_cols, 1) > 0 THEN
            FOR i IN 1..array_length(excluded_cols, 1)
            LOOP
                audit_row.row_data = audit_row.row_data - excluded_cols[i];
                changed_fields = changed_fields - excluded_cols[i];
            END LOOP;
        END IF;
        
        audit_row.changed_fields = changed_fields;
        
        IF (changed_fields = '{}'::jsonb) THEN
            -- All changed fields are ignored. Skip this update.
            RETURN NULL;
        END IF;
        
    ELSIF (TG_OP = 'DELETE' AND TG_LEVEL = 'ROW') THEN
        -- Convert OLD to jsonb
        audit_row.row_data = to_jsonb(OLD);
        
        -- If specified, remove excluded columns
        IF array_length(excluded_cols, 1) > 0 THEN
            FOR i IN 1..array_length(excluded_cols, 1)
            LOOP
                audit_row.row_data = audit_row.row_data - excluded_cols[i];
            END LOOP;
        END IF;
        
    ELSIF (TG_OP = 'INSERT' AND TG_LEVEL = 'ROW') THEN
        -- Convert NEW to jsonb
        audit_row.row_data = to_jsonb(NEW);
        
        -- If specified, remove excluded columns
        IF array_length(excluded_cols, 1) > 0 THEN
            FOR i IN 1..array_length(excluded_cols, 1)
            LOOP
                audit_row.row_data = audit_row.row_data - excluded_cols[i];
            END LOOP;
        END IF;
        
    ELSIF (TG_LEVEL = 'STATEMENT' AND TG_OP IN ('INSERT','UPDATE','DELETE','TRUNCATE')) THEN
        audit_row.statement_only = 't';
    ELSE
        RAISE EXCEPTION '[create_log_on_modify] - Trigger func added as trigger for unhandled case: %, %',TG_OP, TG_LEVEL;
        RETURN NULL;
    END IF;
    
    INSERT INTO audit_trail VALUES (audit_row.*);
    RETURN NULL;
END;
$BODY$;

-- Create helper functions for enabling audit
CREATE OR REPLACE FUNCTION audit_table(target_table regclass, audit_rows boolean, audit_query_text boolean, ignored_cols text[]) RETURNS void AS $body$
DECLARE
  stm_targets text = 'INSERT OR UPDATE OR DELETE OR TRUNCATE';
  _q_txt text;
  _ignored_cols_snip text = '';
BEGIN
    EXECUTE 'DROP TRIGGER IF EXISTS audit_trigger_row ON ' || target_table;
    EXECUTE 'DROP TRIGGER IF EXISTS audit_trigger_stm ON ' || target_table;

    IF audit_rows THEN
        IF array_length(ignored_cols,1) > 0 THEN
            _ignored_cols_snip = ', ' || quote_literal(ignored_cols);
        END IF;
        _q_txt = 'CREATE TRIGGER audit_trigger_row AFTER INSERT OR UPDATE OR DELETE ON ' || 
                 target_table || 
                 ' FOR EACH ROW EXECUTE PROCEDURE create_log_on_modify(' ||
                 quote_literal(audit_query_text) || _ignored_cols_snip || ');';
        RAISE NOTICE '%',_q_txt;
        EXECUTE _q_txt;
        stm_targets = 'TRUNCATE';
    END IF;

    _q_txt = 'CREATE TRIGGER audit_trigger_stm AFTER ' || stm_targets || ' ON ' ||
             target_table ||
             ' FOR EACH STATEMENT EXECUTE PROCEDURE create_log_on_modify('||
             quote_literal(audit_query_text) || ');';
    RAISE NOTICE '%',_q_txt;
    EXECUTE _q_txt;
END;
$body$
language 'plpgsql';

-- Pg doesn't allow variadic calls with 0 params, so provide wrappers
CREATE OR REPLACE FUNCTION audit_table(target_table regclass, audit_rows boolean, audit_query_text boolean) RETURNS void AS $body$
SELECT audit_table($1, $2, $3, ARRAY[]::text[]);
$body$ LANGUAGE SQL;

-- And provide a convenience call wrapper for the simplest case
-- of row-level logging with no excluded cols and query logging enabled.
CREATE OR REPLACE FUNCTION audit_table(target_table regclass) RETURNS void AS $$
SELECT audit_table($1, BOOLEAN 't', BOOLEAN 't');
$$ LANGUAGE 'sql';

-- Add tables to audit here (uncomment and customize with your table names)
SELECT audit_table('"users"');
SELECT audit_table('"urls"');
SELECT audit_table('"url_scans"');
SELECT audit_table('"webhooks"');
SELECT audit_table('"api_keys"');
SELECT audit_table('"keywords"');

COMMIT;