-- Create a function that generates a UUID-compatible string
CREATE OR REPLACE FUNCTION generate_uuid()
RETURNS uuid AS $$
DECLARE
    v_time timestamp with time zone := clock_timestamp();
    v_epoch bigint;
    v_micro bigint;
    v_random text;
    v_uuid text;
BEGIN
    -- Extract time components with maximum precision
    v_epoch := extract(epoch from v_time)::bigint;
    v_micro := mod(extract(microseconds from v_time)::bigint, 1000000);
    
    -- Generate random components using built-in random()
    v_random := '';
    FOR i IN 1..10 LOOP
        v_random := v_random || lpad(to_hex(floor(random() * 256)::int), 2, '0');
    END LOOP;
    
    -- Construct parts of the UUID using timestamp and randomness
    -- Format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
    -- Where y is 8, 9, a, or b
    v_uuid := lpad(to_hex(v_epoch), 8, '0') || '-' ||
              lpad(to_hex(v_micro), 4, '0') || '-' ||
              '4' || substring(v_random, 1, 3) || '-' ||
              substr('89ab', 1 + (random() * 4)::int % 4, 1) || substring(v_random, 4, 3) || '-' ||
              substring(v_random, 7, 12);
              
    RETURN v_uuid::uuid;
END;
$$ LANGUAGE plpgsql;

-- Short code generation range allocator
CREATE SEQUENCE short_code_counter
    START WITH 1
    INCREMENT BY 1000
    NO CYCLE;

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Users (Identity context)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS user_status (
    id         UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    name        VARCHAR(50) NOT NULL UNIQUE, -- e.g., active, suspended, inactive
    description VARCHAR(255) NULL,
    created_at  timestamp with time zone NOT NULL DEFAULT current_timestamp,
    updated_at  timestamp with time zone NOT NULL DEFAULT current_timestamp,
    deleted_at  timestamp with time zone NULL
);

INSERT INTO user_status (name, description) VALUES ('ACTIVE', 'Indicates that the user account is active');
INSERT INTO user_status (name, description) VALUES ('SUSPENDED', 'Indicates that the user account is suspended');
INSERT INTO user_status (name, description) VALUES ('INACTIVE', 'Indicates that the user account is inactive');


CREATE TABLE IF NOT EXISTS users (
    id                   UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    username             VARCHAR(50)  NOT NULL UNIQUE,
    first_name           VARCHAR(50),
    last_name            VARCHAR(50),
    email                VARCHAR(255) NOT NULL,
    password_hash        VARCHAR(255) NOT NULL,
    verified             BOOLEAN      NOT NULL DEFAULT FALSE,
    verification_token   VARCHAR(100),
    verification_expires TIMESTAMPTZ,
    status_id            VARCHAR(50) REFERENCES user_status(id),
    metadata             JSON NULL,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at           TIMESTAMPTZ NULL
);

COMMENT ON TABLE users IS 'Represents registered users of the system.';
COMMENT ON COLUMN users.id IS 'Primary key, UUID generated by the database.';
COMMENT ON COLUMN users.username IS 'Unique username chosen by the user.';
COMMENT ON COLUMN users.first_name IS 'Users first name.';
COMMENT ON COLUMN users.last_name IS 'Users last name.';
COMMENT ON COLUMN users.email IS 'Email address, used for login and notifications.';
COMMENT ON COLUMN users.password_hash IS 'Hashed password using bcrypt.';
COMMENT ON COLUMN users.verified IS 'Indicates if the user has verified their email.';
COMMENT ON COLUMN users.verification_token IS 'Token used for email verification.';
COMMENT ON COLUMN users.verification_expires IS 'Expiration time for the verification token.';
COMMENT ON COLUMN users.status_id IS 'User account status (e.g. ACTIVE, SUSPENDED).';
COMMENT ON COLUMN users.metadata IS 'Additional user metadata stored as JSON.';
COMMENT ON COLUMN users.created_at IS 'Timestamp when the user account was created.';
COMMENT ON COLUMN users.updated_at IS 'Timestamp when the user account was last updated.';

CREATE UNIQUE INDEX idx_users_email ON users (email);

-- API keys (Identity context)
CREATE TABLE api_keys (
    id           VARCHAR(20)  PRIMARY KEY,
    user_id      VARCHAR(20)  NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key_hash     VARCHAR(64)  NOT NULL, -- SHA-256 of the raw key
    name         VARCHAR(100) NOT NULL,
    scopes       TEXT[]       NOT NULL DEFAULT '{}',
    rate_limit   INTEGER      NOT NULL DEFAULT 1000, -- requests per minute
    last_used_at TIMESTAMPTZ,
    expires_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_api_keys_hash ON api_keys (key_hash);
CREATE INDEX idx_api_keys_user ON api_keys (user_id);

-- URLs (URL context — core domain)
CREATE TABLE urls (
    id           VARCHAR(20)  PRIMARY KEY,
    user_id      VARCHAR(20)  NOT NULL REFERENCES users(id),
    short_code   VARCHAR(12)  NOT NULL,
    custom_alias VARCHAR(12),
    original_url TEXT         NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    expires_on   TIMESTAMPTZ  NOT NULL,
    og_title     TEXT,
    og_description TEXT,
    og_image_url TEXT,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- These two indexes are the most performance-critical in the system
CREATE UNIQUE INDEX idx_urls_short_code   ON urls (short_code);
CREATE UNIQUE INDEX idx_urls_custom_alias ON urls (custom_alias) WHERE custom_alias IS NOT NULL;

CREATE INDEX idx_urls_user_id    ON urls (user_id);
CREATE INDEX idx_urls_status     ON urls (status) WHERE status = 'ACTIVE';
CREATE INDEX idx_urls_expires_on ON urls (expires_on) WHERE status = 'ACTIVE';

-- Keywords (URL context)
CREATE TABLE keywords (
    id         VARCHAR(20)  PRIMARY KEY,
    url_id     VARCHAR(20)  NOT NULL REFERENCES urls(id) ON DELETE CASCADE,
    value      VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_keywords_url_id ON keywords (url_id);
CREATE INDEX idx_keywords_value  ON keywords (value);

-- Webhooks (Notification context)
CREATE TABLE webhooks (
    id         VARCHAR(20)  PRIMARY KEY,
    user_id    VARCHAR(20)  NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    url_id     VARCHAR(20)  REFERENCES urls(id) ON DELETE CASCADE, -- NULL = all URLs
    endpoint   TEXT         NOT NULL,
    secret     VARCHAR(64)  NOT NULL, -- HMAC signing secret
    events     TEXT[]       NOT NULL, -- e.g. {'url.accessed', 'url.expired'}
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Security scan results (Security context)
CREATE TABLE url_scans (
    id           VARCHAR(20)  PRIMARY KEY,
    url_id       VARCHAR(20)  NOT NULL REFERENCES urls(id),
    provider     VARCHAR(50)  NOT NULL, -- 'google_safe_browsing' | 'virustotal'
    result       VARCHAR(20)  NOT NULL, -- 'safe' | 'malware' | 'phishing' | 'unknown'
    raw_response JSONB,
    scanned_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_url_scans_url_id ON url_scans (url_id);