// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: url_status_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryAllUrlStatuses = `-- name: QueryAllUrlStatuses :many
SELECT
  id,
  name,
  description,
  created_at,
  updated_at,
  deleted_at
FROM url_status us
WHERE CASE 
  WHEN $1::bool=true THEN us.deleted_at IS NULL OR us.deleted_at IS NOT NULL
  WHEN $1::bool=false THEN us.deleted_at IS NULL
  ELSE us.deleted_at IS NULL
END
ORDER BY us.created_at DESC
LIMIT $3
OFFSET $2
`

type QueryAllUrlStatusesParams struct {
	IncludeDeleted bool  `db:"include_deleted" json:"include_deleted"`
	CurrentOffset  int32 `db:"current_offset" json:"current_offset"`
	LimitBy        int32 `db:"limit_by" json:"limit_by"`
}

// QueryAllUrlStatuses
//
//	SELECT
//	  id,
//	  name,
//	  description,
//	  created_at,
//	  updated_at,
//	  deleted_at
//	FROM url_status us
//	WHERE CASE
//	  WHEN $1::bool=true THEN us.deleted_at IS NULL OR us.deleted_at IS NOT NULL
//	  WHEN $1::bool=false THEN us.deleted_at IS NULL
//	  ELSE us.deleted_at IS NULL
//	END
//	ORDER BY us.created_at DESC
//	LIMIT $3
//	OFFSET $2
func (q *Queries) QueryAllUrlStatuses(ctx context.Context, arg QueryAllUrlStatusesParams) ([]UrlStatus, error) {
	rows, err := q.db.Query(ctx, queryAllUrlStatuses, arg.IncludeDeleted, arg.CurrentOffset, arg.LimitBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UrlStatus
	for rows.Next() {
		var i UrlStatus
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryCreateUrlStatus = `-- name: QueryCreateUrlStatus :one
INSERT INTO url_status (name, description) VALUES ($1, $2) RETURNING id, name, description, created_at, updated_at, deleted_at
`

type QueryCreateUrlStatusParams struct {
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
}

// QueryCreateUrlStatus
//
//	INSERT INTO url_status (name, description) VALUES ($1, $2) RETURNING id, name, description, created_at, updated_at, deleted_at
func (q *Queries) QueryCreateUrlStatus(ctx context.Context, arg QueryCreateUrlStatusParams) (UrlStatus, error) {
	row := q.db.QueryRow(ctx, queryCreateUrlStatus, arg.Name, arg.Description)
	var i UrlStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryDeleteUrlStatusWithId = `-- name: QueryDeleteUrlStatusWithId :one
DELETE FROM url_status WHERE id = $1 RETURNING id, name, description, created_at, updated_at, deleted_at
`

// QueryDeleteUrlStatusWithId
//
//	DELETE FROM url_status WHERE id = $1 RETURNING id, name, description, created_at, updated_at, deleted_at
func (q *Queries) QueryDeleteUrlStatusWithId(ctx context.Context, id pgtype.UUID) (UrlStatus, error) {
	row := q.db.QueryRow(ctx, queryDeleteUrlStatusWithId, id)
	var i UrlStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const querySoftDeleteUrlStatus = `-- name: QuerySoftDeleteUrlStatus :one
UPDATE url_status
SET
  deleted_at = $2
WHERE id = $1 RETURNING id, name, description, created_at, updated_at, deleted_at
`

type QuerySoftDeleteUrlStatusParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// QuerySoftDeleteUrlStatus
//
//	UPDATE url_status
//	SET
//	  deleted_at = $2
//	WHERE id = $1 RETURNING id, name, description, created_at, updated_at, deleted_at
func (q *Queries) QuerySoftDeleteUrlStatus(ctx context.Context, arg QuerySoftDeleteUrlStatusParams) (UrlStatus, error) {
	row := q.db.QueryRow(ctx, querySoftDeleteUrlStatus, arg.ID, arg.DeletedAt)
	var i UrlStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateUrlStatus = `-- name: QueryUpdateUrlStatus :one
UPDATE url_status us
SET
  name=$2,
  description=$3
WHERE us.id = $1 RETURNING id, name, description, created_at, updated_at, deleted_at
`

type QueryUpdateUrlStatusParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
}

// QueryUpdateUrlStatus
//
//	UPDATE url_status us
//	SET
//	  name=$2,
//	  description=$3
//	WHERE us.id = $1 RETURNING id, name, description, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateUrlStatus(ctx context.Context, arg QueryUpdateUrlStatusParams) (UrlStatus, error) {
	row := q.db.QueryRow(ctx, queryUpdateUrlStatus, arg.ID, arg.Name, arg.Description)
	var i UrlStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUrlStatusById = `-- name: QueryUrlStatusById :one
SELECT
  id,
  name,
  description,
  created_at, 
  updated_at,
  deleted_at
FROM url_status
WHERE id = $1
`

// QueryUrlStatusById
//
//	SELECT
//	  id,
//	  name,
//	  description,
//	  created_at,
//	  updated_at,
//	  deleted_at
//	FROM url_status
//	WHERE id = $1
func (q *Queries) QueryUrlStatusById(ctx context.Context, id pgtype.UUID) (UrlStatus, error) {
	row := q.db.QueryRow(ctx, queryUrlStatusById, id)
	var i UrlStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUrlStatusByName = `-- name: QueryUrlStatusByName :one
SELECT
  id,
  name,
  description,
  created_at, 
  updated_at,
  deleted_at
FROM url_status
WHERE name = $1
`

// QueryUrlStatusByName
//
//	SELECT
//	  id,
//	  name,
//	  description,
//	  created_at,
//	  updated_at,
//	  deleted_at
//	FROM url_status
//	WHERE name = $1
func (q *Queries) QueryUrlStatusByName(ctx context.Context, name string) (UrlStatus, error) {
	row := q.db.QueryRow(ctx, queryUrlStatusByName, name)
	var i UrlStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
