// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: url_read_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryAllUrls = `-- name: QueryAllUrls :many
SELECT 
  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at,
  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at,
  COUNT(*) OVER() AS total_records
FROM urls u 
JOIN url_status us ON u.status_id = us.id
WHERE $1::bool OR u.deleted_at IS NULL
  AND (COALESCE($2, '') = '' OR us.name = $2)
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN u.created_at
      WHEN $3::text = 'updated_at' THEN u.updated_at
      WHEN $3::text = 'deleted_at' THEN u.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  -- Sort by 'created_at'
  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC' 
    THEN u.created_at END ASC,
  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC' 
    THEN u.created_at END DESC,
  
  -- Sort by 'updated_at'
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC' 
    THEN u.updated_at END ASC,
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC' 
    THEN u.updated_at END DESC,
  
  -- Sort by 'deleted_at'
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC' 
    THEN u.deleted_at END ASC,
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC' 
    THEN u.deleted_at END DESC
LIMIT $9
OFFSET $8
`

type QueryAllUrlsParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	UrlStatus      interface{}      `db:"url_status" json:"url_status"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryAllUrlsRow struct {
	Url          Url       `db:"url" json:"url"`
	UrlStatus    UrlStatus `db:"url_status" json:"url_status"`
	TotalRecords int64     `db:"total_records" json:"total_records"`
}

// Date range filtering
//
//	SELECT
//	  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at,
//	  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at,
//	  COUNT(*) OVER() AS total_records
//	FROM urls u
//	JOIN url_status us ON u.status_id = us.id
//	WHERE $1::bool OR u.deleted_at IS NULL
//	  AND (COALESCE($2, '') = '' OR us.name = $2)
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN u.created_at
//	      WHEN $3::text = 'updated_at' THEN u.updated_at
//	      WHEN $3::text = 'deleted_at' THEN u.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  -- Sort by 'created_at'
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC'
//	    THEN u.created_at END ASC,
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC'
//	    THEN u.created_at END DESC,
//
//	  -- Sort by 'updated_at'
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC'
//	    THEN u.updated_at END ASC,
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC'
//	    THEN u.updated_at END DESC,
//
//	  -- Sort by 'deleted_at'
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC'
//	    THEN u.deleted_at END ASC,
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC'
//	    THEN u.deleted_at END DESC
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryAllUrls(ctx context.Context, arg QueryAllUrlsParams) ([]QueryAllUrlsRow, error) {
	rows, err := q.db.Query(ctx, queryAllUrls,
		arg.IncludeDeleted,
		arg.UrlStatus,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllUrlsRow
	for rows.Next() {
		var i QueryAllUrlsRow
		if err := rows.Scan(
			&i.Url.ID,
			&i.Url.UserID,
			&i.Url.ShortCode,
			&i.Url.CustomAlias,
			&i.Url.OriginalUrl,
			&i.Url.StatusID,
			&i.Url.ExpiresOn,
			&i.Url.OgTitle,
			&i.Url.OgDescription,
			&i.Url.OgImageUrl,
			&i.Url.Metadata,
			&i.Url.CreatedAt,
			&i.Url.UpdatedAt,
			&i.Url.DeletedAt,
			&i.UrlStatus.ID,
			&i.UrlStatus.Name,
			&i.UrlStatus.Description,
			&i.UrlStatus.CreatedAt,
			&i.UrlStatus.UpdatedAt,
			&i.UrlStatus.DeletedAt,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAllUrlsByUserId = `-- name: QueryAllUrlsByUserId :many
SELECT 
  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at,
  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at,
  COUNT(*) OVER() AS total_records
FROM urls u 
JOIN url_status us ON u.status_id = us.id
WHERE u.user_id = $1
  AND ($2::bool OR u.deleted_at IS NULL)
  AND (COALESCE($3, '') = '' OR us.name = $3)
AND (
  $4::text IS NULL
  OR $5::timestamp IS NULL
  OR $6::timestamp IS NULL
  OR (
    CASE 
      WHEN $4::text = 'created_at' THEN u.created_at
      WHEN $4::text = 'updated_at' THEN u.updated_at
      WHEN $4::text = 'deleted_at' THEN u.deleted_at
    END BETWEEN $5::timestamp AND $6::timestamp
  )
)
ORDER BY
  -- Sort by 'created_at'
  CASE WHEN $7::text = 'created_at' AND $8::text = 'ASC' 
    THEN u.created_at END ASC,
  CASE WHEN $7::text = 'created_at' AND $8::text = 'DESC' 
    THEN u.created_at END DESC,
  
  -- Sort by 'updated_at'
  CASE WHEN $7::text = 'updated_at' AND $8::text = 'ASC' 
    THEN u.updated_at END ASC,
  CASE WHEN $7::text = 'updated_at' AND $8::text = 'DESC' 
    THEN u.updated_at END DESC,
  
  -- Sort by 'deleted_at'
  CASE WHEN $7::text = 'deleted_at' AND $8::text = 'ASC' 
    THEN u.deleted_at END ASC,
  CASE WHEN $7::text = 'deleted_at' AND $8::text = 'DESC' 
    THEN u.deleted_at END DESC
LIMIT $10
OFFSET $9
`

type QueryAllUrlsByUserIdParams struct {
	UserID         pgtype.UUID      `db:"user_id" json:"user_id"`
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	UrlStatus      interface{}      `db:"url_status" json:"url_status"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryAllUrlsByUserIdRow struct {
	Url          Url       `db:"url" json:"url"`
	UrlStatus    UrlStatus `db:"url_status" json:"url_status"`
	TotalRecords int64     `db:"total_records" json:"total_records"`
}

// Date range filtering
//
//	SELECT
//	  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at,
//	  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at,
//	  COUNT(*) OVER() AS total_records
//	FROM urls u
//	JOIN url_status us ON u.status_id = us.id
//	WHERE u.user_id = $1
//	  AND ($2::bool OR u.deleted_at IS NULL)
//	  AND (COALESCE($3, '') = '' OR us.name = $3)
//	AND (
//	  $4::text IS NULL
//	  OR $5::timestamp IS NULL
//	  OR $6::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $4::text = 'created_at' THEN u.created_at
//	      WHEN $4::text = 'updated_at' THEN u.updated_at
//	      WHEN $4::text = 'deleted_at' THEN u.deleted_at
//	    END BETWEEN $5::timestamp AND $6::timestamp
//	  )
//	)
//	ORDER BY
//	  -- Sort by 'created_at'
//	  CASE WHEN $7::text = 'created_at' AND $8::text = 'ASC'
//	    THEN u.created_at END ASC,
//	  CASE WHEN $7::text = 'created_at' AND $8::text = 'DESC'
//	    THEN u.created_at END DESC,
//
//	  -- Sort by 'updated_at'
//	  CASE WHEN $7::text = 'updated_at' AND $8::text = 'ASC'
//	    THEN u.updated_at END ASC,
//	  CASE WHEN $7::text = 'updated_at' AND $8::text = 'DESC'
//	    THEN u.updated_at END DESC,
//
//	  -- Sort by 'deleted_at'
//	  CASE WHEN $7::text = 'deleted_at' AND $8::text = 'ASC'
//	    THEN u.deleted_at END ASC,
//	  CASE WHEN $7::text = 'deleted_at' AND $8::text = 'DESC'
//	    THEN u.deleted_at END DESC
//	LIMIT $10
//	OFFSET $9
func (q *Queries) QueryAllUrlsByUserId(ctx context.Context, arg QueryAllUrlsByUserIdParams) ([]QueryAllUrlsByUserIdRow, error) {
	rows, err := q.db.Query(ctx, queryAllUrlsByUserId,
		arg.UserID,
		arg.IncludeDeleted,
		arg.UrlStatus,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllUrlsByUserIdRow
	for rows.Next() {
		var i QueryAllUrlsByUserIdRow
		if err := rows.Scan(
			&i.Url.ID,
			&i.Url.UserID,
			&i.Url.ShortCode,
			&i.Url.CustomAlias,
			&i.Url.OriginalUrl,
			&i.Url.StatusID,
			&i.Url.ExpiresOn,
			&i.Url.OgTitle,
			&i.Url.OgDescription,
			&i.Url.OgImageUrl,
			&i.Url.Metadata,
			&i.Url.CreatedAt,
			&i.Url.UpdatedAt,
			&i.Url.DeletedAt,
			&i.UrlStatus.ID,
			&i.UrlStatus.Name,
			&i.UrlStatus.Description,
			&i.UrlStatus.CreatedAt,
			&i.UrlStatus.UpdatedAt,
			&i.UrlStatus.DeletedAt,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryUrlByCustomAlias = `-- name: QueryUrlByCustomAlias :one
SELECT 
  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at, 
  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at 
FROM urls u
JOIN url_status us ON u.status_id = us.id
WHERE u.custom_alias = $1
`

type QueryUrlByCustomAliasRow struct {
	Url       Url       `db:"url" json:"url"`
	UrlStatus UrlStatus `db:"url_status" json:"url_status"`
}

// QueryUrlByCustomAlias
//
//	SELECT
//	  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at,
//	  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at
//	FROM urls u
//	JOIN url_status us ON u.status_id = us.id
//	WHERE u.custom_alias = $1
func (q *Queries) QueryUrlByCustomAlias(ctx context.Context, customAlias pgtype.Text) (QueryUrlByCustomAliasRow, error) {
	row := q.db.QueryRow(ctx, queryUrlByCustomAlias, customAlias)
	var i QueryUrlByCustomAliasRow
	err := row.Scan(
		&i.Url.ID,
		&i.Url.UserID,
		&i.Url.ShortCode,
		&i.Url.CustomAlias,
		&i.Url.OriginalUrl,
		&i.Url.StatusID,
		&i.Url.ExpiresOn,
		&i.Url.OgTitle,
		&i.Url.OgDescription,
		&i.Url.OgImageUrl,
		&i.Url.Metadata,
		&i.Url.CreatedAt,
		&i.Url.UpdatedAt,
		&i.Url.DeletedAt,
		&i.UrlStatus.ID,
		&i.UrlStatus.Name,
		&i.UrlStatus.Description,
		&i.UrlStatus.CreatedAt,
		&i.UrlStatus.UpdatedAt,
		&i.UrlStatus.DeletedAt,
	)
	return i, err
}

const queryUrlById = `-- name: QueryUrlById :one
SELECT 
  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at,
  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at
FROM urls u
JOIN url_status us ON u.status_id = us.id 
WHERE u.id = $1
`

type QueryUrlByIdRow struct {
	Url       Url       `db:"url" json:"url"`
	UrlStatus UrlStatus `db:"url_status" json:"url_status"`
}

// QueryUrlById
//
//	SELECT
//	  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at,
//	  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at
//	FROM urls u
//	JOIN url_status us ON u.status_id = us.id
//	WHERE u.id = $1
func (q *Queries) QueryUrlById(ctx context.Context, id pgtype.UUID) (QueryUrlByIdRow, error) {
	row := q.db.QueryRow(ctx, queryUrlById, id)
	var i QueryUrlByIdRow
	err := row.Scan(
		&i.Url.ID,
		&i.Url.UserID,
		&i.Url.ShortCode,
		&i.Url.CustomAlias,
		&i.Url.OriginalUrl,
		&i.Url.StatusID,
		&i.Url.ExpiresOn,
		&i.Url.OgTitle,
		&i.Url.OgDescription,
		&i.Url.OgImageUrl,
		&i.Url.Metadata,
		&i.Url.CreatedAt,
		&i.Url.UpdatedAt,
		&i.Url.DeletedAt,
		&i.UrlStatus.ID,
		&i.UrlStatus.Name,
		&i.UrlStatus.Description,
		&i.UrlStatus.CreatedAt,
		&i.UrlStatus.UpdatedAt,
		&i.UrlStatus.DeletedAt,
	)
	return i, err
}

const queryUrlByUrlShortCode = `-- name: QueryUrlByUrlShortCode :one
SELECT 
  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at, 
  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at 
FROM urls u 
JOIN url_status us ON u.status_id = us.id
WHERE u.short_code = $1
`

type QueryUrlByUrlShortCodeRow struct {
	Url       Url       `db:"url" json:"url"`
	UrlStatus UrlStatus `db:"url_status" json:"url_status"`
}

// QueryUrlByUrlShortCode
//
//	SELECT
//	  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at,
//	  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at
//	FROM urls u
//	JOIN url_status us ON u.status_id = us.id
//	WHERE u.short_code = $1
func (q *Queries) QueryUrlByUrlShortCode(ctx context.Context, shortCode string) (QueryUrlByUrlShortCodeRow, error) {
	row := q.db.QueryRow(ctx, queryUrlByUrlShortCode, shortCode)
	var i QueryUrlByUrlShortCodeRow
	err := row.Scan(
		&i.Url.ID,
		&i.Url.UserID,
		&i.Url.ShortCode,
		&i.Url.CustomAlias,
		&i.Url.OriginalUrl,
		&i.Url.StatusID,
		&i.Url.ExpiresOn,
		&i.Url.OgTitle,
		&i.Url.OgDescription,
		&i.Url.OgImageUrl,
		&i.Url.Metadata,
		&i.Url.CreatedAt,
		&i.Url.UpdatedAt,
		&i.Url.DeletedAt,
		&i.UrlStatus.ID,
		&i.UrlStatus.Name,
		&i.UrlStatus.Description,
		&i.UrlStatus.CreatedAt,
		&i.UrlStatus.UpdatedAt,
		&i.UrlStatus.DeletedAt,
	)
	return i, err
}
