// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: url_scans_read_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryAllUrlScans = `-- name: QueryAllUrlScans :many
SELECT 
  us.id, us.url_id, us.provider, us.result, us.raw_response, us.scanned_at, us.created_at, us.updated_at, us.deleted_at,
  COUNT(*) OVER() AS total_records
FROM url_scans us 
WHERE $1::bool OR us.deleted_at IS NULL
  AND (COALESCE($2, '') = '' OR us.name = $2)
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN us.created_at
      WHEN $3::text = 'updated_at' THEN us.updated_at
      WHEN $3::text = 'deleted_at' THEN us.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  -- Sort by 'created_at'
  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC' 
    THEN us.created_at END ASC,
  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC' 
    THEN us.created_at END DESC,
  
  -- Sort by 'updated_at'
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC' 
    THEN us.updated_at END ASC,
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC' 
    THEN us.updated_at END DESC,
  
  -- Sort by 'deleted_at'
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC' 
    THEN us.deleted_at END ASC,
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC' 
    THEN us.deleted_at END DESC
LIMIT $9
OFFSET $8
`

type QueryAllUrlScansParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	UrlStatus      interface{}      `db:"url_status" json:"url_status"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryAllUrlScansRow struct {
	UrlScan      UrlScan `db:"url_scan" json:"url_scan"`
	TotalRecords int64   `db:"total_records" json:"total_records"`
}

// Date range filtering
//
//	SELECT
//	  us.id, us.url_id, us.provider, us.result, us.raw_response, us.scanned_at, us.created_at, us.updated_at, us.deleted_at,
//	  COUNT(*) OVER() AS total_records
//	FROM url_scans us
//	WHERE $1::bool OR us.deleted_at IS NULL
//	  AND (COALESCE($2, '') = '' OR us.name = $2)
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN us.created_at
//	      WHEN $3::text = 'updated_at' THEN us.updated_at
//	      WHEN $3::text = 'deleted_at' THEN us.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  -- Sort by 'created_at'
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC'
//	    THEN us.created_at END ASC,
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC'
//	    THEN us.created_at END DESC,
//
//	  -- Sort by 'updated_at'
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC'
//	    THEN us.updated_at END ASC,
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC'
//	    THEN us.updated_at END DESC,
//
//	  -- Sort by 'deleted_at'
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC'
//	    THEN us.deleted_at END ASC,
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC'
//	    THEN us.deleted_at END DESC
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryAllUrlScans(ctx context.Context, arg QueryAllUrlScansParams) ([]QueryAllUrlScansRow, error) {
	rows, err := q.db.Query(ctx, queryAllUrlScans,
		arg.IncludeDeleted,
		arg.UrlStatus,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllUrlScansRow
	for rows.Next() {
		var i QueryAllUrlScansRow
		if err := rows.Scan(
			&i.UrlScan.ID,
			&i.UrlScan.UrlID,
			&i.UrlScan.Provider,
			&i.UrlScan.Result,
			&i.UrlScan.RawResponse,
			&i.UrlScan.ScannedAt,
			&i.UrlScan.CreatedAt,
			&i.UrlScan.UpdatedAt,
			&i.UrlScan.DeletedAt,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAllUrlScansByUrlId = `-- name: QueryAllUrlScansByUrlId :many
SELECT 
  us.id, us.url_id, us.provider, us.result, us.raw_response, us.scanned_at, us.created_at, us.updated_at, us.deleted_at,
  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at,
  COUNT(*) OVER() AS total_records
FROM url_scans us 
JOIN urls u ON us.url_id = u.id
WHERE us.url_id = $1
  AND ($2::bool OR us.deleted_at IS NULL)
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN us.created_at
      WHEN $3::text = 'updated_at' THEN us.updated_at
      WHEN $3::text = 'deleted_at' THEN us.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  -- Sort by 'created_at'
  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC' 
    THEN us.created_at END ASC,
  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC' 
    THEN us.created_at END DESC,
  
  -- Sort by 'updated_at'
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC' 
    THEN us.updated_at END ASC,
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC' 
    THEN us.updated_at END DESC,
  
  -- Sort by 'deleted_at'
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC' 
    THEN us.deleted_at END ASC,
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC' 
    THEN us.deleted_at END DESC
LIMIT $9
OFFSET $8
`

type QueryAllUrlScansByUrlIdParams struct {
	UrlID          pgtype.UUID      `db:"url_id" json:"url_id"`
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryAllUrlScansByUrlIdRow struct {
	UrlScan      UrlScan `db:"url_scan" json:"url_scan"`
	Url          Url     `db:"url" json:"url"`
	TotalRecords int64   `db:"total_records" json:"total_records"`
}

// Date range filtering
//
//	SELECT
//	  us.id, us.url_id, us.provider, us.result, us.raw_response, us.scanned_at, us.created_at, us.updated_at, us.deleted_at,
//	  u.id, u.user_id, u.short_code, u.custom_alias, u.original_url, u.status_id, u.expires_on, u.og_title, u.og_description, u.og_image_url, u.metadata, u.created_at, u.updated_at, u.deleted_at,
//	  COUNT(*) OVER() AS total_records
//	FROM url_scans us
//	JOIN urls u ON us.url_id = u.id
//	WHERE us.url_id = $1
//	  AND ($2::bool OR us.deleted_at IS NULL)
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN us.created_at
//	      WHEN $3::text = 'updated_at' THEN us.updated_at
//	      WHEN $3::text = 'deleted_at' THEN us.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  -- Sort by 'created_at'
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC'
//	    THEN us.created_at END ASC,
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC'
//	    THEN us.created_at END DESC,
//
//	  -- Sort by 'updated_at'
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC'
//	    THEN us.updated_at END ASC,
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC'
//	    THEN us.updated_at END DESC,
//
//	  -- Sort by 'deleted_at'
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC'
//	    THEN us.deleted_at END ASC,
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC'
//	    THEN us.deleted_at END DESC
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryAllUrlScansByUrlId(ctx context.Context, arg QueryAllUrlScansByUrlIdParams) ([]QueryAllUrlScansByUrlIdRow, error) {
	rows, err := q.db.Query(ctx, queryAllUrlScansByUrlId,
		arg.UrlID,
		arg.IncludeDeleted,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllUrlScansByUrlIdRow
	for rows.Next() {
		var i QueryAllUrlScansByUrlIdRow
		if err := rows.Scan(
			&i.UrlScan.ID,
			&i.UrlScan.UrlID,
			&i.UrlScan.Provider,
			&i.UrlScan.Result,
			&i.UrlScan.RawResponse,
			&i.UrlScan.ScannedAt,
			&i.UrlScan.CreatedAt,
			&i.UrlScan.UpdatedAt,
			&i.UrlScan.DeletedAt,
			&i.Url.ID,
			&i.Url.UserID,
			&i.Url.ShortCode,
			&i.Url.CustomAlias,
			&i.Url.OriginalUrl,
			&i.Url.StatusID,
			&i.Url.ExpiresOn,
			&i.Url.OgTitle,
			&i.Url.OgDescription,
			&i.Url.OgImageUrl,
			&i.Url.Metadata,
			&i.Url.CreatedAt,
			&i.Url.UpdatedAt,
			&i.Url.DeletedAt,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryUrlScanById = `-- name: QueryUrlScanById :one
SELECT 
  us.id, us.url_id, us.provider, us.result, us.raw_response, us.scanned_at, us.created_at, us.updated_at, us.deleted_at
FROM url_scans us
WHERE us.id = $1
`

type QueryUrlScanByIdRow struct {
	UrlScan UrlScan `db:"url_scan" json:"url_scan"`
}

// QueryUrlScanById
//
//	SELECT
//	  us.id, us.url_id, us.provider, us.result, us.raw_response, us.scanned_at, us.created_at, us.updated_at, us.deleted_at
//	FROM url_scans us
//	WHERE us.id = $1
func (q *Queries) QueryUrlScanById(ctx context.Context, id pgtype.UUID) (QueryUrlScanByIdRow, error) {
	row := q.db.QueryRow(ctx, queryUrlScanById, id)
	var i QueryUrlScanByIdRow
	err := row.Scan(
		&i.UrlScan.ID,
		&i.UrlScan.UrlID,
		&i.UrlScan.Provider,
		&i.UrlScan.Result,
		&i.UrlScan.RawResponse,
		&i.UrlScan.ScannedAt,
		&i.UrlScan.CreatedAt,
		&i.UrlScan.UpdatedAt,
		&i.UrlScan.DeletedAt,
	)
	return i, err
}

const queryUrlScanByProvider = `-- name: QueryUrlScanByProvider :many
SELECT 
  us.id, us.url_id, us.provider, us.result, us.raw_response, us.scanned_at, us.created_at, us.updated_at, us.deleted_at
FROM url_scans us
WHERE us.provider = $1
AND $2::bool OR us.deleted_at IS NULL
  AND (COALESCE($3, '') = '' OR us.name = $3)
AND (
  $4::text IS NULL
  OR $5::timestamp IS NULL
  OR $6::timestamp IS NULL
  OR (
    CASE 
      WHEN $4::text = 'created_at' THEN us.created_at
      WHEN $4::text = 'updated_at' THEN us.updated_at
      WHEN $4::text = 'deleted_at' THEN us.deleted_at
    END BETWEEN $5::timestamp AND $6::timestamp
  )
)
ORDER BY
  -- Sort by 'created_at'
  CASE WHEN $7::text = 'created_at' AND $8::text = 'ASC' 
    THEN us.created_at END ASC,
  CASE WHEN $7::text = 'created_at' AND $8::text = 'DESC' 
    THEN us.created_at END DESC,
  
  -- Sort by 'updated_at'
  CASE WHEN $7::text = 'updated_at' AND $8::text = 'ASC' 
    THEN us.updated_at END ASC,
  CASE WHEN $7::text = 'updated_at' AND $8::text = 'DESC' 
    THEN us.updated_at END DESC,
  
  -- Sort by 'deleted_at'
  CASE WHEN $7::text = 'deleted_at' AND $8::text = 'ASC' 
    THEN us.deleted_at END ASC,
  CASE WHEN $7::text = 'deleted_at' AND $8::text = 'DESC' 
    THEN us.deleted_at END DESC
LIMIT $10
OFFSET $9
`

type QueryUrlScanByProviderParams struct {
	Provider       string           `db:"provider" json:"provider"`
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	UrlStatus      interface{}      `db:"url_status" json:"url_status"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryUrlScanByProviderRow struct {
	UrlScan UrlScan `db:"url_scan" json:"url_scan"`
}

// Date range filtering
//
//	SELECT
//	  us.id, us.url_id, us.provider, us.result, us.raw_response, us.scanned_at, us.created_at, us.updated_at, us.deleted_at
//	FROM url_scans us
//	WHERE us.provider = $1
//	AND $2::bool OR us.deleted_at IS NULL
//	  AND (COALESCE($3, '') = '' OR us.name = $3)
//	AND (
//	  $4::text IS NULL
//	  OR $5::timestamp IS NULL
//	  OR $6::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $4::text = 'created_at' THEN us.created_at
//	      WHEN $4::text = 'updated_at' THEN us.updated_at
//	      WHEN $4::text = 'deleted_at' THEN us.deleted_at
//	    END BETWEEN $5::timestamp AND $6::timestamp
//	  )
//	)
//	ORDER BY
//	  -- Sort by 'created_at'
//	  CASE WHEN $7::text = 'created_at' AND $8::text = 'ASC'
//	    THEN us.created_at END ASC,
//	  CASE WHEN $7::text = 'created_at' AND $8::text = 'DESC'
//	    THEN us.created_at END DESC,
//
//	  -- Sort by 'updated_at'
//	  CASE WHEN $7::text = 'updated_at' AND $8::text = 'ASC'
//	    THEN us.updated_at END ASC,
//	  CASE WHEN $7::text = 'updated_at' AND $8::text = 'DESC'
//	    THEN us.updated_at END DESC,
//
//	  -- Sort by 'deleted_at'
//	  CASE WHEN $7::text = 'deleted_at' AND $8::text = 'ASC'
//	    THEN us.deleted_at END ASC,
//	  CASE WHEN $7::text = 'deleted_at' AND $8::text = 'DESC'
//	    THEN us.deleted_at END DESC
//	LIMIT $10
//	OFFSET $9
func (q *Queries) QueryUrlScanByProvider(ctx context.Context, arg QueryUrlScanByProviderParams) ([]QueryUrlScanByProviderRow, error) {
	rows, err := q.db.Query(ctx, queryUrlScanByProvider,
		arg.Provider,
		arg.IncludeDeleted,
		arg.UrlStatus,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryUrlScanByProviderRow
	for rows.Next() {
		var i QueryUrlScanByProviderRow
		if err := rows.Scan(
			&i.UrlScan.ID,
			&i.UrlScan.UrlID,
			&i.UrlScan.Provider,
			&i.UrlScan.Result,
			&i.UrlScan.RawResponse,
			&i.UrlScan.ScannedAt,
			&i.UrlScan.CreatedAt,
			&i.UrlScan.UpdatedAt,
			&i.UrlScan.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
