// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: url_write_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryCreateUrl = `-- name: QueryCreateUrl :one
INSERT INTO urls (
  user_id, 
  short_code, 
  custom_alias, 
  original_url, 
  status_id, 
  expires_on, 
  og_title, 
  og_description, 
  og_image_url
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
`

type QueryCreateUrlParams struct {
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	ShortCode     string             `db:"short_code" json:"short_code"`
	CustomAlias   pgtype.Text        `db:"custom_alias" json:"custom_alias"`
	OriginalUrl   string             `db:"original_url" json:"original_url"`
	StatusID      pgtype.UUID        `db:"status_id" json:"status_id"`
	ExpiresOn     pgtype.Timestamptz `db:"expires_on" json:"expires_on"`
	OgTitle       pgtype.Text        `db:"og_title" json:"og_title"`
	OgDescription pgtype.Text        `db:"og_description" json:"og_description"`
	OgImageUrl    pgtype.Text        `db:"og_image_url" json:"og_image_url"`
}

// QueryCreateUrl
//
//	INSERT INTO urls (
//	  user_id,
//	  short_code,
//	  custom_alias,
//	  original_url,
//	  status_id,
//	  expires_on,
//	  og_title,
//	  og_description,
//	  og_image_url
//	)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
func (q *Queries) QueryCreateUrl(ctx context.Context, arg QueryCreateUrlParams) (Url, error) {
	row := q.db.QueryRow(ctx, queryCreateUrl,
		arg.UserID,
		arg.ShortCode,
		arg.CustomAlias,
		arg.OriginalUrl,
		arg.StatusID,
		arg.ExpiresOn,
		arg.OgTitle,
		arg.OgDescription,
		arg.OgImageUrl,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.CustomAlias,
		&i.OriginalUrl,
		&i.StatusID,
		&i.ExpiresOn,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImageUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryDeleteUrlWithId = `-- name: QueryDeleteUrlWithId :one
DELETE FROM urls WHERE id = $1 RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
`

// QueryDeleteUrlWithId
//
//	DELETE FROM urls WHERE id = $1 RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
func (q *Queries) QueryDeleteUrlWithId(ctx context.Context, id pgtype.UUID) (Url, error) {
	row := q.db.QueryRow(ctx, queryDeleteUrlWithId, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.CustomAlias,
		&i.OriginalUrl,
		&i.StatusID,
		&i.ExpiresOn,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImageUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const querySoftDeleteUrl = `-- name: QuerySoftDeleteUrl :one
UPDATE urls
SET
  deleted_at = $2,
  updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
`

type QuerySoftDeleteUrlParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// QuerySoftDeleteUrl
//
//	UPDATE urls
//	SET
//	  deleted_at = $2,
//	  updated_at = NOW()
//	WHERE id = $1 RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
func (q *Queries) QuerySoftDeleteUrl(ctx context.Context, arg QuerySoftDeleteUrlParams) (Url, error) {
	row := q.db.QueryRow(ctx, querySoftDeleteUrl, arg.ID, arg.DeletedAt)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.CustomAlias,
		&i.OriginalUrl,
		&i.StatusID,
		&i.ExpiresOn,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImageUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateUrlDetails = `-- name: QueryUpdateUrlDetails :one
UPDATE urls
SET
  short_code=$2,
  custom_alias=$3,
  updated_at=NOW()
WHERE id = $1 RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
`

type QueryUpdateUrlDetailsParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	ShortCode   string      `db:"short_code" json:"short_code"`
	CustomAlias pgtype.Text `db:"custom_alias" json:"custom_alias"`
}

// QueryUpdateUrlDetails
//
//	UPDATE urls
//	SET
//	  short_code=$2,
//	  custom_alias=$3,
//	  updated_at=NOW()
//	WHERE id = $1 RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateUrlDetails(ctx context.Context, arg QueryUpdateUrlDetailsParams) (Url, error) {
	row := q.db.QueryRow(ctx, queryUpdateUrlDetails, arg.ID, arg.ShortCode, arg.CustomAlias)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.CustomAlias,
		&i.OriginalUrl,
		&i.StatusID,
		&i.ExpiresOn,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImageUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateUrlExpiresOn = `-- name: QueryUpdateUrlExpiresOn :one
UPDATE urls SET expires_on=$2, updated_at=NOW() WHERE id = $1 RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
`

type QueryUpdateUrlExpiresOnParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	ExpiresOn pgtype.Timestamptz `db:"expires_on" json:"expires_on"`
}

// QueryUpdateUrlExpiresOn
//
//	UPDATE urls SET expires_on=$2, updated_at=NOW() WHERE id = $1 RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateUrlExpiresOn(ctx context.Context, arg QueryUpdateUrlExpiresOnParams) (Url, error) {
	row := q.db.QueryRow(ctx, queryUpdateUrlExpiresOn, arg.ID, arg.ExpiresOn)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.CustomAlias,
		&i.OriginalUrl,
		&i.StatusID,
		&i.ExpiresOn,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImageUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateUrlMetadata = `-- name: QueryUpdateUrlMetadata :one
UPDATE urls SET metadata=$2, updated_at=NOW() WHERE id = $1 RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
`

type QueryUpdateUrlMetadataParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Metadata []byte      `db:"metadata" json:"metadata"`
}

// QueryUpdateUrlMetadata
//
//	UPDATE urls SET metadata=$2, updated_at=NOW() WHERE id = $1 RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateUrlMetadata(ctx context.Context, arg QueryUpdateUrlMetadataParams) (Url, error) {
	row := q.db.QueryRow(ctx, queryUpdateUrlMetadata, arg.ID, arg.Metadata)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.CustomAlias,
		&i.OriginalUrl,
		&i.StatusID,
		&i.ExpiresOn,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImageUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateUrlStatus = `-- name: QueryUpdateUrlStatus :one
UPDATE urls
SET
  status_id=$2,
  updated_at=NOW()
WHERE id = $1 RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
`

type QueryUpdateUrlStatusParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	StatusID pgtype.UUID `db:"status_id" json:"status_id"`
}

// QueryUpdateUrlStatus
//
//	UPDATE urls
//	SET
//	  status_id=$2,
//	  updated_at=NOW()
//	WHERE id = $1 RETURNING id, user_id, short_code, custom_alias, original_url, status_id, expires_on, og_title, og_description, og_image_url, metadata, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateUrlStatus(ctx context.Context, arg QueryUpdateUrlStatusParams) (Url, error) {
	row := q.db.QueryRow(ctx, queryUpdateUrlStatus, arg.ID, arg.StatusID)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.CustomAlias,
		&i.OriginalUrl,
		&i.StatusID,
		&i.ExpiresOn,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImageUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
