// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users_read_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryAllUsers = `-- name: QueryAllUsers :many
SELECT 
  u.id, u.username, u.first_name, u.last_name, u.email, u.password_hash, u.verified, u.verification_token, u.verification_expires, u.status_id, u.metadata, u.created_at, u.updated_at, u.deleted_at,
  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at,
  COUNT(*) OVER() AS total_records
FROM users u 
JOIN user_status us ON u.status_id = us.id
WHERE $1::bool OR u.deleted_at IS NULL
  AND (COALESCE($2, '') = '' OR us.name = $2)
AND (
  $3::text IS NULL
  OR $4::timestamp IS NULL
  OR $5::timestamp IS NULL
  OR (
    CASE 
      WHEN $3::text = 'created_at' THEN u.created_at
      WHEN $3::text = 'updated_at' THEN u.updated_at
      WHEN $3::text = 'deleted_at' THEN u.deleted_at
    END BETWEEN $4::timestamp AND $5::timestamp
  )
)
ORDER BY
  -- Sort by 'created_at'
  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC' 
    THEN u.created_at END ASC,
  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC' 
    THEN u.created_at END DESC,
  
  -- Sort by 'updated_at'
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC' 
    THEN u.updated_at END ASC,
  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC' 
    THEN u.updated_at END DESC,
  
  -- Sort by 'deleted_at'
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC' 
    THEN u.deleted_at END ASC,
  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC' 
    THEN u.deleted_at END DESC
LIMIT $9
OFFSET $8
`

type QueryAllUsersParams struct {
	IncludeDeleted bool             `db:"include_deleted" json:"include_deleted"`
	UserStatus     interface{}      `db:"user_status" json:"user_status"`
	DateField      pgtype.Text      `db:"date_field" json:"date_field"`
	DateFrom       pgtype.Timestamp `db:"date_from" json:"date_from"`
	DateTo         pgtype.Timestamp `db:"date_to" json:"date_to"`
	OrderBy        string           `db:"order_by" json:"order_by"`
	SortOrder      string           `db:"sort_order" json:"sort_order"`
	CurrentOffset  int32            `db:"current_offset" json:"current_offset"`
	LimitBy        int32            `db:"limit_by" json:"limit_by"`
}

type QueryAllUsersRow struct {
	User         User       `db:"user" json:"user"`
	UserStatus   UserStatus `db:"user_status" json:"user_status"`
	TotalRecords int64      `db:"total_records" json:"total_records"`
}

// Date range filtering
//
//	SELECT
//	  u.id, u.username, u.first_name, u.last_name, u.email, u.password_hash, u.verified, u.verification_token, u.verification_expires, u.status_id, u.metadata, u.created_at, u.updated_at, u.deleted_at,
//	  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at,
//	  COUNT(*) OVER() AS total_records
//	FROM users u
//	JOIN user_status us ON u.status_id = us.id
//	WHERE $1::bool OR u.deleted_at IS NULL
//	  AND (COALESCE($2, '') = '' OR us.name = $2)
//	AND (
//	  $3::text IS NULL
//	  OR $4::timestamp IS NULL
//	  OR $5::timestamp IS NULL
//	  OR (
//	    CASE
//	      WHEN $3::text = 'created_at' THEN u.created_at
//	      WHEN $3::text = 'updated_at' THEN u.updated_at
//	      WHEN $3::text = 'deleted_at' THEN u.deleted_at
//	    END BETWEEN $4::timestamp AND $5::timestamp
//	  )
//	)
//	ORDER BY
//	  -- Sort by 'created_at'
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'ASC'
//	    THEN u.created_at END ASC,
//	  CASE WHEN $6::text = 'created_at' AND $7::text = 'DESC'
//	    THEN u.created_at END DESC,
//
//	  -- Sort by 'updated_at'
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'ASC'
//	    THEN u.updated_at END ASC,
//	  CASE WHEN $6::text = 'updated_at' AND $7::text = 'DESC'
//	    THEN u.updated_at END DESC,
//
//	  -- Sort by 'deleted_at'
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'ASC'
//	    THEN u.deleted_at END ASC,
//	  CASE WHEN $6::text = 'deleted_at' AND $7::text = 'DESC'
//	    THEN u.deleted_at END DESC
//	LIMIT $9
//	OFFSET $8
func (q *Queries) QueryAllUsers(ctx context.Context, arg QueryAllUsersParams) ([]QueryAllUsersRow, error) {
	rows, err := q.db.Query(ctx, queryAllUsers,
		arg.IncludeDeleted,
		arg.UserStatus,
		arg.DateField,
		arg.DateFrom,
		arg.DateTo,
		arg.OrderBy,
		arg.SortOrder,
		arg.CurrentOffset,
		arg.LimitBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllUsersRow
	for rows.Next() {
		var i QueryAllUsersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.Verified,
			&i.User.VerificationToken,
			&i.User.VerificationExpires,
			&i.User.StatusID,
			&i.User.Metadata,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
			&i.UserStatus.ID,
			&i.UserStatus.Name,
			&i.UserStatus.Description,
			&i.UserStatus.CreatedAt,
			&i.UserStatus.UpdatedAt,
			&i.UserStatus.DeletedAt,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryUserByEmail = `-- name: QueryUserByEmail :one
SELECT 
  u.id, u.username, u.first_name, u.last_name, u.email, u.password_hash, u.verified, u.verification_token, u.verification_expires, u.status_id, u.metadata, u.created_at, u.updated_at, u.deleted_at, 
  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at 
FROM users u
JOIN user_status us ON u.status_id = us.id
WHERE u.email = $1
`

type QueryUserByEmailRow struct {
	User       User       `db:"user" json:"user"`
	UserStatus UserStatus `db:"user_status" json:"user_status"`
}

// QueryUserByEmail
//
//	SELECT
//	  u.id, u.username, u.first_name, u.last_name, u.email, u.password_hash, u.verified, u.verification_token, u.verification_expires, u.status_id, u.metadata, u.created_at, u.updated_at, u.deleted_at,
//	  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at
//	FROM users u
//	JOIN user_status us ON u.status_id = us.id
//	WHERE u.email = $1
func (q *Queries) QueryUserByEmail(ctx context.Context, email string) (QueryUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, queryUserByEmail, email)
	var i QueryUserByEmailRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Username,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.Verified,
		&i.User.VerificationToken,
		&i.User.VerificationExpires,
		&i.User.StatusID,
		&i.User.Metadata,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
		&i.UserStatus.ID,
		&i.UserStatus.Name,
		&i.UserStatus.Description,
		&i.UserStatus.CreatedAt,
		&i.UserStatus.UpdatedAt,
		&i.UserStatus.DeletedAt,
	)
	return i, err
}

const queryUserById = `-- name: QueryUserById :one
SELECT 
  u.id, u.username, u.first_name, u.last_name, u.email, u.password_hash, u.verified, u.verification_token, u.verification_expires, u.status_id, u.metadata, u.created_at, u.updated_at, u.deleted_at,
  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at
FROM users u
JOIN user_status us ON u.status_id = us.id 
WHERE u.id = $1
`

type QueryUserByIdRow struct {
	User       User       `db:"user" json:"user"`
	UserStatus UserStatus `db:"user_status" json:"user_status"`
}

// QueryUserById
//
//	SELECT
//	  u.id, u.username, u.first_name, u.last_name, u.email, u.password_hash, u.verified, u.verification_token, u.verification_expires, u.status_id, u.metadata, u.created_at, u.updated_at, u.deleted_at,
//	  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at
//	FROM users u
//	JOIN user_status us ON u.status_id = us.id
//	WHERE u.id = $1
func (q *Queries) QueryUserById(ctx context.Context, id pgtype.UUID) (QueryUserByIdRow, error) {
	row := q.db.QueryRow(ctx, queryUserById, id)
	var i QueryUserByIdRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Username,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.Verified,
		&i.User.VerificationToken,
		&i.User.VerificationExpires,
		&i.User.StatusID,
		&i.User.Metadata,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
		&i.UserStatus.ID,
		&i.UserStatus.Name,
		&i.UserStatus.Description,
		&i.UserStatus.CreatedAt,
		&i.UserStatus.UpdatedAt,
		&i.UserStatus.DeletedAt,
	)
	return i, err
}

const queryUserByUsername = `-- name: QueryUserByUsername :one
SELECT 
  u.id, u.username, u.first_name, u.last_name, u.email, u.password_hash, u.verified, u.verification_token, u.verification_expires, u.status_id, u.metadata, u.created_at, u.updated_at, u.deleted_at, 
  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at 
FROM users u 
JOIN user_status us ON u.status_id = us.id
WHERE u.username = $1
`

type QueryUserByUsernameRow struct {
	User       User       `db:"user" json:"user"`
	UserStatus UserStatus `db:"user_status" json:"user_status"`
}

// QueryUserByUsername
//
//	SELECT
//	  u.id, u.username, u.first_name, u.last_name, u.email, u.password_hash, u.verified, u.verification_token, u.verification_expires, u.status_id, u.metadata, u.created_at, u.updated_at, u.deleted_at,
//	  us.id, us.name, us.description, us.created_at, us.updated_at, us.deleted_at
//	FROM users u
//	JOIN user_status us ON u.status_id = us.id
//	WHERE u.username = $1
func (q *Queries) QueryUserByUsername(ctx context.Context, username string) (QueryUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, queryUserByUsername, username)
	var i QueryUserByUsernameRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Username,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.Verified,
		&i.User.VerificationToken,
		&i.User.VerificationExpires,
		&i.User.StatusID,
		&i.User.Metadata,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
		&i.UserStatus.ID,
		&i.UserStatus.Name,
		&i.UserStatus.Description,
		&i.UserStatus.CreatedAt,
		&i.UserStatus.UpdatedAt,
		&i.UserStatus.DeletedAt,
	)
	return i, err
}
