// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users_write_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryCreateUser = `-- name: QueryCreateUser :one
INSERT INTO users (username, first_name, last_name, email, password_hash, status_id) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
`

type QueryCreateUserParams struct {
	Username     string      `db:"username" json:"username"`
	FirstName    pgtype.Text `db:"first_name" json:"first_name"`
	LastName     pgtype.Text `db:"last_name" json:"last_name"`
	Email        string      `db:"email" json:"email"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	StatusID     pgtype.UUID `db:"status_id" json:"status_id"`
}

// QueryCreateUser
//
//	INSERT INTO users (username, first_name, last_name, email, password_hash, status_id) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
func (q *Queries) QueryCreateUser(ctx context.Context, arg QueryCreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, queryCreateUser,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.StatusID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.VerificationToken,
		&i.VerificationExpires,
		&i.StatusID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryDeleteUserWithId = `-- name: QueryDeleteUserWithId :one
DELETE FROM users WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
`

// QueryDeleteUserWithId
//
//	DELETE FROM users WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
func (q *Queries) QueryDeleteUserWithId(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, queryDeleteUserWithId, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.VerificationToken,
		&i.VerificationExpires,
		&i.StatusID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const querySoftDeleteUser = `-- name: QuerySoftDeleteUser :one
UPDATE users
SET
  deleted_at = $2,
  updated_at = NOW()
WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
`

type QuerySoftDeleteUserParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// QuerySoftDeleteUser
//
//	UPDATE users
//	SET
//	  deleted_at = $2,
//	  updated_at = NOW()
//	WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
func (q *Queries) QuerySoftDeleteUser(ctx context.Context, arg QuerySoftDeleteUserParams) (User, error) {
	row := q.db.QueryRow(ctx, querySoftDeleteUser, arg.ID, arg.DeletedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.VerificationToken,
		&i.VerificationExpires,
		&i.StatusID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateUserDetails = `-- name: QueryUpdateUserDetails :one
UPDATE users
SET
  username=$2,
  first_name=$3,
  last_name=$4,
  email=$5,
  updated_at=NOW()
WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
`

type QueryUpdateUserDetailsParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	Username  string      `db:"username" json:"username"`
	FirstName pgtype.Text `db:"first_name" json:"first_name"`
	LastName  pgtype.Text `db:"last_name" json:"last_name"`
	Email     string      `db:"email" json:"email"`
}

// QueryUpdateUserDetails
//
//	UPDATE users
//	SET
//	  username=$2,
//	  first_name=$3,
//	  last_name=$4,
//	  email=$5,
//	  updated_at=NOW()
//	WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateUserDetails(ctx context.Context, arg QueryUpdateUserDetailsParams) (User, error) {
	row := q.db.QueryRow(ctx, queryUpdateUserDetails,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.VerificationToken,
		&i.VerificationExpires,
		&i.StatusID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateUserMetadata = `-- name: QueryUpdateUserMetadata :one
UPDATE users SET metadata=$2, updated_at=NOW() WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
`

type QueryUpdateUserMetadataParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Metadata []byte      `db:"metadata" json:"metadata"`
}

// QueryUpdateUserMetadata
//
//	UPDATE users SET metadata=$2, updated_at=NOW() WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateUserMetadata(ctx context.Context, arg QueryUpdateUserMetadataParams) (User, error) {
	row := q.db.QueryRow(ctx, queryUpdateUserMetadata, arg.ID, arg.Metadata)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.VerificationToken,
		&i.VerificationExpires,
		&i.StatusID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateUserPassword = `-- name: QueryUpdateUserPassword :one
UPDATE users SET password_hash=$2, updated_at=NOW() WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
`

type QueryUpdateUserPasswordParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
}

// QueryUpdateUserPassword
//
//	UPDATE users SET password_hash=$2, updated_at=NOW() WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateUserPassword(ctx context.Context, arg QueryUpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, queryUpdateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.VerificationToken,
		&i.VerificationExpires,
		&i.StatusID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateUserStatusId = `-- name: QueryUpdateUserStatusId :one
UPDATE users
SET
  status_id=$2,
  updated_at=NOW()
WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
`

type QueryUpdateUserStatusIdParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	StatusID pgtype.UUID `db:"status_id" json:"status_id"`
}

// QueryUpdateUserStatusId
//
//	UPDATE users
//	SET
//	  status_id=$2,
//	  updated_at=NOW()
//	WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateUserStatusId(ctx context.Context, arg QueryUpdateUserStatusIdParams) (User, error) {
	row := q.db.QueryRow(ctx, queryUpdateUserStatusId, arg.ID, arg.StatusID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.VerificationToken,
		&i.VerificationExpires,
		&i.StatusID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateUserVerification = `-- name: QueryUpdateUserVerification :one
UPDATE users
SET
  verified=$2,
  verification_token=$3,
  verification_expires=$4,
  updated_at=NOW()
WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
`

type QueryUpdateUserVerificationParams struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	Verified            bool               `db:"verified" json:"verified"`
	VerificationToken   pgtype.Text        `db:"verification_token" json:"verification_token"`
	VerificationExpires pgtype.Timestamptz `db:"verification_expires" json:"verification_expires"`
}

// QueryUpdateUserVerification
//
//	UPDATE users
//	SET
//	  verified=$2,
//	  verification_token=$3,
//	  verification_expires=$4,
//	  updated_at=NOW()
//	WHERE id = $1 RETURNING id, username, first_name, last_name, email, password_hash, verified, verification_token, verification_expires, status_id, metadata, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateUserVerification(ctx context.Context, arg QueryUpdateUserVerificationParams) (User, error) {
	row := q.db.QueryRow(ctx, queryUpdateUserVerification,
		arg.ID,
		arg.Verified,
		arg.VerificationToken,
		arg.VerificationExpires,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.VerificationToken,
		&i.VerificationExpires,
		&i.StatusID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
