// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_status_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryAllUserStatuses = `-- name: QueryAllUserStatuses :many
SELECT
  id,
  name,
  description,
  created_at,
  updated_at,
  deleted_at,
  COUNT(*) OVER() AS total_records
FROM user_status us
WHERE CASE 
  WHEN $1::bool=true THEN us.deleted_at IS NULL OR us.deleted_at IS NOT NULL
  WHEN $1::bool=false THEN us.deleted_at IS NULL
  ELSE us.deleted_at IS NULL
END
ORDER BY us.created_at DESC
LIMIT $3
OFFSET $2
`

type QueryAllUserStatusesParams struct {
	IncludeDeleted bool  `db:"include_deleted" json:"include_deleted"`
	CurrentOffset  int32 `db:"current_offset" json:"current_offset"`
	LimitBy        int32 `db:"limit_by" json:"limit_by"`
}

type QueryAllUserStatusesRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Description  pgtype.Text        `db:"description" json:"description"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	TotalRecords int64              `db:"total_records" json:"total_records"`
}

// QueryAllUserStatuses
//
//	SELECT
//	  id,
//	  name,
//	  description,
//	  created_at,
//	  updated_at,
//	  deleted_at,
//	  COUNT(*) OVER() AS total_records
//	FROM user_status us
//	WHERE CASE
//	  WHEN $1::bool=true THEN us.deleted_at IS NULL OR us.deleted_at IS NOT NULL
//	  WHEN $1::bool=false THEN us.deleted_at IS NULL
//	  ELSE us.deleted_at IS NULL
//	END
//	ORDER BY us.created_at DESC
//	LIMIT $3
//	OFFSET $2
func (q *Queries) QueryAllUserStatuses(ctx context.Context, arg QueryAllUserStatusesParams) ([]QueryAllUserStatusesRow, error) {
	rows, err := q.db.Query(ctx, queryAllUserStatuses, arg.IncludeDeleted, arg.CurrentOffset, arg.LimitBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAllUserStatusesRow
	for rows.Next() {
		var i QueryAllUserStatusesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalRecords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryCreateUserStatus = `-- name: QueryCreateUserStatus :one
INSERT INTO user_status (name, description) VALUES ($1, $2) RETURNING id, name, description, created_at, updated_at, deleted_at
`

type QueryCreateUserStatusParams struct {
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
}

// QueryCreateUserStatus
//
//	INSERT INTO user_status (name, description) VALUES ($1, $2) RETURNING id, name, description, created_at, updated_at, deleted_at
func (q *Queries) QueryCreateUserStatus(ctx context.Context, arg QueryCreateUserStatusParams) (UserStatus, error) {
	row := q.db.QueryRow(ctx, queryCreateUserStatus, arg.Name, arg.Description)
	var i UserStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryDeleteUserStatusWithId = `-- name: QueryDeleteUserStatusWithId :one
DELETE FROM user_status WHERE id = $1 RETURNING id, name, description, created_at, updated_at, deleted_at
`

// QueryDeleteUserStatusWithId
//
//	DELETE FROM user_status WHERE id = $1 RETURNING id, name, description, created_at, updated_at, deleted_at
func (q *Queries) QueryDeleteUserStatusWithId(ctx context.Context, id pgtype.UUID) (UserStatus, error) {
	row := q.db.QueryRow(ctx, queryDeleteUserStatusWithId, id)
	var i UserStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const querySoftDeleteUserStatus = `-- name: QuerySoftDeleteUserStatus :one
UPDATE user_status
SET
  deleted_at = $2
WHERE id = $1 RETURNING id, name, description, created_at, updated_at, deleted_at
`

type QuerySoftDeleteUserStatusParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// QuerySoftDeleteUserStatus
//
//	UPDATE user_status
//	SET
//	  deleted_at = $2
//	WHERE id = $1 RETURNING id, name, description, created_at, updated_at, deleted_at
func (q *Queries) QuerySoftDeleteUserStatus(ctx context.Context, arg QuerySoftDeleteUserStatusParams) (UserStatus, error) {
	row := q.db.QueryRow(ctx, querySoftDeleteUserStatus, arg.ID, arg.DeletedAt)
	var i UserStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateUserStatus = `-- name: QueryUpdateUserStatus :one
UPDATE user_status us
SET
  name=$2,
  description=$3
WHERE us.id = $1 RETURNING id, name, description, created_at, updated_at, deleted_at
`

type QueryUpdateUserStatusParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
}

// QueryUpdateUserStatus
//
//	UPDATE user_status us
//	SET
//	  name=$2,
//	  description=$3
//	WHERE us.id = $1 RETURNING id, name, description, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateUserStatus(ctx context.Context, arg QueryUpdateUserStatusParams) (UserStatus, error) {
	row := q.db.QueryRow(ctx, queryUpdateUserStatus, arg.ID, arg.Name, arg.Description)
	var i UserStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUserStatusById = `-- name: QueryUserStatusById :one
SELECT
  id,
  name,
  description,
  created_at, 
  updated_at,
  deleted_at
FROM user_status
WHERE id = $1
`

// QueryUserStatusById
//
//	SELECT
//	  id,
//	  name,
//	  description,
//	  created_at,
//	  updated_at,
//	  deleted_at
//	FROM user_status
//	WHERE id = $1
func (q *Queries) QueryUserStatusById(ctx context.Context, id pgtype.UUID) (UserStatus, error) {
	row := q.db.QueryRow(ctx, queryUserStatusById, id)
	var i UserStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUserStatusByName = `-- name: QueryUserStatusByName :one
SELECT
  id,
  name,
  description,
  created_at, 
  updated_at,
  deleted_at
FROM user_status
WHERE name = $1
`

// QueryUserStatusByName
//
//	SELECT
//	  id,
//	  name,
//	  description,
//	  created_at,
//	  updated_at,
//	  deleted_at
//	FROM user_status
//	WHERE name = $1
func (q *Queries) QueryUserStatusByName(ctx context.Context, name string) (UserStatus, error) {
	row := q.db.QueryRow(ctx, queryUserStatusByName, name)
	var i UserStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
