// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: webhooks_write_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryCreateWebhook = `-- name: QueryCreateWebhook :one
INSERT INTO webhooks (
  user_id,
  url_id, 
  endpoint, 
  secret, 
  events
)
VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
`

type QueryCreateWebhookParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	UrlID    pgtype.UUID `db:"url_id" json:"url_id"`
	Endpoint string      `db:"endpoint" json:"endpoint"`
	Secret   string      `db:"secret" json:"secret"`
	Events   []string    `db:"events" json:"events"`
}

// QueryCreateWebhook
//
//	INSERT INTO webhooks (
//	  user_id,
//	  url_id,
//	  endpoint,
//	  secret,
//	  events
//	)
//	VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
func (q *Queries) QueryCreateWebhook(ctx context.Context, arg QueryCreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, queryCreateWebhook,
		arg.UserID,
		arg.UrlID,
		arg.Endpoint,
		arg.Secret,
		arg.Events,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UrlID,
		&i.Endpoint,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryDeleteWebhookWithId = `-- name: QueryDeleteWebhookWithId :one
DELETE FROM webhooks WHERE id = $1 RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
`

// QueryDeleteWebhookWithId
//
//	DELETE FROM webhooks WHERE id = $1 RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
func (q *Queries) QueryDeleteWebhookWithId(ctx context.Context, id pgtype.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, queryDeleteWebhookWithId, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UrlID,
		&i.Endpoint,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const querySoftDeleteWebhook = `-- name: QuerySoftDeleteWebhook :one
UPDATE webhooks
SET
  deleted_at = $2,
  updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
`

type QuerySoftDeleteWebhookParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// QuerySoftDeleteWebhook
//
//	UPDATE webhooks
//	SET
//	  deleted_at = $2,
//	  updated_at = NOW()
//	WHERE id = $1 RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
func (q *Queries) QuerySoftDeleteWebhook(ctx context.Context, arg QuerySoftDeleteWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, querySoftDeleteWebhook, arg.ID, arg.DeletedAt)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UrlID,
		&i.Endpoint,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateWebhookActive = `-- name: QueryUpdateWebhookActive :one
UPDATE webhooks
SET
  active = $2,
  updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
`

type QueryUpdateWebhookActiveParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Active bool        `db:"active" json:"active"`
}

// QueryUpdateWebhookActive
//
//	UPDATE webhooks
//	SET
//	  active = $2,
//	  updated_at = NOW()
//	WHERE id = $1 RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateWebhookActive(ctx context.Context, arg QueryUpdateWebhookActiveParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, queryUpdateWebhookActive, arg.ID, arg.Active)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UrlID,
		&i.Endpoint,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateWebhookEndpoint = `-- name: QueryUpdateWebhookEndpoint :one
UPDATE webhooks
SET
  endpoint = $2,
  updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
`

type QueryUpdateWebhookEndpointParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Endpoint string      `db:"endpoint" json:"endpoint"`
}

// QueryUpdateWebhookEndpoint
//
//	UPDATE webhooks
//	SET
//	  endpoint = $2,
//	  updated_at = NOW()
//	WHERE id = $1 RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateWebhookEndpoint(ctx context.Context, arg QueryUpdateWebhookEndpointParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, queryUpdateWebhookEndpoint, arg.ID, arg.Endpoint)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UrlID,
		&i.Endpoint,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateWebhookEvent = `-- name: QueryUpdateWebhookEvent :one
UPDATE webhooks
SET
  events = $2,
  updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
`

type QueryUpdateWebhookEventParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Events []string    `db:"events" json:"events"`
}

// QueryUpdateWebhookEvent
//
//	UPDATE webhooks
//	SET
//	  events = $2,
//	  updated_at = NOW()
//	WHERE id = $1 RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateWebhookEvent(ctx context.Context, arg QueryUpdateWebhookEventParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, queryUpdateWebhookEvent, arg.ID, arg.Events)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UrlID,
		&i.Endpoint,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryUpdateWebhookSecret = `-- name: QueryUpdateWebhookSecret :one
UPDATE webhooks
SET
  secret = $2,
  updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
`

type QueryUpdateWebhookSecretParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Secret string      `db:"secret" json:"secret"`
}

// QueryUpdateWebhookSecret
//
//	UPDATE webhooks
//	SET
//	  secret = $2,
//	  updated_at = NOW()
//	WHERE id = $1 RETURNING id, user_id, url_id, endpoint, secret, events, active, created_at, updated_at, deleted_at
func (q *Queries) QueryUpdateWebhookSecret(ctx context.Context, arg QueryUpdateWebhookSecretParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, queryUpdateWebhookSecret, arg.ID, arg.Secret)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UrlID,
		&i.Endpoint,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
