// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/domain/identity/user_datastore.go
//
// Generated by this command:
//
//	mockgen -destination=app/internal/domain/identity/mocks/mock_user_datastore.go -package=mockidentity -source=app/internal/domain/identity/user_datastore.go
//

// Package mockidentity is a generated GoMock package.
package mockidentity

import (
	context "context"
	reflect "reflect"

	repository "github.com/sanctumlabs/curtz/app/internal/core/ports/repository"
	identity "github.com/sanctumlabs/curtz/app/internal/domain/identity"
	common "github.com/sanctumlabs/curtz/app/internal/pkg/common"
	gomock "go.uber.org/mock/gomock"
)

// MockUserDatastore is a mock of UserDatastore interface.
type MockUserDatastore struct {
	ctrl     *gomock.Controller
	recorder *MockUserDatastoreMockRecorder
	isgomock struct{}
}

// MockUserDatastoreMockRecorder is the mock recorder for MockUserDatastore.
type MockUserDatastoreMockRecorder struct {
	mock *MockUserDatastore
}

// NewMockUserDatastore creates a new mock instance.
func NewMockUserDatastore(ctrl *gomock.Controller) *MockUserDatastore {
	mock := &MockUserDatastore{ctrl: ctrl}
	mock.recorder = &MockUserDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDatastore) EXPECT() *MockUserDatastoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserDatastore) Create(ctx context.Context, request identity.CreateUserRequest) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserDatastoreMockRecorder) Create(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserDatastore)(nil).Create), ctx, request)
}

// Delete mocks base method.
func (m *MockUserDatastore) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserDatastoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserDatastore)(nil).Delete), ctx, id)
}

// FetchAll mocks base method.
func (m *MockUserDatastore) FetchAll(ctx context.Context, params common.RequestParams) (repository.FetchRecordsResponse[identity.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, params)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[identity.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUserDatastoreMockRecorder) FetchAll(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUserDatastore)(nil).FetchAll), ctx, params)
}

// FetchByEmail mocks base method.
func (m *MockUserDatastore) FetchByEmail(ctx context.Context, email string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByEmail", ctx, email)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByEmail indicates an expected call of FetchByEmail.
func (mr *MockUserDatastoreMockRecorder) FetchByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByEmail", reflect.TypeOf((*MockUserDatastore)(nil).FetchByEmail), ctx, email)
}

// FetchById mocks base method.
func (m *MockUserDatastore) FetchById(ctx context.Context, id string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchById", ctx, id)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchById indicates an expected call of FetchById.
func (mr *MockUserDatastoreMockRecorder) FetchById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchById", reflect.TypeOf((*MockUserDatastore)(nil).FetchById), ctx, id)
}

// FetchByStatus mocks base method.
func (m *MockUserDatastore) FetchByStatus(ctx context.Context, status identity.UserStatus) (repository.FetchRecordsResponse[identity.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByStatus", ctx, status)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[identity.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByStatus indicates an expected call of FetchByStatus.
func (mr *MockUserDatastoreMockRecorder) FetchByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByStatus", reflect.TypeOf((*MockUserDatastore)(nil).FetchByStatus), ctx, status)
}

// FetchByUsername mocks base method.
func (m *MockUserDatastore) FetchByUsername(ctx context.Context, username string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUsername", ctx, username)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUsername indicates an expected call of FetchByUsername.
func (mr *MockUserDatastoreMockRecorder) FetchByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUsername", reflect.TypeOf((*MockUserDatastore)(nil).FetchByUsername), ctx, username)
}

// FetchByVerificationToken mocks base method.
func (m *MockUserDatastore) FetchByVerificationToken(ctx context.Context, token string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByVerificationToken", ctx, token)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByVerificationToken indicates an expected call of FetchByVerificationToken.
func (mr *MockUserDatastoreMockRecorder) FetchByVerificationToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByVerificationToken", reflect.TypeOf((*MockUserDatastore)(nil).FetchByVerificationToken), ctx, token)
}

// MarkVerified mocks base method.
func (m *MockUserDatastore) MarkVerified(ctx context.Context, request identity.MarkUserVerifiedRequest) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkVerified", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkVerified indicates an expected call of MarkVerified.
func (mr *MockUserDatastoreMockRecorder) MarkVerified(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkVerified", reflect.TypeOf((*MockUserDatastore)(nil).MarkVerified), ctx, request)
}

// Save mocks base method.
func (m *MockUserDatastore) Save(ctx context.Context, request identity.User) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockUserDatastoreMockRecorder) Save(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserDatastore)(nil).Save), ctx, request)
}

// SoftDelete mocks base method.
func (m *MockUserDatastore) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUserDatastoreMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUserDatastore)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockUserDatastore) Update(ctx context.Context, request identity.User) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserDatastoreMockRecorder) Update(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserDatastore)(nil).Update), ctx, request)
}

// UpdateMetadata mocks base method.
func (m *MockUserDatastore) UpdateMetadata(ctx context.Context, request identity.UpdateUserMetadataVerificationRequest) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetadata", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMetadata indicates an expected call of UpdateMetadata.
func (mr *MockUserDatastoreMockRecorder) UpdateMetadata(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetadata", reflect.TypeOf((*MockUserDatastore)(nil).UpdateMetadata), ctx, request)
}

// UpdatePassword mocks base method.
func (m *MockUserDatastore) UpdatePassword(ctx context.Context, request identity.UpdateUserPasswordRequest) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserDatastoreMockRecorder) UpdatePassword(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserDatastore)(nil).UpdatePassword), ctx, request)
}

// UpdateStatus mocks base method.
func (m *MockUserDatastore) UpdateStatus(ctx context.Context, request identity.UpdateUserStatusRequest) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockUserDatastoreMockRecorder) UpdateStatus(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockUserDatastore)(nil).UpdateStatus), ctx, request)
}

// UpdateVerification mocks base method.
func (m *MockUserDatastore) UpdateVerification(ctx context.Context, request identity.UpdateUserVerificationRequest) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerification", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVerification indicates an expected call of UpdateVerification.
func (mr *MockUserDatastoreMockRecorder) UpdateVerification(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerification", reflect.TypeOf((*MockUserDatastore)(nil).UpdateVerification), ctx, request)
}

// MockUserWriteDatastore is a mock of UserWriteDatastore interface.
type MockUserWriteDatastore struct {
	ctrl     *gomock.Controller
	recorder *MockUserWriteDatastoreMockRecorder
	isgomock struct{}
}

// MockUserWriteDatastoreMockRecorder is the mock recorder for MockUserWriteDatastore.
type MockUserWriteDatastoreMockRecorder struct {
	mock *MockUserWriteDatastore
}

// NewMockUserWriteDatastore creates a new mock instance.
func NewMockUserWriteDatastore(ctrl *gomock.Controller) *MockUserWriteDatastore {
	mock := &MockUserWriteDatastore{ctrl: ctrl}
	mock.recorder = &MockUserWriteDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserWriteDatastore) EXPECT() *MockUserWriteDatastoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserWriteDatastore) Create(ctx context.Context, request identity.CreateUserRequest) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserWriteDatastoreMockRecorder) Create(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserWriteDatastore)(nil).Create), ctx, request)
}

// Delete mocks base method.
func (m *MockUserWriteDatastore) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserWriteDatastoreMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserWriteDatastore)(nil).Delete), ctx, id)
}

// MarkVerified mocks base method.
func (m *MockUserWriteDatastore) MarkVerified(ctx context.Context, request identity.MarkUserVerifiedRequest) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkVerified", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkVerified indicates an expected call of MarkVerified.
func (mr *MockUserWriteDatastoreMockRecorder) MarkVerified(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkVerified", reflect.TypeOf((*MockUserWriteDatastore)(nil).MarkVerified), ctx, request)
}

// Save mocks base method.
func (m *MockUserWriteDatastore) Save(ctx context.Context, request identity.User) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockUserWriteDatastoreMockRecorder) Save(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserWriteDatastore)(nil).Save), ctx, request)
}

// SoftDelete mocks base method.
func (m *MockUserWriteDatastore) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUserWriteDatastoreMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUserWriteDatastore)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockUserWriteDatastore) Update(ctx context.Context, request identity.User) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserWriteDatastoreMockRecorder) Update(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserWriteDatastore)(nil).Update), ctx, request)
}

// UpdateMetadata mocks base method.
func (m *MockUserWriteDatastore) UpdateMetadata(ctx context.Context, request identity.UpdateUserMetadataVerificationRequest) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetadata", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMetadata indicates an expected call of UpdateMetadata.
func (mr *MockUserWriteDatastoreMockRecorder) UpdateMetadata(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetadata", reflect.TypeOf((*MockUserWriteDatastore)(nil).UpdateMetadata), ctx, request)
}

// UpdatePassword mocks base method.
func (m *MockUserWriteDatastore) UpdatePassword(ctx context.Context, request identity.UpdateUserPasswordRequest) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserWriteDatastoreMockRecorder) UpdatePassword(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserWriteDatastore)(nil).UpdatePassword), ctx, request)
}

// UpdateStatus mocks base method.
func (m *MockUserWriteDatastore) UpdateStatus(ctx context.Context, request identity.UpdateUserStatusRequest) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockUserWriteDatastoreMockRecorder) UpdateStatus(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockUserWriteDatastore)(nil).UpdateStatus), ctx, request)
}

// UpdateVerification mocks base method.
func (m *MockUserWriteDatastore) UpdateVerification(ctx context.Context, request identity.UpdateUserVerificationRequest) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerification", ctx, request)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVerification indicates an expected call of UpdateVerification.
func (mr *MockUserWriteDatastoreMockRecorder) UpdateVerification(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerification", reflect.TypeOf((*MockUserWriteDatastore)(nil).UpdateVerification), ctx, request)
}

// MockUserReadDatastore is a mock of UserReadDatastore interface.
type MockUserReadDatastore struct {
	ctrl     *gomock.Controller
	recorder *MockUserReadDatastoreMockRecorder
	isgomock struct{}
}

// MockUserReadDatastoreMockRecorder is the mock recorder for MockUserReadDatastore.
type MockUserReadDatastoreMockRecorder struct {
	mock *MockUserReadDatastore
}

// NewMockUserReadDatastore creates a new mock instance.
func NewMockUserReadDatastore(ctrl *gomock.Controller) *MockUserReadDatastore {
	mock := &MockUserReadDatastore{ctrl: ctrl}
	mock.recorder = &MockUserReadDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserReadDatastore) EXPECT() *MockUserReadDatastoreMockRecorder {
	return m.recorder
}

// FetchAll mocks base method.
func (m *MockUserReadDatastore) FetchAll(ctx context.Context, params common.RequestParams) (repository.FetchRecordsResponse[identity.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, params)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[identity.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUserReadDatastoreMockRecorder) FetchAll(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUserReadDatastore)(nil).FetchAll), ctx, params)
}

// FetchByEmail mocks base method.
func (m *MockUserReadDatastore) FetchByEmail(ctx context.Context, email string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByEmail", ctx, email)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByEmail indicates an expected call of FetchByEmail.
func (mr *MockUserReadDatastoreMockRecorder) FetchByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByEmail", reflect.TypeOf((*MockUserReadDatastore)(nil).FetchByEmail), ctx, email)
}

// FetchById mocks base method.
func (m *MockUserReadDatastore) FetchById(ctx context.Context, id string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchById", ctx, id)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchById indicates an expected call of FetchById.
func (mr *MockUserReadDatastoreMockRecorder) FetchById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchById", reflect.TypeOf((*MockUserReadDatastore)(nil).FetchById), ctx, id)
}

// FetchByStatus mocks base method.
func (m *MockUserReadDatastore) FetchByStatus(ctx context.Context, status identity.UserStatus) (repository.FetchRecordsResponse[identity.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByStatus", ctx, status)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[identity.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByStatus indicates an expected call of FetchByStatus.
func (mr *MockUserReadDatastoreMockRecorder) FetchByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByStatus", reflect.TypeOf((*MockUserReadDatastore)(nil).FetchByStatus), ctx, status)
}

// FetchByUsername mocks base method.
func (m *MockUserReadDatastore) FetchByUsername(ctx context.Context, username string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUsername", ctx, username)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUsername indicates an expected call of FetchByUsername.
func (mr *MockUserReadDatastoreMockRecorder) FetchByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUsername", reflect.TypeOf((*MockUserReadDatastore)(nil).FetchByUsername), ctx, username)
}

// FetchByVerificationToken mocks base method.
func (m *MockUserReadDatastore) FetchByVerificationToken(ctx context.Context, token string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByVerificationToken", ctx, token)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByVerificationToken indicates an expected call of FetchByVerificationToken.
func (mr *MockUserReadDatastoreMockRecorder) FetchByVerificationToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByVerificationToken", reflect.TypeOf((*MockUserReadDatastore)(nil).FetchByVerificationToken), ctx, token)
}
