// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/domain/identity/user_repository.go
//
// Generated by this command:
//
//	mockgen -destination=app/internal/domain/identity/mocks/mock_user_repository.go -package=mockidentity -source=app/internal/domain/identity/user_repository.go
//

// Package mockidentity is a generated GoMock package.
package mockidentity

import (
	context "context"
	reflect "reflect"

	repository "github.com/sanctumlabs/curtz/app/internal/core/ports/repository"
	identity "github.com/sanctumlabs/curtz/app/internal/domain/identity"
	common "github.com/sanctumlabs/curtz/app/internal/pkg/common"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, entity identity.User) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), ctx, id)
}

// FetchAll mocks base method.
func (m *MockUserRepository) FetchAll(ctx context.Context, params common.RequestParams) (repository.FetchRecordsResponse[identity.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, params)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[identity.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUserRepositoryMockRecorder) FetchAll(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUserRepository)(nil).FetchAll), ctx, params)
}

// FetchByEmail mocks base method.
func (m *MockUserRepository) FetchByEmail(ctx context.Context, email string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByEmail", ctx, email)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByEmail indicates an expected call of FetchByEmail.
func (mr *MockUserRepositoryMockRecorder) FetchByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByEmail", reflect.TypeOf((*MockUserRepository)(nil).FetchByEmail), ctx, email)
}

// FetchById mocks base method.
func (m *MockUserRepository) FetchById(ctx context.Context, id string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchById", ctx, id)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchById indicates an expected call of FetchById.
func (mr *MockUserRepositoryMockRecorder) FetchById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchById", reflect.TypeOf((*MockUserRepository)(nil).FetchById), ctx, id)
}

// FetchByStatus mocks base method.
func (m *MockUserRepository) FetchByStatus(ctx context.Context, status identity.UserStatus) (repository.FetchRecordsResponse[identity.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByStatus", ctx, status)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[identity.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByStatus indicates an expected call of FetchByStatus.
func (mr *MockUserRepositoryMockRecorder) FetchByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByStatus", reflect.TypeOf((*MockUserRepository)(nil).FetchByStatus), ctx, status)
}

// FetchByUsername mocks base method.
func (m *MockUserRepository) FetchByUsername(ctx context.Context, username string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUsername", ctx, username)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUsername indicates an expected call of FetchByUsername.
func (mr *MockUserRepositoryMockRecorder) FetchByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUsername", reflect.TypeOf((*MockUserRepository)(nil).FetchByUsername), ctx, username)
}

// SoftDelete mocks base method.
func (m *MockUserRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUserRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUserRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, entity identity.User) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, entity)
}

// MockUserWriteRepository is a mock of UserWriteRepository interface.
type MockUserWriteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserWriteRepositoryMockRecorder
	isgomock struct{}
}

// MockUserWriteRepositoryMockRecorder is the mock recorder for MockUserWriteRepository.
type MockUserWriteRepositoryMockRecorder struct {
	mock *MockUserWriteRepository
}

// NewMockUserWriteRepository creates a new mock instance.
func NewMockUserWriteRepository(ctrl *gomock.Controller) *MockUserWriteRepository {
	mock := &MockUserWriteRepository{ctrl: ctrl}
	mock.recorder = &MockUserWriteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserWriteRepository) EXPECT() *MockUserWriteRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserWriteRepository) Create(ctx context.Context, entity identity.User) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserWriteRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserWriteRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockUserWriteRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserWriteRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserWriteRepository)(nil).Delete), ctx, id)
}

// SoftDelete mocks base method.
func (m *MockUserWriteRepository) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUserWriteRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUserWriteRepository)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockUserWriteRepository) Update(ctx context.Context, entity identity.User) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserWriteRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserWriteRepository)(nil).Update), ctx, entity)
}

// MockUserReadRepository is a mock of UserReadRepository interface.
type MockUserReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserReadRepositoryMockRecorder
	isgomock struct{}
}

// MockUserReadRepositoryMockRecorder is the mock recorder for MockUserReadRepository.
type MockUserReadRepositoryMockRecorder struct {
	mock *MockUserReadRepository
}

// NewMockUserReadRepository creates a new mock instance.
func NewMockUserReadRepository(ctrl *gomock.Controller) *MockUserReadRepository {
	mock := &MockUserReadRepository{ctrl: ctrl}
	mock.recorder = &MockUserReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserReadRepository) EXPECT() *MockUserReadRepositoryMockRecorder {
	return m.recorder
}

// FetchAll mocks base method.
func (m *MockUserReadRepository) FetchAll(ctx context.Context, params common.RequestParams) (repository.FetchRecordsResponse[identity.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, params)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[identity.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUserReadRepositoryMockRecorder) FetchAll(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUserReadRepository)(nil).FetchAll), ctx, params)
}

// FetchByEmail mocks base method.
func (m *MockUserReadRepository) FetchByEmail(ctx context.Context, email string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByEmail", ctx, email)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByEmail indicates an expected call of FetchByEmail.
func (mr *MockUserReadRepositoryMockRecorder) FetchByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByEmail", reflect.TypeOf((*MockUserReadRepository)(nil).FetchByEmail), ctx, email)
}

// FetchById mocks base method.
func (m *MockUserReadRepository) FetchById(ctx context.Context, id string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchById", ctx, id)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchById indicates an expected call of FetchById.
func (mr *MockUserReadRepositoryMockRecorder) FetchById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchById", reflect.TypeOf((*MockUserReadRepository)(nil).FetchById), ctx, id)
}

// FetchByStatus mocks base method.
func (m *MockUserReadRepository) FetchByStatus(ctx context.Context, status identity.UserStatus) (repository.FetchRecordsResponse[identity.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByStatus", ctx, status)
	ret0, _ := ret[0].(repository.FetchRecordsResponse[identity.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByStatus indicates an expected call of FetchByStatus.
func (mr *MockUserReadRepositoryMockRecorder) FetchByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByStatus", reflect.TypeOf((*MockUserReadRepository)(nil).FetchByStatus), ctx, status)
}

// FetchByUsername mocks base method.
func (m *MockUserReadRepository) FetchByUsername(ctx context.Context, username string) (identity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUsername", ctx, username)
	ret0, _ := ret[0].(identity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUsername indicates an expected call of FetchByUsername.
func (mr *MockUserReadRepositoryMockRecorder) FetchByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUsername", reflect.TypeOf((*MockUserReadRepository)(nil).FetchByUsername), ctx, username)
}
