package url

import (
	"regexp"

	"github.com/sanctumlabs/curtz/app/pkg/errdefs"
)

// ShortCode is a value object generated by the ShortCodeGenerator domain service.
// It is never generated inside the aggregate — the aggregate receives it.
type ShortCode struct {
	value string // base62, 6–10 chars
}

// Value returns the string value of the ShortCode.
func (sc ShortCode) Value() string {
	return sc.value
}

// NewShortCode creates a new ShortCode value object after validating the input.
func NewShortCode(value string) (ShortCode, error) {
	// Validate length
	if len(value) < 6 || len(value) > 10 {
		return ShortCode{}, errdefs.ErrShortCodeInvalidLength
	}

	// Validate characters (base62 only)
	matched, err := regexp.MatchString(`^[a-zA-Z0-9]+$`, value)
	if err != nil {
		return ShortCode{}, err
	}
	if !matched {
		return ShortCode{}, errdefs.ErrShortCodeInvalidCharacters
	}

	return ShortCode{value: value}, nil
}
