package urlrepo

import (
	"context"

	postgresql "github.com/sanctumlabs/curtz/app/internal/adapters/postgres/sql"
)

// UrlWriteQuerier defines the subset of SQL operations needed for URL writes.
// Using an interface here lets tests inject a mock instead of a real DB connection.
// The concrete *postgresql.Queries type (generated by sqlc) satisfies this interface.
type UrlWriteQuerier interface {
	QueryUrlStatusByName(ctx context.Context, name string) (postgresql.UrlStatus, error)
	QueryCreateUrl(ctx context.Context, params postgresql.QueryCreateUrlParams) (postgresql.Url, error)
	QueryCreateKeyword(ctx context.Context, params postgresql.QueryCreateKeywordParams) (postgresql.Keyword, error)
}
