# Ref: https://github.com/wangchucheng/git-repo-sync
name: BitBucket RepoSync

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Bitbucket Repo Sync
    steps:

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Mirror to Bitbucket
      uses: wangchucheng/git-repo-sync@63782025e80e84c48b25a1ee6bb9a22a3bd570d3 # v0.1.0
      with:
        # Such as https://bitbucket.org/SomeUser/some-repo-sync.git
        target-url: ${{ secrets.BITBUCKET_REPO_URL }}
        # Such as SomeUser
        target-username: ${{ secrets.BITBUCKET_USERNAME }}
        # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS_TOKEN }}
        target-token: ${{ secrets.BITBUCKET_ACCESS_TOKEN }}
