name: Deploy

on:
  workflow_run:
    workflows:
      - "Build"
    branches:
      - 'main'
    types:
      - completed

jobs:

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      # https://github.com/superfly/flyctl-actions
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl secrets set DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          flyctl secrets set DATABASE=${{ secrets.DATABASE }}
          flyctl secrets set DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
          flyctl secrets set DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD}}
          flyctl secrets set DATABASE_PORT=${{ secrets.DATABASE_PORT }}
          flyctl secrets set AUTH_SECRET=${{ secrets.AUTH_SECRET }}
          flyctl secrets set AUTH_EXPIRE=${{ secrets.AUTH_EXPIRE }}
          flyctl secrets set AUTH_ISSUER=${{ secrets.AUTH_ISSUER }}
          flyctl secrets set CACHE_HOST=${{ secrets.CACHE_HOST }}
          flyctl secrets set CACHE_PORT=${{ secrets.CACHE_PORT }}
          flyctl secrets set CACHE_USERNAME=${{ secrets.CACHE_USERNAME }}
          flyctl secrets set CACHE_PASSWORD=${{ secrets.CACHE_PASSWORD }}
          flyctl secrets set CACHE_REQUIRE_AUTH=${{ secrets.CACHE_REQUIRE_AUTH }}
          flyctl secrets set SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          flyctl secrets set SENTRY_ENV=${{ secrets.SENTRY_ENV }}
          flyctl secrets set SENTRY_SAMPLE_RATE=${{ secrets.SENTRY_SAMPLE_RATE }}
          flyctl secrets set SENTRY_ENABLED=${{ secrets.SENTRY_ENABLED }}
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
