name: Sentry Release

on:
  workflow_run:
    workflows:
      - "Build"
    types:
      - completed
    branches:
      - main

jobs:
  sentryrelease:
    name: Sentry Release

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install Dependencies
      run: make install

    - name: Run Build
      run: make build

    - name: Create Sentry Staging release
      if: github.ref_name == 'develop'
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_GH_RELEASE_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: staging

    - name: Create Sentry Production release
      if: github.ref_name == 'main'
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_GH_RELEASE_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production