name: Tests

on:
  workflow_run:
    workflows:
      - "Lint"
    types:
      - completed

permissions:
  contents: read

jobs:
  unit_tests:
     strategy:
       matrix:
         go-version: [ '1.25' ]
     name: Unit Tests (Go ${{ matrix.go-version }})
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     uses: SanctumLabs/ci-workflows/.github/workflows/go-test.yml@main
     with:
       go-version: ${{ matrix.go-version }}
       command: make test.coverage
     secrets:
       codacy_token: ${{ secrets.CODACY_PROJECT_TOKEN }}

  integration_tests:
     strategy:
       matrix:
         go-version: [ '1.25' ]
     name: Integration Tests (Go ${{ matrix.go-version }})
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     uses: SanctumLabs/ci-workflows/.github/workflows/go-test.yml@main
     with:
       go-version: ${{ matrix.go-version }}
       command: make test.integration
       database-image-name: dhi.io/postgres
       database-image-version: 18-alpine3.23-dev
       database-name: curtz_database_test
       database-username: curtz_user
       database-password: curtz_password
       database-port: 5432
       database-port-internal: 5432
