// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/ports/notifier.go
//
// Generated by this command:
//
//	mockgen -destination=app/internal/ports/mocks/mock_notifier.go -package=mockports -source=app/internal/ports/notifier.go
//

// Package mockports is a generated GoMock package.
package mockports

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// SendEmailVerification mocks base method.
func (m *MockNotifier) SendEmailVerification(ctx context.Context, recipient, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailVerification", ctx, recipient, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmailVerification indicates an expected call of SendEmailVerification.
func (mr *MockNotifierMockRecorder) SendEmailVerification(ctx, recipient, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailVerification", reflect.TypeOf((*MockNotifier)(nil).SendEmailVerification), ctx, recipient, token)
}
